### ISSUE TITLE
Twitter image problem.

### ISSUE THREAD

**Issue by ArielZ123** [project-error/npwd#1001]
### Development Issue

Yes

### Phone Version

1.7.0->Latest

### Issue Description

When clicking on the image in the Twitter application, the image appears on the entire screen.
![image](https://github.com/project-error/npwd/assets/74502022/26b027af-0e2a-4729-a028-84a4b93221a0)

### Issue Reproduction

Just upload am image to the twitter and click on it...

### Evidence

![image](https://github.com/project-error/npwd/assets/74502022/4023f840-f826-4e16-9603-20d531c062db)

**Comment by ArielZ123** [comment]
Same

**Comment by GlitchOo** [comment]
Is this happening with any image? Or just this one in particular?

**Comment by ArielZ123** [comment]
> Is this happening with any image? Or just this one in particular?

Any image mate.

**Comment by GlitchOo** [comment]
Im working on the image popup models so ill do some testing

**Comment by ArielZ123** [comment]
> Im working on the image popup models so ill do some testing

Ok if you have a fix I will be happy to get a download link here mate☺️.
@GlitchOo

**Comment by GlitchOo** [comment]
> 

I should have fixed in this commit . I tested it and it seems to be working perfectly. 83d4e0c486f0f7f6520e8dcb4ba3b113790866aa

You can download in this test release I have up that also brings other changes and bug fixes from previous commits until I have time to do a PR
https://github.com/GlitchOo/npwd/releases/tag/1.7.1-G

https://i.gyazo.com/58b1d06c016e8dc67b81f796450637dd.jpg

**Comment by LiamDormon** [comment]
I believe this was fixed a while ago on the master branch but never made it to a stable release.

**Comment by ArielZ123** [comment]
> I believe this was fixed a while ago on the master branch but never made it to a stable release.

I downloaded the phone a week ago or two and I had this problem..

**Comment by LiamDormon** [comment]
> > I believe this was fixed a while ago on the master branch but never made it to a stable release.
> 
> I downloaded the phone a week ago or two and I had this problem.. @LiamDormon

And?

**Comment by ArielZ123** [comment]
> > > I believe this was fixed a while ago on the master branch but never made it to a stable release.
> > 
> > 
> > I downloaded the phone a week ago or two and I had this problem.. @LiamDormon
> 
> And?

It means that they didn't fix that....

**Comment by LiamDormon** [comment]
> > > > I believe this was fixed a while ago on the master branch but never made it to a stable release.
> > > 
> > > 
> > > I downloaded the phone a week ago or two and I had this problem.. @LiamDormon
> > 
> > 
> > And?
> 
> It means that they didn't fix that.... @LiamDormon

I said that it never made it to a stable release...

**Comment by ArielZ123** [comment]
> > > > > I believe this was fixed a while ago on the master branch but never made it to a stable release.
> > > > 
> > > > 
> > > > I downloaded the phone a week ago or two and I had this problem.. @LiamDormon
> > > 
> > > 
> > > And?
> > 
> > 
> > It means that they didn't fix that.... @LiamDormon
> 
> I said that it never made it to a stable release... The fix is there but only on master branch which is currently broken
Ok all good then...

**Comment by ArielZ123** [comment]
Hi mate, getting a new problem with your fix while trying to upload pic to
twitter.

**Comment by ArielZ123** [comment]
> Make sure you setup your config.json correctly

There is no config file in your download, added one according to the steps and I have the same problem.
@GlitchOo
