### ISSUE TITLE
Bug: Not able to tweet without image

### ISSUE THREAD

**Issue by Akemimimi** [project-error/npwd#1011]
### Development Issue

Unsure

### Phone Version

v1.7.1
I downloaded the release and got qb-npwd aswell, set everything up like mentioned in the documentation

### Issue Description

Tweets without images don't work

### Issue Reproduction

I opened the phone, clicked on twitter and tried tweeting without an image attached but it doesn't work. Even the box where you put in the text doesn't disappear if I click on tweet. I don't get any errors anywhere. Tweeting with an image does work tho but I have to close the twitter app for it to appear in there.

**Comment by Akemimimi** [comment]
Nevermind I found an oopsie in my database that I somehow missed

**Comment by AvarianKnight** [comment]
If you have another feel free to open another issue :)

**Comment by 2Girls1CJ** [comment]
what was the issue im having the same problem, the tweet button doesnt work

**Comment by domzel123** [comment]
what do you mean "let i rebuild"? I am trying to fix this issue as well

**Comment by AdiTechs10** [comment]
How did you fix this issue im having the same problem?
