### ISSUE TITLE
Bug: SCRIPT ERROR: @pe-core/server/sv_main.lua:29: No such export newPlayer in resource npwd 

### ISSUE THREAD

**Issue by KaiKingStreams** [project-error/npwd#1012]
### Development Issue

No

### Phone Version

v1.7.1

### Issue Description

So had to use PE-Core with it but keep getting a error after we try to rejoin the server

### Issue Reproduction

Add function to the config 

### Evidence

![image](https://github.com/project-error/npwd/assets/59054276/2a39f03a-8397-4828-be17-1a4723a74ca2)

**Comment by RobijnGit** [comment]
Did you download the source or the build?

**Comment by KaiKingStreams** [comment]
build

**Comment by KaiKingStreams** [comment]
We are a vMenu server and have NAT2K15 Framework

**Comment by LiamDormon** [comment]
Configuration error, not an issue, We have support channels for this kind of thing.
