### ISSUE TITLE
Bug: Messaging notifications do not show if you have not yet opened the message conversation

### ISSUE THREAD

**Issue by BackSH00TER** [project-error/npwd#1017]
### Development Issue

No

### Phone Version

v1.7.1 (latest)

### Issue Description

If a user has not opened the Message app, and then receives a text message, they will not see a notification popup.

The user has to first open the Message app and navigate to the conversation. Only then will they begin to start seeing the notifications for that message conversation.

### Issue Reproduction

1. Player 1 and 2 logs into the server
2. Player 2 sends a message through the Messaging app to Player 1 in their 1:1 message conversation 
3. The message is successfully sent from Player 2
4. Player 1 does not see anything on their end
5. Player 1 opens the phone app, navigates to Messaging app, and sees a unread pill count of 1 on the conversation with Player 2
6. Player 1 closes the app
7. Player 2 sends another message to Player 1
8. Player 1 now successfully sees the notification popup

Repro rate: 100%

Tried the same repro steps with Twitter and other apps that have notifications but was unable to reproduce on those apps.
My hunch is that this may have something to do with the routes of conversations being semi-dynamic (where its like message/conversationId or something like that), whereas the routes for Twitter and other apps are static and do not change.

**Comment by itschip** [comment]
This should be fixed.
