### ISSUE TITLE
Bug: Failed to upload audio

### ISSUE THREAD

**Issue by zzettazz** [project-error/npwd#1044]
### Development Issue

Yes

### Phone Version

1.7.2

### Issue Description

Cant send voice messages

### Issue Reproduction

1. Open phone
2. Try to send a voice message

### Evidence

![image](https://github.com/project-error/npwd/assets/131651123/5cce79ca-4c66-4d8d-9c33-a27427ea1816)
![image](https://github.com/project-error/npwd/assets/131651123/28181489-b091-4b18-ba45-08358cd4c64d)

**Comment by itschip** [comment]
Where did you add the api token? (dont show the token)

**Comment by zzettazz** [comment]
config.json:

"voiceMessage": {
    "enabled": true,
    "authorizationHeader": "Authorization",
    "url": "https://api.fivemanage.com/api/audio",
    "returnedDataIndexes": ["url"]
  }, 

Server.cfg: 
set NPWD_AUDIO_TOKEN my_token

**Comment by itschip** [comment]
Are you sure that the token you have passed is correct? I'll update the error message, so we get some more details about what's happening, but it seems like the token does not exist

**Comment by zzettazz** [comment]
Yes, also generated a new token, and also got same error

**Comment by itschip** [comment]
@zzettazz please try again now.

**Comment by zzettazz** [comment]
Still getting error message

**Comment by zzettazz** [comment]
Error getting messages

**Comment by itschip** [comment]
Please create a new issue :)
