### ISSUE TITLE
Bug: The image host you tried to use is not allowed by this server

### ISSUE THREAD

**Issue by Akyrano** [project-error/npwd#1046]
### Development Issue

Unsure

### Phone Version

Latest

### Issue Description

I am using fivemanage for host my images. When I take pics with the camera it works. they are stocked. I can send this image in a message but when I want to tweet, or adding a pic in the marketplace, change the tinder and twitter profil pic I got the "The image host you tried to use is not allowed by this server" error. 

### Issue Reproduction

1. Upload image : Twitter, Marketplace
2. Change profil Pic in twitter and Tinder

### Evidence

![phonenpwd](https://github.com/project-error/npwd/assets/140458046/c3159217-8bd5-4cd2-adac-5b1743283872)

**Comment by itschip** [comment]
Ah, yes. Thank you. @LiamDormon can you fix this one?

**Comment by AvarianKnight** [comment]
You can get the fix in https://github.com/project-error/npwd/releases/tag/v1.7.3
