### ISSUE TITLE
Bug: missing export setPhoneDisabled

### ISSUE THREAD

**Issue by MauriceHandwerker** [project-error/npwd#1057]
### Development Issue

Unsure

### Phone Version

FiveM Linux  Artifact : 6895
ESX Legacy : 1.10.1
NPWD : 1.7.3
esx-npwd : 08.08.2023  (https://github.com/overextended/esx-npwd)

### Issue Description

I already have a tread in the discord open. But I think it should be a real issue.

I get this error in the client log:
![image](https://github.com/project-error/npwd/assets/66009198/cc610774-ddc7-4622-88f2-88f2586b0cd2)

This is my config.json
```json
{
  "PhoneAsItem": {
    "enabled": false,
    "exportResource": "my-core-resource",
    "exportFunction": "myCheckerFunction"
  },
  "general": {
    "useResourceIntegration": true,
    "toggleKey": "f1",
    "toggleCommand": "phone"
  },
  "contacts": {
    "frameworkPay": false,
    "payResource": "my-core-resource",
    "payFunction": "myCheckerFunction"
  },
  "profanityFilter": {
    "enabled": false,
    "badWords": ["esx"]
  },
  "database": {
    "useIdentifierPrefix": false,
    "playerTable": "users",
    "identifierColumn": "identifier",
    "identifierType": "license",
    "profileQueries": true,
    "phoneNumberColumn": "phone_number"
  },
  "debug": {
    "level": "error",
    "enabled": true,
    "sentryEnabled": true
  },
  "defaultContacts": [],
  "disabledApps": [],
  "apps": ["pefcl"],
  "voiceMessage": {
    "enabled": false,
    "authorizationHeader": "PE-Secret",
    "url": "",
    "returnedDataIndexes": ["url"]
  },
"images":{
  "useWebhook": true
}
}
```

And this is my cfg:
```cfg
ensure pma-voice
ensure esx-npwd         # [phone]
ensure npwd             # [phone]
```

### Issue Reproduction

Use the resources & and server serion from above and try using the phone.

### Evidence

![image](https://github.com/project-error/npwd/assets/66009198/422b8193-b5fb-495d-9df6-92b315a641b2)

**Comment by Corentin28** [comment]
Same prolem, https://discord.com/channels/791854454760013827/1130536737135931522

**Comment by MauriceHandwerker** [comment]
Hey any new info?

**Comment by MauriceHandwerker** [comment]
From what I could find out he has an error reading the config.json. But still it should be able to get the export.

**Comment by itschip** [comment]
@MauriceHandwerker a new release is on the way from the latest pre-release (v1.7.4). You can check if that works when its' ready

**Comment by MauriceHandwerker** [comment]
I fixded the error:
You dont need the esx-npwd resource anymore. But you need to have a item with the lable 'phone' in your inventory. But the phone as item setting must be false. 
Then it works without warnings or errors. 
I dont know why.
