### ISSUE TITLE
bug: Install problem

### ISSUE THREAD

**Issue by wolfred85** [project-error/npwd#1062]
### Development Issue

Yes

### Phone Version

Qb core

### Issue Description

Hello, we have taken your phone from our Qb-Core server and unfortunately it is not working. We do F1 and we have a ghost message that appears without having the phone in physics. There are also files missing in the phone download. There is no HTML file that allows it to appear. It constantly asks where is the Phone item even though it is well configured. You can help me it's been 3 days since we've been on it and no response on discord. Do you have a solution to offer us? 

### Issue Reproduction

We have installed the phone and by pressing F1 we ​​have everything in the F8.

### Evidence

![Capture d'écran 2023-08-27 193927](https://github.com/project-error/npwd/assets/143408679/9d2cb5f8-2be1-4004-b6da-985ed0141681)
![Capture d'écran 2023-08-27 194026](https://github.com/project-error/npwd/assets/143408679/a67bd6c0-8534-40b4-8850-9e0b7c510ea1)
![Capture d'écran 2023-08-27 194242](https://github.com/project-error/npwd/assets/143408679/3a0839d9-debb-4835-a6fa-c38ec7dde562)
![Capture d'écran 2023-08-27 212335](https://github.com/project-error/npwd/assets/143408679/687e5741-76b0-4149-8685-2ac59bff4e60)
![Capture d'écran 2023-08-27 213132](https://github.com/project-error/npwd/assets/143408679/0b9a4213-2aae-4656-a804-451bfe76b92b)

**Comment by itschip** [comment]
Looks like you have a script that's using the same keybinds. You can change that both in-game and in the npwd config.json

**Comment by itschip** [comment]
Please refer to our Discord for more support.
