### ISSUE TITLE
Bug: no default "no image" image

### ISSUE THREAD

**Issue by maejok-xx** [project-error/npwd#1067]
### Development Issue

Unsure

### Phone Version

1.7.3 source and release

### Issue Description

When adding or viewing contacts, there's no default image for "no image".

### Issue Reproduction

- yarn/pnpm install; yarn build. -or- Download release and extract
- ensure npwd from resources root
- add/edit contact

### Evidence

![image](https://github.com/project-error/npwd/assets/12991886/78d22a1e-268c-419a-b183-9c3b21e6a116)
![image](https://github.com/project-error/npwd/assets/12991886/2738b6e2-1984-400f-8894-bc0202b589ee)
![image](https://github.com/project-error/npwd/assets/12991886/230c66a4-a4f1-44bf-ba1c-559fe1813385)

**Comment by itschip** [comment]
This is fixed in the latest version.
