### ISSUE TITLE
Bug: ESX Integration Documentation Error

### ISSUE THREAD

**Issue by MauriceHandwerker** [project-error/npwd#1069]
### Development Issue

No

### Phone Version

-

### Issue Description

In the [documentation](https://projecterror.dev/docs/npwd/framework/esx) Is a link to the esx-npwd resource. But this resource doesent work with the newest npwd versions anymore (I dont know why). 
The documentation should be updated to work with the [export repo](https://github.com/project-error/phone_export) instead. 
But you dont need the export. 
The newest esx Legacy versions have npwd support included.
But you need to have a item with the lable 'phone' and the setting PhoneAsItem doesent matter. I think that should be fixed.

### Issue Reproduction

-

### Evidence

https://projecterror.dev/docs/npwd/framework/esx

#1057

**Comment by itschip** [comment]
Will check it out during the week

**Comment by MauriceHandwerker** [comment]
ok

**Comment by ThiaudioTT** [comment]
I was having some random issues installing npwd in ESX 1.10 like [Object object] and missing dependencies. 

> But you need to have a item with the lable 'phone' and the setting PhoneAsItem doesent matter. 

I did what @MauriceHandwerker said. I inserted `'phone'` in inventory and it fixed.

There's also this doc in esx but this didn't help me much.

https://documentation.esx-framework.org/tutorials/tutorials-esx/npwd

And also code:
https://github.com/esx-framework/esx_core/blob/main/%5Bcore%5D/es_extended/client/modules/npwd.lua

**Comment by MauriceHandwerker** [comment]
Yea Im currently working on fixing all the documentation.

**Comment by MauriceHandwerker** [comment]
My documentation update went through. You can now follow the documentation :white_check_mark:
