### ISSUE TITLE
Enhancement: Built-in Saltychat support

### ISSUE THREAD

**Issue by Tfc538** [project-error/npwd#1093]
### Application

Other

### Dependency

No

### Feature Description

As many others i‘d like to see a setting for saltychat (and maybe others like TokoVoip). I could make a PR Later that does that.

### References

Examples:

https://github.com/Zerofour04/gcphone-saltychat

SaltyChat Exports:

exports {
    'GetVoiceRange',
    'GetRadioChannel',
    'GetRadioVolume',
    'GetRadioSpeaker',
    'GetMicClick',
    'SetRadioChannel',
    'SetRadioVolume',
    'SetRadioSpeaker',
    'SetMicClick',
    'GetPluginState',
    'PlaySound'
}

server_export 'GetPlayerAlive'
server_export 'SetPlayerAlive'
server_export 'GetPlayerVoiceRange'
server_export 'SetPlayerVoiceRange'
server_export 'EstablishCall'
server_export 'EndCall'
server_export 'GetPlayersInRadioChannel'
server_export 'SetPlayerRadioSpeaker'
server_export 'SetPlayerRadioChannel'
server_export 'RemovePlayerRadioChannel'
server_export 'SetRadioTowers'

**Comment by Ehbw** [comment]
https://github.com/project-error/npwd/issues/659

**Comment by TonybynMp4** [comment]
no way people still ask for saltychat in 2023 💀
