### ISSUE TITLE
Set up with QBCore

### ISSUE THREAD

**Issue by mayres12090** [project-error/npwd#1108]
### Development Issue

Unsure

### Phone Version

Newest version

### Issue Description

Ive followed the instructions provided, but the console is giving me 2 errors. Trying to figure it out. 

https://i.imgur.com/70c1hf9.png

### Issue Reproduction

Not yet

**Comment by itschip** [comment]
Doesn't seem like you've downloaded the release files, but the source code. 

If you're sure you have, make sure qb-npwd is ensured before npwd

**Comment by mayres12090** [comment]
Yeah that ended up fixing that issue.  Now it's just saying no export found HasPhone. I'm surprised I've only got that one error.  I'm new to all of this, so I try to read closely and follow everything to a T.

**Comment by mayres12090** [comment]
Note to self, Dont work on a major project like a phone when you have been up for almost 24 hours. My server.cfg had ensure in front of qb-npwd twice.

**Comment by itschip** [comment]
@mayres12090 if it's solved, please close the issue when u can :)

**Comment by mayres12090** [comment]
Will do, there was another issue that led me to just delete the phone.  The photo's wasn't working.  I even linked everything as I should.  All the apps didn't show, but I just ended up deleting the resource.  Other than the camera issue it did seem like a pretty cool phone.
