### ISSUE TITLE
Bug: but with esx-npwd/npwd when log/relog with character

### ISSUE THREAD

**Issue by xsoskiller** [project-error/npwd#1124]
### Development Issue

Unsure

### Phone Version

3.11.0

### Issue Description

i got those error when i log in a character and unload a character

> [     script:esx-npwd] SCRIPT ERROR: @esx-npwd/server.lua:18: No such export newPlayer in resource npwd
> [     script:esx-npwd] > loadESXPlayer (@es_extended/server/main.lua:298)
> [     script:esx-npwd] > handler (@es_extended/server/main.lua:28)
> [     script:esx-npwd] > rawExecute (@oxmysql/dist/build.js:25166)
> [     script:esx-npwd] > processTicksAndRejections (node:internal/process/task_queues:96)
> [  script:es_extended] [INFO] Player "asdasd asdsadsa" has connected to the server. ID: 1
> [     script:esx-npwd] SCRIPT ERROR: @esx-npwd/server.lua:27: No such export unloadPlayer in resource npwd
> [     script:esx-npwd] > handler (@renzu_multicharacter/server/main.lua:50)
> [  script:es_extended] [INFO] Saved player "asdasd asdsadsa"
> [     script:esx-npwd] SCRIPT ERROR: @esx-npwd/server.lua:18: No such export newPlayer in resource npwd
> [     script:esx-npwd] > loadESXPlayer (@es_extended/server/main.lua:298)
> [     script:esx-npwd] > handler (@es_extended/server/main.lua:28)
> [     script:esx-npwd] > rawExecute (@oxmysql/dist/build.js:25166)
> [     script:esx-npwd] > processTicksAndRejections (node:internal/process/task_queues:96)

Multicharacter script i use: Renzu_multicharacter
i don't know if you can help me with that.

### Issue Reproduction

log in/relog

### Evidence

![image](https://github.com/project-error/npwd/assets/66858021/f6c868e4-b3ca-4dd1-8ad7-a1738cb516c9)

**Comment by itschip** [comment]
You need to set `useResourceIntegration` to `true` in the config.json file for npwd

**Comment by xsoskiller** [comment]
![image](https://github.com/project-error/npwd/assets/66858021/768c851b-f7de-4e80-9225-8030757dbf0a)

already at true

**Comment by itschip** [comment]
@xsoskiller make sure that you have the release files of `npwd` and that `esx-npwd` is ensured before `npwd`

Try restarting your server afterwards.

**Comment by xsoskiller** [comment]
i'll download the last version and try of both

**Comment by xsoskiller** [comment]
alright it seem to be ok now thx
