### ISSUE TITLE
Issue removing from resources

### ISSUE THREAD

**Issue by InfernoRP23** [project-error/npwd#1130]
Just trying out some different scripts for phones. 
problem is not being able to remove this file now. 
when we go to remove it, we get an error deleting and its stating the directories are not empty. 
which there's several folders within each other that are just repeating. 

error mentioned 
QBcoreframework/resources/scripts/npwd/node_modules/@commitlint/read/node_modules/.bin:
directory not empty. 

I got directly from your repository I have seen several versions leaked. but no need when its open source through here. 

anyway any info would be appreciated. ( Maybe Im just dumb and cant delete a file correctly :'p )

all the folders are empty but as stated they just are repeating to the last location ".bin"

**Comment by OldMateFitzy** [comment]
Did you find a fix for this?

**Comment by TonybynMp4** [comment]
Well, start by not downloading the source code unless you really need to,
And best guess is to try and delete folder by folder starting from the 'deepest',
Windows seems to struggle with the number of dependencies npwd has 😄
