### ISSUE TITLE
Bug: <short description>

### ISSUE THREAD

**Issue by NLGameBoy** [project-error/npwd#1144]
### Development Issue

Yes

### Phone Version

(3.13.1-beta.4)

### Issue Description

[      script:npwdnew] Error loading script dist/game/server/server.js in resource npwdnew: SyntaxError: Unexpected token } in JSON at position 3024
[      script:npwdnew] stack:
[      script:npwdnew] SyntaxError: Unexpected token } in JSON at position 3024
[      script:npwdnew]     at JSON.parse (<anonymous>)
[      script:npwdnew]     at getConfig (@npwdnew/dist/game/server/server.js:49810:24)
[      script:npwdnew]     at @npwdnew/dist/game/server/server.js:49816:19
[      script:npwdnew]     at @npwdnew/dist/game/server/server.js:49832:3
[    c-scripting-core] Failed to load script dist/game/server/server.js.

### Issue Reproduction

I get this error when I just want to start the script or something

**Comment by itschip** [comment]
Syntax error in config.
