### ISSUE TITLE
Enhancement: Add Public Facing Identifier API

### ISSUE THREAD

**Issue by TasoOneAsia** [project-error/npwd#192]
**Is your feature request related to a problem or design oversight? If so, please explain it.**
Yes, currently the identifier attribute for NPWD players is readonly and assigned on join. This excludes individuals who use a multicharacter system from easily changing a players identifier.

**What is your suggestion?**
Implement a public API through an export that allows for users to set the player identifier and any other relevant in-memory data used in the phone. These would be triggered whenever a framework loads a player, or unloads a player. 

**Any additional comments or concerns?**
Exact implementation details should be discussed.

**Comment by EvanDarwin** [comment]
i am waiting

**Comment by RockySouthpaw** [comment]
Just to reiterate, the way the phone is also means that anyone using the following will be unable to use the phone:
- license (without doing string sub. Would be `license:XXXXXXX`
- Steam
- Discord
- Xb1
- Live
- IP
- Any multichar that changes the column to `charY:XXXXXXXXXX`
- Hawaii’s ESX (without changing license sub string)
Idk if vRP would even work with the phone or some of the other frameworks ether.

**Comment by benzon** [comment]
The current handling is perfect, i do think a export would be better then a EventTrigger like now, but then again if it works it works.

**Comment by RockySouthpaw** [comment]
@TasoOneAsia Is this enhancement still valid as its been implemented?

**Comment by TasoOneAsia** [comment]
Implemented
