### ISSUE TITLE
Road to v1.0.0 Release - Where We Are Now

### ISSUE THREAD

**Issue by TasoOneAsia** [project-error/npwd#194]
**Since we actually are getting close to release, it is time to get a basic checklist of what we want done before v1.0.0, expect this to grow/shrink over the next week**

### Perf Testing
- [ ] At scale testing with a high number of concurrent players. 
- [ ] Profiler data for React Renders, Client Side, & Server Side

### Misc

- [ ] Complete and verified translation keys for offered locales
- [x] Test Linux compatibility and attain a repro for globbing issues, if one exists.

### Phone

- [ ] Complete dark theme
- [ ] Complete light theme

### Client Side

- [x] Enable keyboard controls for WASD while retaining mouse focus.

### Server Side
- [x] Public facing exports allowing for certain NPWD internal behavior to be altered by users.
- [ ] Enhanced logging to Sentry and files

**Comment by RockySouthpaw** [comment]
>  Test Linux compatibility and attain a repro for globbing issues, if one exists.

This should be fixed now so @jfrader needs to retest.
