### ISSUE TITLE
Bug: Phone's NUI Freezes and requires relog.

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#196]
**Describe the bug**
Essentially what occurs is the phone becomes unresponsive and remains stuck on on your screen, You can ensure the resource, do `phone` or even `phone:restart` and the UI isn't removed. A full relog is required to remove the phone from the screen.

**To Reproduce**
Still need a reproduction for this issue as I can not find a viable one. It occurred previously in dev but i haven't since been able to reproduce it until today where it occurred on 3 occasions to myself and also occurred with others who were testing the phone too. The only constant is related to tabbing out and tabbing back in. 

The issue has occurred on multiple apps so it isn't app restricted. I also reproduced it on a non esx server as well.

**Evidence**
If applicable, add a screenshot or a video to help explain your problem.
![image](https://user-images.githubusercontent.com/55056068/113381308-a336b080-934c-11eb-9430-fdb920ebf5ae.png)

Screenshot doesn't really help as there is no error logs. Though you can see in the console the resource was restarted and the issue still stayed.

**Needed information (please complete the following information):**
 - **Server OS**: `Windows 10`
- **Server Artifact version**: `3759`
- What version of **new-phone-who-dis** are you running? `9896f2384e18108c8d90ef4ae70d35141f7a5dd9`

**Additional context**
A valid reproduction still needs to be found. It's probably something we should fix before v1 is released.

**Comment by Ruqen** [comment]
I tried every way to reproduce this like closing and opening the phone with SPAMMING F1, smashing the keyboard and couldn't do it. I will try again when the reproduction is found.

**Comment by RockySouthpaw** [comment]
> I tried every way to reproduce this like closing and opening the phone with SPAMMING F1, smashing the keyboard and couldn't do it. I will try again when the reproduction is found.

The only constant factor seems to be alt tabbing. Idk if it’s relative to the duration you alt tab/where you click when you come back.

**Comment by OhTanoshi** [comment]
Why not just make a keypress such as esc close all nui for the phone. it is just a bandaid but would remove the having to relog and such.

**Comment by TasoOneAsia** [comment]
> Why not just make a keypress such as esc close all nui for the phone. it is just a bandaid but would remove the having to relog and such.

Huh? This is the current behavior of the phone. The freezing behavior as described here is a result of the NUI frame itself totally freezing, meaning any event listeners, such as the ones for keystrokes, fail to trigger.

**Comment by RockySouthpaw** [comment]
> Why not just make a keypress such as esc close all nui for the phone. it is just a bandaid but would remove the having to relog and such.

As Taso said, this is already the current behavior. Usually you can close the phone via a command to fix the issue or use the `phone:restart` command. This is just a special case.

**Comment by RockySouthpaw** [comment]
> Any other repros on this?

No reproduction methods for it but it only took maybe 10 minutes when I had 3 people in my server to trigger it.

**Comment by kywan** [comment]
Same hard to find whats wrong but it's happend, all game freeze and all keyboard and input (clic) are not detected (alt+f4 not working too)

Sometime it's happend by spamming F1 or esc but not sure it's about this

**Comment by itschip** [comment]
I'll keep digging into this.

**Comment by RockySouthpaw** [comment]
Pinned this issue sine it's one of the major concerns and has no reproduction.

**Comment by itschip** [comment]
Would be nice if someone could try to create a repro. Unsure if it's fixed after [fix(init): remove player/ui ready events](https://github.com/project-error/new-phone-who-dis/commit/f89ffc3060bb1529fb153fcb1e1b1cebce39b777)

**Comment by AvarianKnight** [comment]
@RockySouthpaw Is this valid anymore?

**Comment by RockySouthpaw** [comment]
> @RockySouthpaw Is this valid anymore?

You’re the one with a prod server, you tell me kek

**Comment by AvarianKnight** [comment]
> > @RockySouthpaw Is this valid anymore?
> 
> You’re the one with a prod server, you tell me kek

Haven't had this issue so far
