### ISSUE TITLE
Enhancement: Adjust messages SQL to remove unnecessary table.

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#208]
**Is your feature request related to a problem or design oversight? If so, please explain it.**
Design oversight. We currently have a table for message labels `npwd_messages_labels` (only used for group messages) while also having the same column within `npwd_messages_groups`

**What is your suggestion?**
Use the already existing column within `npwd_messages_groups` instead of creating another table to handle it. 

**Additional Information?**
Currently the `label` column is unused in this table. See below:

```sql
CREATE TABLE IF NOT EXISTS `npwd_messages_groups` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_identifier` varchar(48) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `group_id` varchar(512) NOT NULL,
  `participant_identifier` varchar(48) NOT NULL,
  `label` varchar(60) DEFAULT '',
  `unreadCount` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);
```
As you can see, `label` already exist in this column but as stated previously; it Isn’t used. The phone currently uses the table below for it:
```sql
CREATE TABLE IF NOT EXISTS `npwd_messages_labels` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_identifier` varchar(48) NOT NULL,
  `label` varchar(60) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `group_id` varchar(512) NOT NULL,
  PRIMARY KEY (`id`)
);
```

**Comment by itschip** [comment]
Hmmm
