### ISSUE TITLE
Bug: While using text fields, controls are enabled so movement occurs/menus open.

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#227]
**Describe the bug**
- If a server has any menu bound to any key that is typically used when writing a message (A-Z, commas, periods, ect) then that menu will pop up. 
- People will move slightly every time they type the letters `W,A,S,D` as we do not freeze them now. 

The only solution I have would be to disable all control actions if they're clicking on a text field or `SetNuiFocusKeepInput(false)` within text boxes. 

Issue was introduced in the following PR: https://github.com/project-error/new-phone-who-dis/pull/212

**Comment by benzon** [comment]
Agree since the current way of the char moving around is an issue, even hitting something like p will open the pause screen.

And i do think your method sounds like the optimal one to use.
