### ISSUE TITLE
Bug(Calling): Offline players/invalid numbers are currently not handled when calling

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#228]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description

When calling a player who is offline, the call fails and a server console error is shown.

### Issue Reproduction

- Open Dailer
- Call number who is offline

Receive error

### Evidence

![image](https://user-images.githubusercontent.com/55056068/146448817-57903506-58c7-4888-8462-eea4a07bb2cb.png)

![image](https://user-images.githubusercontent.com/55056068/146448843-19881828-5a29-4d64-8743-5d917a0ef3b5.png)

### Suggested work around

Simply send a different error to the UI when source isn't found that the player is currently outside of the service area.

Refactor the console print stating player is offline.

**Comment by itschip** [comment]
Does this happen if its a valid number but the player is offline?

**Comment by RockySouthpaw** [comment]
Yea last I checked, this issue existed with messages too but kidz added something to prevent that. Will re test tomorrow

**Comment by TasoOneAsia** [comment]
@itschip Issue you should be testing against on refactor of messages

**Comment by itschip** [comment]
Fixed in #323 , not sure about the status on messages

**Comment by RockySouthpaw** [comment]
Updated issue

**Comment by itschip** [comment]
Fixed in 4a8a2ffc0aa7349f0bce45755c8fd3c0c74e9c13

**Comment by RockySouthpaw** [comment]
Not 200% sure on the intended functionality now but i tested calling a player who wasn't on and the call went through with no errors. 

![image](https://user-images.githubusercontent.com/55056068/147204486-23019bd4-a7d0-4204-92ba-7e46518b66c7.png)

if intended please close.

**Comment by itschip** [comment]
Intended.
