### ISSUE TITLE
Bug: Twitter doesn't use the right notification volume

### ISSUE THREAD

**Issue by AvarianKnight** [project-error/npwd#233]
**Describe the bug**
Twitter notifications are done based on "notification volume" instead of "Twitter notification volume"

**To Reproduce**
1. Tweet and listen to it on another client
2. your ears bleed
3. suffer

**Expected behavior**
Twitter notification volume to be used for Twitter notifications

**Comment by RockySouthpaw** [comment]
For issue 2, can you confirm it occurs as such:

 - call animation is playing 
 - Phone is closed (call is still active)
 - Phone is opened but plays the phone to text animation 

I’m not entirely sure how I would fix this one unless I pass a call in progress var to the play animation event. I’ll look at that issue tomorrow ish.

**Comment by RockySouthpaw** [comment]
@TasoOneAsia can you clarify what is “uncomfirmed” here as there is 2 issues mentioned?

**Comment by RockySouthpaw** [comment]
@AvarianKnight Can you make another issue for the animations bug? Since there are multiple issues with animations it would make for better tracking.

**Comment by RockySouthpaw** [comment]
is this still a thing?

**Comment by RockySouthpaw** [comment]
Issue is resolved at this time.
