### ISSUE TITLE
Bug: Twitter account creation.

### ISSUE THREAD

**Issue by benzon** [project-error/npwd#235]
**Describe the bug**
Fresh install, latest "version" - When trying to create a twitter profile, it fails and drops a error in server console
![1621566667942d9d20d8db764120a2f0400fb59757](https://user-images.githubusercontent.com/3528000/119076732-635a8400-b9f3-11eb-91a0-8d7ddb4bbc24.jpg)

**To Reproduce**
Use latest version, with multichar enabled, create account and error is droped in console

**Comment by itschip** [comment]
Is some of your player data undefined?

**Comment by benzon** [comment]
Everything should be filled out.

TriggerEvent('npwd:newPlayer', {source = playerId, identifier = identifier, firstname = firstname, lastname = lastname})

And all the date should be forwarded correct.

**Comment by itschip** [comment]
Might be the DB table column.

**Comment by itschip** [comment]
Any updates?

**Comment by benzon** [comment]
Waiting for you to look up the issue you had with DB

**Comment by TasoOneAsia** [comment]
Stale issue, shouldn't be an issue but if it is please make another issue
