### ISSUE TITLE
Enhancement: Billing

### ISSUE THREAD

**Issue by benzon** [project-error/npwd#238]
Insted of having that pesky esx_billing menu that feels odd and malplaced.

An integrated solution to pay bill's would be a nice thing, maybe as a part of the bank app, where you got a overview of your bills and with a click on a button makes the payment.

**Comment by RockySouthpaw** [comment]
Maybe an export or event could be made that people can use to send bills with their menu. Would allow it to be made with minimal framework dependencies.

**Comment by benzon** [comment]
Could be done quite easy, just send over the mysql or cached result of bills - and trigger the pay bill event, so it's basicly just a UI portion.

**Comment by frazz1234** [comment]
A bank App send money to people

**Comment by itschip** [comment]
> A bank App send money to people

Under development

**Comment by RockySouthpaw** [comment]
WIP. Closing as a result.
