### ISSUE TITLE
Enhancement: Resize notifications so they don’t cover the top row of apps

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#246]
**Is your feature request related to a problem or design oversight? If so, please explain it.**
Yes, notifications overlap apps.

**What is your suggestion?**
Resize them so they don’t overlap.

**Any additional comments or concerns?**

![](https://media.discordapp.net/attachments/811371031104847883/846116874307502120/image0.png)

Pretty much sums it up.

**Comment by itschip** [comment]
Could we also simplify notifications where we don't care what app is triggering it? Or is showing the app *icon* desired? 

Trying to gather whatever information before re-writing the Notification API.

**Comment by itschip** [comment]
Fixed in 94d14add517d7748e0b1cb8843e419797e719258
