### ISSUE TITLE
Twitter fails to initalize if two players have the same name

### ISSUE THREAD

**Issue by AvarianKnight** [project-error/npwd#248]
**Describe the bug**
If another player has the same name as you Twitter will fail to initialize for that player
`[NPWD] [twitter] [error]: Failed to get or create a profile, Duplicate entry 'Mike_Hunt' for key 'profile_name_UNIQUE'`

**To Reproduce**
1. Have the same name as an already existing Twitter user
2. Try to load the player
3. Fail to create a profile

**Expected behavior**
Twitter to properly initialize when they have the same phone number.

**Needed information:**
 - **Server OS**: [e.g. Windows 10] Ubuntu 16.04
- **Server Artifact version**: [e.g. 3486] 3922
- What version of **new-phone-who-dis** are you running?: HMMM

**Comment by TasoOneAsia** [comment]
@jfrader Keep in mind for twitter refactor
