### ISSUE TITLE
BUG: Animations Reset

### ISSUE THREAD

**Issue by AvarianKnight** [project-error/npwd#249]
**Describe the bug**
Animations reset when doing any action

**To Reproduce**
1. Start a phone call
2. Close the phone
3. Animation goes away with the phone

**Expected behavior**
Animations to continue to play when in a phone call

**Comment by RockySouthpaw** [comment]
It use to function like this but the issue was the fact the phone should of closed and rendered partially if you’re in a call. I don’t recall if that feature ever came but this was the plan when that change was made.

**Comment by RockySouthpaw** [comment]
Another thing to note as well is that all the animations need a check for the last played animation added to them. Currently they’re not checked so there may be a bit of scuff here and there.

Theres also the issue too where the phone animations will end if you walk through Doors.
