### ISSUE TITLE
Bug: Tweets are sometimes initalized as null

### ISSUE THREAD

**Issue by AvarianKnight** [project-error/npwd#251]
**Describe the bug**
Tweets are sometimes null, which crash the entire phone

**To Reproduce**
** This isn't reliable at all **
1. First load in go to tweets
2. Tweets are null
3. Phone crashes

**Expected behavior**
Tweets to not be null on first initialization 

**Needed information (please complete the following information):**
 - **Server OS**: Ubuntu 20.04
- **Server Artifact version**: [e.g. 3486] 4000
- What version of **new-phone-who-dis** are you running? N/A

**Comment by RockySouthpaw** [comment]
How many tweets do you have when this happens? Is that related at all or could it happen if there are like 10?

**Comment by AvarianKnight** [comment]
> How many tweets do you have when this happens? Is that related at all or could it happen if there are like 10?

There's always 75 tweets loaded

**Comment by AvarianKnight** [comment]
Just to update this, this primarily happens due to the unoptimized query that runs every time someone opens the Twitter app. A fix for this would be to only fetch the query on the initial server start-up and rotate recent queries in an array and to optimize the queries

**Comment by TasoOneAsia** [comment]
This can be much better approached by moving towards a client passive based system which does initial twitter client fetch when mounted, to fill recent backlog. Then will receive updates that can be used to continually update local cache.
