### ISSUE TITLE
Bug: Shift Clicking the link tags changes the NUI root.

### ISSUE THREAD

**Issue by AleksanderEvensen** [project-error/npwd#255]
**Describe the bug**
When you shift clicked a button in the UI everything disappears. After checking out the web code I saw that you guys were using links to navigate with react router and therefor used links to open apps in the main menu. Normally in the web browser, when you shift click a link, it would open that page in a new window, but since the FiveM NUI doesn't handle multiple windows, it will just navigate and change the root html to the page you clicked on. 

**To Reproduce**
First problem:
1. Open Phone
2. Start running
3. Click on any of the apps on the home screen.

**Expected behavior**
The phone opens the app or does the action the button(link) should've done.

**Evidence**
Video:
https://user-images.githubusercontent.com/19311856/120891442-fe18ac80-c608-11eb-8a29-9ecebcec5735.mp4

NUI devtools Sources Tab:
![image](https://user-images.githubusercontent.com/19311856/120891453-0cff5f00-c609-11eb-8ea4-c1202d433f85.png)

NUI devtools Elements Tab:
![image](https://user-images.githubusercontent.com/19311856/120891461-15579a00-c609-11eb-9899-68c08afb1422.png)

**Needed information (please complete the following information):**
 - **Server OS**: Windows Server 2019 and Windows 10
- **Server Artifact version**: 4007
- the newest version on the master branch after @itschip merged [this pr](https://github.com/project-error/npwd/pull/245) yesterday.

**Comment by AleksanderEvensen** [comment]
Sorry if the video didn't show so much of the phone. Had to trim it down for GH

**Comment by AleksanderEvensen** [comment]
https://user-images.githubusercontent.com/19311856/120891619-d83fd780-c609-11eb-8115-cd40db3123a4.mp4

**Comment by RockySouthpaw** [comment]
We were aware of this issue as @AvarianKnight reported it in the discord but never opened an issue about it.

Thank you for making such a detailed issue :). I think there’s a PR that was made to address this temporarily but I’m not sure.

**Comment by lukealford** [comment]
Also so you are aware, it's not just isolated to npwd. 

It's actually a CEF issue that has a PR waiting to be reviewed, all resources are affected by this.

https://github.com/citizenfx/fivem/pull/732

**Comment by TasoOneAsia** [comment]
Fixed with https://github.com/citizenfx/fivem/commit/34104fd5fc2d69caa6834d19f180498ce576888e
