### ISSUE TITLE
Bug: Bug GetLocationFromUrlValue

### ISSUE THREAD

**Issue by Nekzerd** [project-error/npwd#271]
![image](https://user-images.githubusercontent.com/79750023/124953327-5599a600-e015-11eb-98ef-e817b7947a1c.png)

**Comment by TasoOneAsia** [comment]
@Nekzerd Is this still an issue, I haven't encountered this issue on any of the recent development builds

**Comment by itschip** [comment]
This only happens on 'master'.

**Comment by YisusOnDev** [comment]
just need to change a "String" for string. On other builds there is no problem but in master yes it does

**Comment by itschip** [comment]
Fixed in some commit I couldn't find 👀
