### ISSUE TITLE
Bug: Match Making has no Input Validation on client

### ISSUE THREAD

**Issue by AvarianKnight** [project-error/npwd#272]
**Describe the bug**
Players are able to input any value into matchmaking input fields and send it to the server

**To Reproduce**
1. Setup your profile
2. Add some stupid long job name
3. Errors in MySQL instead of client

**Expected behavior**
Client to get a error and not send to server

**Evidence**
![error](https://i.dillonskaggs.dev/jTPUe7YZ)

**Comment by RockySouthpaw** [comment]
Can you check if this is the same with Twitter? I don’t think it’s like this with contacts anymore

**Comment by AvarianKnight** [comment]
> Can you check if this is the same with Twitter? I don’t think it’s like this with contacts anymore

No settings have length validation

**Comment by itschip** [comment]
Ill fix this in the refactor.

**Comment by itschip** [comment]
Oh, I forgot this issue.

**Comment by itschip** [comment]
Should be fixed on 'develop'. #293
