### ISSUE TITLE
Phone fails to fetch html

### ISSUE THREAD

**Issue by Tiimon** [project-error/npwd#280]
**Is this issue related to the phone still being in development?**
If so, please consult the [gitkraken](https://app.gitkraken.com/glo/board/X9YZ_x_SVQEcMwpH) to see if it's already being tracked. 
Unsure if this is related to this bug https://app.gitkraken.com/glo/view/card/fc3b54291da048b2a52799c2cc04fc0a

**Describe the bug**
Every single app throws this error in the client console (this phone is when opening the contacts app) Uncaught (in promise) TypeError: Failed to fetch (2new-phone-who-dis/resources/html/index.html#/phone/contacts:0)

**To Reproduce**
Download NPWD
Follow the docs on install guide
Load in the server and open the phone
Click on any app and the error will throw

**Expected behavior**
Apps should be working
Current Apps Not Working:
- Twitter
- Contacts
- Calling
- Texting
- Notes
- Ads

**Evidence**
![unknown](https://user-images.githubusercontent.com/32118783/125669429-9e517320-8724-4ff2-8a37-5fee608ee041.png)

**Needed information (please complete the following information):**
- **Server OS**: [e.g. Windows 10]
- Windows Server 2019
- **Server Artifact version**: [e.g. 3486] Don't know? Do `version` into your server console.
- 4201
- What version of **new-phone-who-dis** are you running?
- V0.1.3 (also tried V0.1.2 and develop branch)

**Additional context**
- NodeJS Version 14.17.3
- npm Version 6.14.13

**Comment by TasoOneAsia** [comment]
This is fixed on latest development builds
