### ISSUE TITLE
Bug: Bad argument format

### ISSUE THREAD

**Issue by Edrow-6** [project-error/npwd#281]
**Is this issue related to the phone still being in development?**
If so, please consult the [gitkraken](https://app.gitkraken.com/glo/board/X9YZ_x_SVQEcMwpH) to see if it's already being tracked. 

**Describe the bug**
Compilation error due to bad argument format

**To Reproduce**
1. Run 'yarn build' on linux
2. See error

**Expected behavior**
A successful compilation

**Evidence**
/server-data/resources/npwd/phone/src/common/utils/getLocationFromUrl.ts(4,41):
Argument of type 'String' is not assignable to parameter of type 'string'.
  'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.  TS2345

    2 | 
    3 | export const getLocationFromUrl = (url: String) => {
  > 4 |   const { pathname, search } = parseUrl(url);
      |                                                                  ^
    5 |   const searchStr = '?' + (search || '');
    6 |   return { pathname, search: searchStr };
    7 | };

**Needed information (please complete the following information):**
 - **Server OS**: Debian 10
- **Server Artifact version**: 4126
- What version of **new-phone-who-dis** are you running? LASTEST

**Additional context**
To correct this problem you need to replace: `String` by `string` at line 3 of `getLocationFromUrl.ts` file and run `yarn build.`

**Comment by itschip** [comment]
Which release is this? `0.1.3` or `0.1.4`? This is fixed in the latter.

**Comment by Edrow-6** [comment]
I cloned the master version a few hours ago, so I think 0.1.4

**Comment by itschip** [comment]
Try the `develop` branch

**Comment by Edrow-6** [comment]
No but it's ok, it works with the patch I said

**Comment by Edrow-6** [comment]
No but it's ok, it works with the patch I said

**Comment by itschip** [comment]
> No but it's ok, it works with the patch I said

Yes, it's already been fixed on `develop`
