### ISSUE TITLE
Bug: Phone freezes when players text each other

### ISSUE THREAD

**Issue by Tiimon** [project-error/npwd#294]
**Is this issue related to the phone still being in development?**
If so, please consult the [gitkraken](https://app.gitkraken.com/glo/board/X9YZ_x_SVQEcMwpH) to see if it's already being tracked. 

**Describe the bug**
When a player texts another player regardless if they're in their contacts or not the phone will freeze for both the sender and receiver when they go to open the message

**To Reproduce**
1. Player1 sends a text message to Player2
2. Player2 opens messaging and tries to press the unread message
3. Player2's phone bricks (ui is left on the screen but player can still do the phone animation with F1)
4. Shortly after Player1's phone also bricks

**Expected behavior**
Texting players should not brick phone

**Evidence**
Here is the output of devtools when the phone freezes
![e9ac275e8a40310cfa1ff647bb1df105](https://user-images.githubusercontent.com/32118783/127502154-01bdb3f5-a316-4da9-9f06-f9208e13c859.png)

Here is a video of the issue occurring
https://user-images.githubusercontent.com/32118783/127502293-5b87773c-f3c9-40bc-80c5-952708ba0dea.mp4

**Needed information (please complete the following information):**
 - **Server OS**: [e.g. Windows 10]
 - Windows Server 2019
- **Server Artifact version**: [e.g. 3486] Don't know? Do `version` into your server console.
- 4260
- What version of **new-phone-who-dis** are you running?
- Develop branch

**Comment by TasoOneAsia** [comment]
@itschip Should be tested against in the messages refactor

**Comment by itschip** [comment]
Haven't experienced this while refactoring, so hopefully, this has been resolved. 

I'll see if I can reproduce it on 'develop' or 'master'.

**Comment by AvarianKnight** [comment]
Sounds like the old UI freeze from the useEffect
