### ISSUE TITLE
Enhancement: Job Listing App

### ISSUE THREAD

**Issue by ModernAesthetics** [project-error/npwd#306]
Listing of available "non-whitelisted" jobs from a Job Listing App would be great. Would be great to no longer have to have some random location or "Job Center" to go to to join a job when you could on the fly join a job from your phone. A long with joining a job obviously the ability to change or leave job should be in this as well. As far as a config should go make it easy to simply add the job name from job table(ex. taxi, fishing, garbage, burgershot, etc...)

**Comment by renatokeys** [comment]
im working on this.

**Comment by frazz1234** [comment]
Very good idea

**Comment by RockySouthpaw** [comment]
This was denied due to the highly likely need for framework dependency. Not current within our scope for the phone but if someone wants to make it @renatokeys we’d be open to adding it.
