### ISSUE TITLE
Bug: Tooltips get stuck on phone close

### ISSUE THREAD

**Issue by AvarianKnight** [project-error/npwd#326]
**Describe the bug**
If you are hovering over an App Icon when you put the phone away the Tooltip will get stuck on the screen

![image](https://user-images.githubusercontent.com/13681939/136645228-c676def4-a657-40c4-8c3a-fd050a1b9726.png)

![image](https://user-images.githubusercontent.com/13681939/136645233-366581b3-feec-4368-9cd6-45f55bedd962.png)

**Comment by RockySouthpaw** [comment]
Added to kraken: <https://app.gitkraken.com/glo/card/93315980d99c4523b919936c753eadd1>
