### ISSUE TITLE
Bug: Eager NUI Requests are Invalid on Mount

### ISSUE THREAD

**Issue by TasoOneAsia** [project-error/npwd#330]
### Developement Issue

No

### Issue Description

Fetching on the client side when using an async selector immediately occurs whenever a component is mounted that requires the scoped data. This creates a problem of eager fetching, as certain apps may immediately trigger a server side fetch upon NUI load before the player has been added to the server maps.

To fix this, we must prevent requests from going out until we can confirm that the player source has been processed and exists within the server side player maps. At this point, it is considered safe to initialize server requests.

### Issue Reproduction

N/A

**Comment by RockySouthpaw** [comment]
Tracked here: https://app.gitkraken.com/glo/card/de59f3fd72894673bc953d3eb662f4f9

**Comment by TasoOneAsia** [comment]
Closed with #334
