### ISSUE TITLE
Bug: My M1 refuses to work

### ISSUE THREAD

**Issue by TasoOneAsia** [project-error/npwd#342]
### Developement Issue

No

### Issue Description

This issue is a place where I can release my anger regarding docker platform architecture edge cases for `FXServer`, specifically for the latest Apple Silicon chips. It appears that mono isn't playing nice with ARM64 most likely (but why???????), anyways thanks for attending my Ted talk.

I don't expect CFX to bring M1 support but it would be nice to figure out a way to virtualize on `darwin-arm64`, so I can actually work on FiveM related things when I am away from my Windows machine.

### Issue Reproduction

1. get m1
2. spend 8 hours of ur life trying to containerize FXServer + Alpine in docker
3. fail
4. repeat

### Evidence

This is gonna be closed immediately anyways

**Comment by itschip** [comment]
WHERE IS MY LINEAR.APP ISSUE!!!!!!!

**Comment by RockySouthpaw** [comment]
Cant reproduce, closed.

**Comment by thelindat** [comment]
hello my npwd not launch am using esx 1.1
