### ISSUE TITLE
Bug: Call notification isn't removed on rejection

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#364]
### Developement Issue

No

### Issue Description

After rejecting a call, the person who rejected the call still has their notification for the call despite it having ended for both players and being removed from the map.

### Issue Reproduction

1. Player 1 calls Player 2
2. Player 2 rejects call

Call is ended for both players. Player 1 (person who called) doesn't have the notification alert while player 2 (the receiver) does.

### Evidence

![image](https://user-images.githubusercontent.com/55056068/142798927-a9d9b1ed-60e9-4d16-88f1-f5a34c1022d9.png)
![image](https://user-images.githubusercontent.com/55056068/142798944-ad129a11-61aa-4192-a324-890e7827014b.png)

**Comment by TasoOneAsia** [comment]
Should be fixed in #374
