### ISSUE TITLE
Bug(Messages): duplicate conversations

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#367]
### Developement Issue

Unsure

### version

Develop

### Issue Description

Multiple conversations can be created with the same number, though its just a UI bug and not a sql issue.

### Issue Reproduction

1. Player 1 creates a group with player 2
2. Repeat step 1

Both players get the groups created multiple times.

### Evidence

Follow this [link](https://discord.com/channels/791854454760013827/791854455468458042/912593709063868436) to some spooky channel in the discord 👀

**Comment by itschip** [comment]
Fixed in ae9676a
