### ISSUE TITLE
Bug(Twitter): Overlapping search icon

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#369]
### Developement Issue

Yes

### Phone Version

develop + refactor/twitter

### Issue Description

Within the twitter app, the search icon overlaps the profile icon when search is selected.

### Issue Reproduction

1. Open Twitter
2. Click the magnifying glass icon (search tab)

The magnifying glass overlaps the contact head icon (user info). This results in the unintentonal behavior of routing to the user info tab on the click of this icon.

### Evidence

![image](https://user-images.githubusercontent.com/55056068/142984800-d86bc8a2-32ee-4332-a3aa-c7884b3faa43.png)

**Comment by itschip** [comment]
Fixed in #338
