### ISSUE TITLE
Enhancement(Messages): Improve conversation deletion

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#370]
### Application

Messages

### Dependency

No

### Feature Description

Add the ability to select multiple conversations to delete on the root of the messages app. Currently if you want to delete more than 1 conversation, say someone spammed you with multiple users, you'd need to open every conversation + press the actions icon + delete. This is super slow and a pain for users with a lot of conversations.

Could also need a way to delete all conversations as well but not required.

**Comment by itschip** [comment]
Fixed in 8b46a519f30733b771ac340da49d5c3bfcd9494c
