### ISSUE TITLE
Bug(Calling/Contacts): No data type validation on contact number field

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#376]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description

Missing validation for number field. This currently allows you to use letters for the number field where numbers are expected.

**Calling issue portion**
As a result of the above, you can call someone with letters for number. This results in the call actually going through (wild) and the player being stuck in the call since the call isn't in current maps.

### Issue Reproduction

1. Open contacts and click the create contact icon
2. Type letters into the number field.

**Part 2**
1. Route back to contacts
2. Call the 'number' you entered.
 
 You'll be stuck in the call as it will succeed.

### Evidence

![image](https://user-images.githubusercontent.com/55056068/143179799-d07a76fa-1f62-4240-8550-55f5d0dbc90c.png)

**Comment by TasoOneAsia** [comment]
@RockySouthpaw We can't lock this the input to a specific format as we can't assume the format of any valid number. For example, some servers use 'police' as a phone number for emergency services. NPWD should handle number format as agnostically as possible.

**Comment by RockySouthpaw** [comment]
> @RockySouthpaw We can't lock this the input to a specific format as we can't assume the format of any valid number. For example, some servers use 'police' as a phone number for emergency services. NPWD should handle number format as agnostically as possible.

No servers will use police as phone number because that is the functionality of gcphone add ons. Why can’t servers just set a phone number for their jobs then??? Seems asinine imo to confirm to an idiotic thing like text for phone numbers.

**Comment by TasoOneAsia** [comment]
> Why can’t servers just set a phone number for their jobs then??? Seems asinine imo to conform to an idiotic thing like text for phone numbers. Name one place in the world that makes you dial “police” to reach the police department smh.

I can easily add something for locking to a specific format and then we can control for that everywhere. But, at the moment, NPWD takes no assumption about the phone number for greatest compatibility. If we feel like this is a meh idea and we should make some assumptions about phone number, I am open to suggestions.

**Comment by RockySouthpaw** [comment]
> > Why can’t servers just set a phone number for their jobs then??? Seems asinine imo to conform to an idiotic thing like text for phone numbers. Name one place in the world that makes you dial “police” to reach the police department smh.
> 
> I can easily add something for locking to a specific format and then we can control for that everywhere. But, at the moment, NPWD takes no assumption about the phone number for greatest compatibility. If we feel like this is a meh idea and we should make some assumptions about phone number, I am open to suggestions.

It’s just weird because currently there is no resources, outside of gcphone, that has job numbers as their job name. As far as I have seen anyways. So I don’t think this would even be possible.

Furthermore, phone is written in such a way that we get players by phone numbers for various things. So we actually would be breaking parts of the phone by allowing it to be a job name without actually writing in something to handle it. Which we can’t do without adding framework dependency.
