### ISSUE TITLE
Bug(Contacts): Missing data length validation for avatar URL

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#377]
### Developement Issue

Yes

### Phone Version

Develope

### Issue Description

Due to a lack of data length restriction, a user can paste a long link into the avatar URL field which will result in an error message stating "Failed to create contact" (Should say why imo) and add a server error log 
![image](https://user-images.githubusercontent.com/55056068/143180552-54a2b0c3-44f5-4976-9e40-284177d3d287.png)

This should be addressed within the UI so users can get proper feedback and also since it can be abused as I can just spam this by generating a long link and attempting to create a contact which results in multiple server prints.

### Issue Reproduction

1. Open contacts and click the create contact icon
2.  Paste a long link into the avatar URL (Can generate one here http://www.reallylong.link/)
3. Press add contact
4. Press many times for added fun.

**Comment by itschip** [comment]
This is not an issue. If you're have such a long link, then you can rather upload it to imgur or a similar service. Closing this for now.
