### ISSUE TITLE
Bug(Notes): Notification issues

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#378]
### Developement Issue

Yes

### Phone Version

Develope

### Issue Description

- [x] Save notification overlaps with create note icon.
- [x] Save Notification persist upon clicking the new note icon.

### Issue Reproduction
1. Create note
2. Attempt to create a second note

Notification blocks you from doing so and may get stuck unless you click on the background.

Should probably do some sort of scalar fetch to prevent duplicate notes from being created tbh.

### Evidence

![image](https://user-images.githubusercontent.com/55056068/143182033-d05ae7d2-4db5-4467-8ed7-d073000fadbd.png)

**Comment by itschip** [comment]
I also reduced the duration of the notification to 2sec. See ae9676a

But we might just use the new notification api Taso is working on for this, instead of two different. Thoughts?

**Comment by RockySouthpaw** [comment]
> I also reduced the duration of the notification to 2sec. See [ae9676a](https://github.com/project-error/npwd/commit/ae9676ab3927c7fe15a778da2b5aa6603c2fac9f)
> 
> But we might just use the new notification api Taso is working on for this, instead of two different. Thoughts?

Yea I’m all for using one notification system across the board. I assumed it was going to replace this one anyways but I documented it for the purpose of documentation.

**Comment by TasoOneAsia** [comment]
> But we might just use the new notification api Taso is working on for this, instead of two different. Thoughts?

I don't think we should use my new notification system with these types of interaction feedbacks. Those notifications aren't used for success/failure indicators. Rather, they are used for the traditional notifications one would receive while using a phone.

**Comment by RockySouthpaw** [comment]
> > But we might just use the new notification api Taso is working on for this, instead of two different. Thoughts?
> 
> I don't think we should use my new notification system with these types of interaction feedbacks. Those notifications aren't used for success/failure indicators. Rather, they are used for the traditional notifications one would receive while using a phone.

Well whatever we use, it needs to work properly cause whatever we currently use for alerts sucks dick and needs a rewrite. I’m tired of writing issues about them on every single app.

**Comment by TasoOneAsia** [comment]
> Well whatever we use, it needs to work properly cause whatever we currently use for alerts sucks dick and needs a rewrite. I’m tired of writing issues about them on every single app.

Agreed, lets make sure they are clearable by the user using a close action.

**Comment by RockySouthpaw** [comment]
@itschip this isn't resolved as i tested it on dev earlier
unless my build didnt go correctly

**Comment by itschip** [comment]
@RockySouthpaw 😨 And it was merged 🐛

**Comment by itschip** [comment]
Well, do a new test in develop and see. I test it as well today, and confirm

**Comment by RockySouthpaw** [comment]
Confirmed resolved, was a me issue.
