### ISSUE TITLE
Enhancement(Calculator): Improve readability

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#379]
### Application

Calculator

### Dependency

No

### Feature Description

- [ ]  Large numbers are displayed poorly so this should be improved upon. Cases of numbers being overlapped by icons and long numbers being cut off with a `,...` 
https://i.imgur.com/xlS6SIo.png
https://i.imgur.com/MzYuw2L.png

**Example**
11,111,111,111,111 + 1 will result in it displaying `11,111,111,...` which is more or less impossible to use. While this is a niche case and i don't forsee anyone doing calculations in the 10's of billions, a data

- [ ]  Populate comma when doing calculations to improve readability as we currently only do so on results. Extremely poor readability on larger calculations. With lots of server having non realistic based economy, this is needed imo.
https://i.imgur.com/tQDN1dI.png

### References
IOS populates the comma on calculations. It actually restricts you to only being able to do calculations that are initially no greater than hundreds of millions. It also reduces font size so more numbers can fit as well though we don't need to do that as we can fit up to billions.

**Comment by antonstjernquist** [comment]
Seems like an interesting issue. Will look into this :)

**Comment by antonstjernquist** [comment]
https://github.com/project-error/npwd/pull/630
