### ISSUE TITLE
Bug(Marketplace): Multiple

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#380]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description as of https://github.com/project-error/npwd/commit/a061ff5cd457e530f198439786c8c41fb218abf5

- [x] Unable to report offline player listings. ** (Need a solid repro as its not everytime)**
![image](https://user-images.githubusercontent.com/55056068/144732562-bbbde708-3d15-44fa-9b3d-469237f2bf91.png)
1. Player 2 post a listing
2. Player 2 quits or changes character (so long as the npwd unload event triggers.)
3. Player 1 reports listing.

- [x] #405

### MInor Suggestions

- [x] Make the primary key `listing id` to prevent duplicate reportsin the event should some error occur with the UI. We don't really need the id column as nothing is being shown based off reports iirc so its more or less unused.

- [x] Re-adjust border for listing as its a bit dim on the black background + light theme as well. Padding is pog though.

- [x] Maybe just set a bool within the sql to true so we dont need another table just for reports as its only 3 columns.

### Issue Reproduction

Please tag me if you need reproduction steps for any of the above.

### Evidence

Please tag me if you need evidence for any of the above.

**Comment by itschip** [comment]
@RockySouthpaw How do you want to validate duplicates the if one of the columns matches, or all of them?

**Comment by RockySouthpaw** [comment]
> @RockySouthpaw How do you want to validate duplicates? If one of the columns matches, or all of them?

What do you think is best? I think duplicate title would be enough because people can re upload their listing if they need to for whatever reason. 

@AvarianKnight thoughts?

**Comment by RockySouthpaw** [comment]
@itschip Appears you can't report an offline players listings

**Comment by RockySouthpaw** [comment]
Choosing a picture also removes the title you entered before. Not sure if oversight, bug, or intended since i assume we reload it.

**Comment by RockySouthpaw** [comment]
Listings are removed on player drop, however, idk when sellout refreshes as the listings persist until the phone is restarted.

**Comment by RockySouthpaw** [comment]
I would also suggest changing the color of the app if we are using red for error handling. This is overly confusing as to whats goofed when a field is highlighted red + your selected field is also red. See below:
![image](https://user-images.githubusercontent.com/55056068/143730346-9234a68d-840f-4469-b58e-1b76d8b25cb0.png)

**Comment by itschip** [comment]
> Listings are removed on player drop, however, idk when sellout refreshes as the listings persist until the phone is restarted.

Let's get some RP people to answer if they still would like to see other peoples posts after they leave, in order to message them.

**Comment by itschip** [comment]
@RockySouthpaw Please test 'No validation for duplicate listings' and check the border

**Comment by RockySouthpaw** [comment]
@itschip issue updated to reflect current fixes

**Comment by RockySouthpaw** [comment]
@itschip added issue regarding the listing not refreshing following posting a new listing

**Comment by RockySouthpaw** [comment]
@itschip Tested all resolved issues and updated the issue label. Good work chip ❤️

**Comment by itschip** [comment]
> Make the primary key listing id to prevent duplicate reportsin the event should some error occur with the UI. We don't really need the id column as nothing is being shown based off reports iirc so its more or less unused.

I think we need to restructure the whole report flow, as we are now deleting listings on player drops, so we need to store the whole listing in the table, if it were to be useful.

**Comment by itschip** [comment]
> Unable to report offline player listings

This itself is not an issue, because we have already deleted their listing. We however need to broadcast this change to all clients.

**Comment by itschip** [comment]
@RockySouthpaw Please look over the issues listed. They should be resolved.

**Comment by RockySouthpaw** [comment]
All issues resolved
