### ISSUE TITLE
Enhancement: Event for hiding ui components on picture taken

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#384]
### Application

Camera

### Dependency

No

### Feature Description

Essentially a net event that is triggered when hud components should be hid. Like the `ClearHelp(bool);` function we have where the ui components are cleared before the "picture" is taken.

Would resolve issues such as peoples huds/maps being on pictures and would be super simple to add docs for. 

![image](https://i.imgur.com/xOPRajR.jpg)

Would end up being something like 2 events. One for show and one for hide or we can just use a bool instead of 2 events.

Below is a lua example for how server owners could utilize it:
```lua
-- 2 Events
AddEventHandler('npwd:hideHudComponents', function ()
    DisplayRadar(false) -- Hides map
    -- Add hud here
end)

AddEventHandler('npwd:showHudComponents', function ()
    DisplayRadar(true) -- Shows map
     -- Add hud here
end)

-- 1 Event but use a bool for showing components
AddEventHandler('npwd:showHudComponents', function (visible)
    if visible then
        DisplayRadar(true) -- Show map
        -- show hud
    else
        DisplayRadar(false) -- hide map
        -- hide hud
    end
end)
```
This would be the best solution imo as server owners can fix their own problems without rebuilding phone.

**Comment by TasoOneAsia** [comment]
What exactly do you think should be hidden? The radar for sure, but should we hide all the other default HUD elements as well?

**Comment by RockySouthpaw** [comment]
> What exactly do you think should be hidden? The radar for sure, but should we hide all the other default HUD elements as well?

Really depends on the server tbh. 

On NPWD side we can hide map, money, wanted level and probably the weapon stuff. But server owners have their own hud implementations that would also need to be hidden too + whatever they have while a player is inside a vehicle.

This is why the suggestion for an event to fire was made so server owners can handle it on their own in whatever language using an eventhandler and would keep people from having to touch the phone code as I don’t think we can make a true blanket solution without requiring server owners to modify source.
