### ISSUE TITLE
Bug(Matchmaker): Icons overlap navbar

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#407]
### Developement Issue

No

### Phone Version

Develop

### Issue Description

The icons to swipe left and right overlap navigation making navigation difficult.

### Issue Reproduction

1. Player 1 updates profile
2. restart phone
3. open matchmaker so the matches fetch again

Issue will appear

### Evidence

![image](https://user-images.githubusercontent.com/55056068/144733607-dd31d486-c736-4b98-b3c6-1b465eda01d2.png)

**Comment by RockySouthpaw** [comment]
Nav bar is currently hidden so technically still occurs? New issue was created with the attempted fix.

![image](https://user-images.githubusercontent.com/55056068/145701481-4fbc9ca1-06d7-45f8-8d41-adb753164313.png)

**Comment by itschip** [comment]
@RockySouthpaw , should be fixed in 5f7ae56569e1aa5236fe5952134b7b4e16897d2b

**Comment by RockySouthpaw** [comment]
Resolved
