### ISSUE TITLE
Bug(Calling): Target player not removed from call maps if call is ended early

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#416]
### Developement Issue

Yes

### Phone Version

develop

### Issue Description

If a call is started and ended before the target has chance to respond, the target player is unable to end the call.

`[         script:npwd] [NPWD] [calls] [error]: Error occured in accept call event (860-186-5489), Error:  Cannot set properties of undefined (setting 'is_accepted')`
`[         script:npwd] [NPWD] [calls] [error]: Call with transmitter number 860-186-5489 does not exist in current calls map!`

### Issue Reproduction

- Player 1 calls Player 2
- Player 2 doesn’t respond in any manner
- Player 1 ends call
- Player 2 will still have the call on their phone and they are unable to properly accept or deny it since it’s no longer in the call maps. They will still be in a call according to the notification on the header.

**Comment by itschip** [comment]
@RockySouthpaw Should be fixed in 3075af694a9b51cba334987ef11b4171830bf5aa

**Comment by RockySouthpaw** [comment]
Actually causes a crash. I had the phone rendered on the bottom right as the phone wasn't opened and ended the call on the second client. First client had a fatal error.

![Uploading image.png…]()

**Comment by itschip** [comment]
This is partially fixed in 'develop'. Another issue was that the notification alert wouldn't go away, so I just set 'keepWhenPhoneClosed' to false for now, until we fix it. See 4e6f455c1a3ca6f981a3fa69033efe5b11775520 and 573c8d758f0c074d0ab1a0d4bb830e7f83af9605

**Comment by RockySouthpaw** [comment]
Resolved
