### ISSUE TITLE
Bug(Messages): Target player doesn't receive group without a restart

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#417]
### Developement Issue

Yes

### Phone Version

Develope

### Issue Description

Target player doesn't receive the new message/group creation unless the resource is restarted. 

Messaging works fine so long as the group is populated first.

### Issue Reproduction

1. Have a clean install. 
2. Message player 2

Player 2 will not receive the message/group creation.

3. Restart npwd

Messages will be populated properly and player 2 will now receive any messages sent and vice versa.

**Comment by itschip** [comment]
@RockySouthpaw Should be fixed in 515526065a6622a6a6eb4906aa127442f13704e0

**Comment by RockySouthpaw** [comment]
Resolved
