### ISSUE TITLE
Bug(Twitter): Routing back to profile shows the previous profile name

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#419]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description

When changing user profile name and pressing save, the UI will show the old one when you route back to the profile tab.

While it's actually updated, the UI doesn't render it as such.

### Issue Reproduction

1. Open twitter
2. Route to the profile tab
3. Change profile name
4. Route to home page of twitter
5. Route back to profile page

The UI shows the old profile name but if you tweet it shows the new one.

**Comment by itschip** [comment]
Should be fixed in e87e97d94db8559c47ab85ded518cf7c4579dd77

**Comment by RockySouthpaw** [comment]
Resolved
