### ISSUE TITLE
Bug(Twitter): Emoji search doesn't disable control action

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#420]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description

If you press a key when searching for an emoji that should open a menu, like vMenu or dpEmotes, it will pull the menu up.

### Issue Reproduction

1. Open Twitter
2. Create tweet
3. Search the emoji you want and type a letter with a key that opens a menu. 

Menu will open while the phone is open.

### Evidence

![image](https://user-images.githubusercontent.com/55056068/145474799-af1a2fc1-9554-473c-b07a-7679c8048121.png)

**Comment by itschip** [comment]
Fixed in 8dd47d00c2553a9c48c3361958727d37e55cdaf0
