### ISSUE TITLE
Enhancement(Twitter): Make use of unused profile fields

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#421]
### Application

Twitter

### Dependency

No

### Feature Description

We currently have the following fields that we don't use:
![image](https://user-images.githubusercontent.com/55056068/145475882-deb1780a-b928-4ba3-aaf9-111a9707e5d7.png)

If we're going to keep these, we should add something that displays these otherwise they're pointless to keep.

**Comment by itschip** [comment]
ITS FOR THE ROLEPLAYERS

**Comment by RockySouthpaw** [comment]
> ITS FOR THE ROLEPLAYERS

Kek

**Comment by itschip** [comment]
We could always have a tooltip, if you hover over the avatar in the tweet list, which shows this information?

**Comment by RockySouthpaw** [comment]
> We could always have a tooltip, if you hover over the avatar in the tweet list, which shows this information?

Yea that would work, just be a bit weird with if the tweet is at the bottom of the phone in terms of where to position it

**Comment by itschip** [comment]
Actually, let's not.

**Comment by itschip** [comment]
Removed in d90d04fdebe0b9769353cdf55b88e1087655e016. Someone that is more creative that me can figure out that they could be useful for.
