### ISSUE TITLE
Bug(Messages): Failure to populate search field for message creation

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#422]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description

More so a critical issue as this effects the ability of marketplace and contacts.

Currently, if we click the Message icon within `Contacts` or `Marketplace`, we are routed to the page to create a message conversation, however, the search field is not populated.

![image](https://user-images.githubusercontent.com/55056068/145476723-36d5ab0f-dc14-4934-8f4c-0af5cf52de18.png)

This is generally *okay* with contacts as we can just re-type it, however, with marketplace it's actually almost impossible to message the author of the listing unless you hover over the `phone call` icon and get the number from it. 

What should actually happen is the number from the listing be populated into the create message field as well as the contacts name.

### Issue Reproduction

1. Open Marketplace
2. Press the message icon

You'll be routed to the messages page but you won't have the number auto filled. Essentially unable to contact the listing author unless you know that hovering over the call icon shows their number.

1. Open Contacts
2. Click message icon

You'll be routed to the messages page but the selected contact isn't passed. You have to re type the contact name now.

**Comment by itschip** [comment]
Should be fixed in c81340ab147c6f0d07f66247f9501c9fbc34e84c

**Comment by RockySouthpaw** [comment]
Resolved
