### ISSUE TITLE
Bug(Messgaes): Crash when using ESX

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#425]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description
When routing to message conversation, nui 'freezes' but doesn't seem to crash.

### Issue Reproduction
- open phone
- route to messages
- create conversation or use existing
- click conversation
- press back at the top left
- click conversation again

'freezes' occurs here

Issue persist after resource restart

Not resolved by `phone:restart`
### Evidence
https://streamable.com/sayjep

### Resource Version
[ox esx](https://github.com/overextended/es_extended)
[esx_multichar](https://github.com/thelindat/esx_multicharacter)

### Start Order
```
ensure pma-voice
ensure screenshot-basic
ensure npwd
ensure esx-npwd # should be unrelated
```

**Comment by RockySouthpaw** [comment]
Apparently does the same even without multichar

**Comment by RockySouthpaw** [comment]
Some logs:
![image](https://user-images.githubusercontent.com/55056068/145669654-11437e96-5954-4c41-b82b-327f465057bf.png)

It prints 2 since they use esx-npwd which is already in ox but doesn't seem to matter as i tested a similiar approach and doesnt mess anything up.

**Comment by itschip** [comment]
> press back at the top left

From the video, it is the 'home' button

**Comment by RockySouthpaw** [comment]
> > press back at the top left
> 
> From the video, it is the 'home' button

You can simply route back to the messages group and it’ll crash

**Comment by itschip** [comment]
Can confirm that it is related to conversationsId's with using `[prefix]:` with the 'colon'. Could try to encode the URI.

**Comment by RockySouthpaw** [comment]
> Can confirm that it is related to conversationsId's using `[prefix]:` with the 'colon'. Could try to encode the URI.

So it’s a “you” issue? 

Closed

**Comment by RockySouthpaw** [comment]
I joke

**Comment by itschip** [comment]
Fixed.
