### ISSUE TITLE
Enhancement(Messages): Add a way to call from conversation

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#426]
### Application

Messages

### Dependency

No

### Feature Description

Just add an option to call the player. We have the drop down functionality already so starting a call with the target number should be simple to add here. Could also do a button instead for calling and would give us enough padding

![image](https://user-images.githubusercontent.com/55056068/145701232-38f921c4-7dd8-417b-9884-72e9f37bd344.png)

**Comment by NuttyShrimp** [comment]
Is something like this not more intuitive for the user?
![image](https://user-images.githubusercontent.com/5462901/147860712-4740beea-b6fd-4569-945f-70265d6ebb32.png)

**Comment by RockySouthpaw** [comment]
The only reason I suggested using the existing drop down stuff is to not add anything additional functionality wise.

**Comment by NuttyShrimp** [comment]
Something like this then? Only 'problem' I had to prevent adding a new translation was putting the phonenumber behind the translation
![image](https://user-images.githubusercontent.com/5462901/147966903-32727a6b-c9b1-48ce-9db6-102ef6e3ac64.png)

**Comment by RockySouthpaw** [comment]
> Something like this then? Only 'problem' I had to prevent adding a new translation was putting the phonenumber behind the translation
> ![image](https://user-images.githubusercontent.com/5462901/147966903-32727a6b-c9b1-48ce-9db6-102ef6e3ac64.png)

Yea something like this would probably work okay. I think there might be some existing translations we can use for “call” I think. Not 100% sure though.

@TasoOneAsia @itschip Thoughts?

**Comment by NuttyShrimp** [comment]
I'm currently using that translation but I don't now if there are languages where the number is placed somewhere else in the sentence then at the end

**Comment by itschip** [comment]
> Is something like this not more intuitive for the user? ![image](https://user-images.githubusercontent.com/5462901/147860712-4740beea-b6fd-4569-945f-70265d6ebb32.png)

I like this. The modal should be deleted, as you can now delete multiple conversations from the messages list.

**Comment by RockySouthpaw** [comment]
> > Is something like this not more intuitive for the user? ![image](https://user-images.githubusercontent.com/5462901/147860712-4740beea-b6fd-4569-945f-70265d6ebb32.png)
> 
> I like this. The modal should be deleted, as you can now delete multiple conversations from the messages list.
> 
> EDIT: Just make the icon slightly smaller.

The modal is still useful Incase you just want to delete individual messages and not an entire conversation. Abstracting that functionality would be weird imo.

**Comment by TasoOneAsia** [comment]
My issue with this modal at the moment is that it seems like an odd choice from a UX standpoint as well (weird component). But, if others actually find it useful then eh.

**Comment by RockySouthpaw** [comment]
> My issue with this modal at the moment is that it seems like an odd choice from a UX standpoint as well (weird component). But, if others actually find it useful then eh.

It can be removed and refactored but the functionality needs to exist in some capacity

**Comment by itschip** [comment]
> > > Is something like this not more intuitive for the user? ![image](https://user-images.githubusercontent.com/5462901/147860712-4740beea-b6fd-4569-945f-70265d6ebb32.png)
> > 
> > 
> > I like this. The modal should be deleted, as you can now delete multiple conversations from the messages list.
> > EDIT: Just make the icon slightly smaller.
> 
> The modal is still useful Incase you just want to delete individual messages and not an entire conversation. Abstracting that functionality would be weird imo.

Hm? You don't delete messages from the modal, the modal deletes the whole convo. We have a context menu which give the ability to delete messages.

**Comment by itschip** [comment]
You can also delete a individual conversation from the message list, but you can choose to delete others in the process.

**Comment by TasoOneAsia** [comment]
Wouldn't it be nice to have a github bot that could order wendy's if CI failed to make you feel better. **real enhancements**. 

> It can be removed and refactored but the functionality needs to exist in some capacity

Yea, don't expect API changes simply presentation layer.

**Comment by RockySouthpaw** [comment]
> > > > Is something like this not more intuitive for the user? ![image](https://user-images.githubusercontent.com/5462901/147860712-4740beea-b6fd-4569-945f-70265d6ebb32.png)
> > > 
> > > 
> > > I like this. The modal should be deleted, as you can now delete multiple conversations from the messages list.
> > > EDIT: Just make the icon slightly smaller.
> > 
> > 
> > The modal is still useful Incase you just want to delete individual messages and not an entire conversation. Abstracting that functionality would be weird imo.
> 
> Hm? You don't delete messages from the modal, the modal deletes the whole convo. We have a context menu which give the ability to delete messages.

Ah mis communication kek

**Comment by TasoOneAsia** [comment]
Will be included with the next minor release.
