### ISSUE TITLE
Bug(Messages): Messages conversation ui doesn't update with new contact name

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#427]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description

When adding a number to a users contact from the message conversation, all goes properly it seems. Just doesn't update the UI portion with the new contact.

### Issue Reproduction

- Open messages
- Find a conversation with a non saved contact
- Open conversation and add the contact
- Input name and save
- Route back to messages.

Still shows number.

**Comment by itschip** [comment]
@RockySouthpaw, should be fixed in 0241e81e7c48b610bd720cd32bd31c97575e5f57

**Comment by RockySouthpaw** [comment]
Resolved
