### ISSUE TITLE
Bug(Messages/Dialer): Overflow with long contact name

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#428]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description

If the contact name is long, the text will overflow horizontally and add a scroll bar.

![image](https://user-images.githubusercontent.com/55056068/145701342-c525a890-84b4-4c7b-9ae2-cd9e6f648bbb.png)

This is similar to [this issue](https://github.com/project-error/npwd/issues/383). Not sure if there will be other instances though.

### Issue Reproduction

Add a message group with a long name contact.

**Comment by RockySouthpaw** [comment]
Also exist on dialer 
![image](https://user-images.githubusercontent.com/55056068/145701530-c22dddcc-b57d-44a9-9b3a-9e081c828ee6.png)

**Comment by RockySouthpaw** [comment]
@TasoOneAsia Partially resolved. Persist within messages conversation still.

![image](https://user-images.githubusercontent.com/55056068/146448300-e930c9b5-811d-4379-8d19-f8fb92397699.png)

**Comment by itschip** [comment]
Fixed in 6a69097322fb84c1850cd379033f78eae237dabf and d9966d6da1e49bc5f4d354a0e7eed1ab49144eb4
