### ISSUE TITLE
Bug(MatchMaker): Brief display of home screen

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#429]
### Developement Issue

Unsure

### Phone Version

Develop

### Issue Description

When routing from the home page to any other tabs, the phone background is shown briefly, but only once. Doesn't occur again unless the phone is restarted.

### Issue Reproduction

- Open phone
- Route to macthmaker
- Click on the center tab

Background is shown.

### Evidence

https://user-images.githubusercontent.com/55056068/146466824-e9e5fb4f-14cc-4551-ae3c-bed08484cf17.mp4

**Comment by itschip** [comment]
Seems like this is fixed @RockySouthpaw
