### ISSUE TITLE
Bug: Picture details still available after deletion.

### ISSUE THREAD

**Issue by c-wide** [project-error/npwd#430]
### Developement Issue

Unsure

### Phone Version

Develop

### Issue Description

After deleting a photo in the Camera app, you can click the back button and interact with the photo as if it was not deleted.

### Issue Reproduction

1. Open Camera app
2. Take a picture
3. Click on that picture in the gallery
4. Delete the picture
5. Click the back button in the bottom right

### Evidence

https://streamable.com/5arah4

**Comment by RockySouthpaw** [comment]
Can you check if it’s deleted from the SQL?

**Comment by c-wide** [comment]
yea its properly updating the database

**Comment by RockySouthpaw** [comment]
Then it should be fine imo and seems like intended functionality of the router button but @itschip would probably know best.

I imagine this functionality is probably the same with other things we delete like message conversation.

**Comment by c-wide** [comment]
I'm not sure if its the same with messages but with contacts, if you add a contact, delete it, then go back, it appears to do nothing the first time then goes back to the main screen.

**Comment by itschip** [comment]
Fixed in 1aefaa09cc98a66edb755ab653c6c7be1972eb5c
