### ISSUE TITLE
Bug(Dialer): call history doesn't populate contacts on first open

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#432]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description

When first joining or restarting phone, the call history will show the phone number instead of contact name. It isn't fixed until the list is refreshed by re-opening the app.

### Issue Reproduction

1. Call a contact
2. restart phone
3. Open dialer

Contact Number will be shown

4. Route to home
5. Open dialer

Contact name is now shown

### Evidence

![image](https://user-images.githubusercontent.com/55056068/147211217-714e7c61-b118-43d2-af8e-752b7e9d1bb9.png)
![image](https://user-images.githubusercontent.com/55056068/147211253-e0e97853-9c73-4526-b345-85de7901f972.png)

**Comment by jfrader** [comment]
Fix is merged in develop branch for this issue @RockySouthpaw

**Comment by RockySouthpaw** [comment]
I’ll test this later today
