### ISSUE TITLE
Bug(Calling): While call is ringing, pressing the router locks you from making calls.

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#433]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description

While a call is being made and the router is pressed (bottom right button); the user is unable to call anyone else. I assume this is due to the fact that they're technically still in a call. Currently no way to end it so they're locked from calling anyone else as the phone doesn't show the call stuff like end call/ringing.

Probably just need to end call when this is done, but not 200% on the solution.

### Issue Reproduction

1. Start a call
2. Press the bottom right button
3. Attempt to make a call.

No errors or anything. Calls seem to be possible as the server console prints each time but the nui wont display the calling interface.

**Comment by TasoOneAsia** [comment]
## Possible Solution:

### Pre V6 Migration 

Until we migrate to React Router V6 (when key features like `Prompt` and `usePrompt` are added), we should block route transitions whenever call is in a "pending/ringing" state. This block should be lifted when the call status is resolved from the pending state update. 

[Block Reference](https://v5.reactrouter.com/web/example/preventing-transitions)

**Comment by itschip** [comment]
Should be fixed in 86523985e5ffc766008d22652da5a5a18e9bc695

**Comment by RockySouthpaw** [comment]
Resolved
