### ISSUE TITLE
Bug(Messages): Notifications no longer work

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#437]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description

Players no longer receive notifications when a new message is made.

### Issue Reproduction

Reproduction was done with a fresh DB.
1. Open phone
2. Route to messages and create conversation
3. Click conversation and send a message to player 1

Player 1 receives no alert.

**Comment by itschip** [comment]
Fixed in a741b6a78ee23f6f3fb9c65ecffa1ba6d5158434
