### ISSUE TITLE
Bug(Messages): Deleted conversations do not repopulate

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#438]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description

I know the title is a bit confusing but allow me to elaborate.

Player 1 has a conversation with Player 2, and Player 1 deletes the conversation. Now, if player 2 text player 1 at any point going foreward; player 1 will not have that  conversation refreshed/fetched.

### Issue Reproduction

1. Player 2 messages Player 1
-- At this point both Player 1 and Player 2 have the message conversation.
2. Player 1 deletes the conversation.
3. Player 2 messages Player 1 again.

Player 1 will not receive the message within the phone and no conversation will be shown for player 2. The database updates properly though.

**Comment by itschip** [comment]
I don't know if we should to do an extra query each time we send a message, to check if the other player has the conversation or not. It sounds a bit expensive, from a bigger perspective, that is

**Comment by RockySouthpaw** [comment]
Resolved with https://github.com/project-error/npwd/commit/386a3ef888ed908e4e749362c4fde07399c7c0e1
