### ISSUE TITLE
Enhancement: Job Messages

### ISSUE THREAD

**Issue by 0pax** [project-error/npwd#441]
### Application

Messages

### Dependency

Yes

### Feature Description

Would be awesome to add a job message system like GCPhone has. I know its framework dependent, so it could just be a config? And people would be able to send messages to for example the police via their phone. This makes up for less chats, and easier to sort calls etc. This way we wouldn't need a /911 call for example, but when you first join the server, theres a few contacts already setup which is police, so you can send them a message and everyone on duty receives the message.

### References

GCPhone jobmessages.

**Comment by RockySouthpaw** [comment]
We've discussed this internally a decent bit in the past. However, with the phone aiming for standalone implementation and the various frameworks we would need to probably make some other resource to handle this and integrate it into npwd, or an app for it when a config for various getters.

The way gcphone worked for it would be a poor implementation as it messaged everyone with that job regardless if they we're online or not. Highly abusable imo. It's also generally entirely unrealistic that you could message the entire police department or mechanic shop.

A proper implementation wouldn't handle job texting but calling instead. I don't have the logistics worked out and internally we haven't put a lot of time into brain storming it.

Off the top of my head we can make a pre determined area(Polyzone) + number for this area. A player could call this number and the phone could trigger a sound within this area so anyone nearby could answer. You can probably get away with using npwd here as it could be a *work phone* and just not a land line as various companies and place of business do this. Would be kind of annoying to implement though.

**Comment by RockySouthpaw** [comment]
We plan to handle this with our exposed events for calling/messaging so server owners can do their own things.

Should be able to make your own system on your own when we finish it.
