### ISSUE TITLE
Enhancement: Automatic answer when messaging "npc" numbers

### ISSUE THREAD

**Issue by Oldarorn** [project-error/npwd#445]
### Application

Other

### Dependency

No

### Feature Description

The idea is to get an automatic answer when you send a message to a (potential) reserved number.

For example if I'm looking for a weed dealer, I send my message to XXX-XXXX and I get a position where I can find the npc. 

It could be an open door for other things, you can reserve some numbers to send scam or ads to your players if they contacts those numbers. (yeah, something it's funny to troll people)

In a far away future you could contact the Taxi society to get a driver and if no taxi is online it sends an auto answer + an AI which drives the taxi. (could be linked to https://github.com/project-error/npwd/issues/441 but I read it's a low priority then this one is too imo)

I did the first part with GCPhone some years ago, I know it's not a reference anymore but I'm sure if I could did this before, it would be even better with NPWD !

**Comment by RockySouthpaw** [comment]
I assume a reference table with configired numbers would be fine? 

As far as the NPC taxi stuff, we’ve thought about it in the past but it’s one of those things that ended up not being important enough to be a priority as kidz made something similar in the last.

**Comment by Oldarorn** [comment]
If we are free to fill the table and link messages to each number, we should be fine (I guess ?) !

**Comment by RockySouthpaw** [comment]
We plan to handle this with our exposed events for calling/messaging so server owners can do their own things.

You should be able to implement subsequent logic easily with this when we finish so closing this as a result. Thank you for the suggestion. :)
