### ISSUE TITLE
Bug: weird behavior with infinite scroll in twitter app

### ISSUE THREAD

**Issue by Ekinoxx0** [project-error/npwd#447]
### Developement Issue

Yes

### Phone Version

develop branch and release version

### Issue Description

Hi,

When using the Twitter app, if your server contains a lot of tweets, it seems like the latest tweets are not loaded in the correct order.
Oldest tweets are available first, when scrolling down you are then loading the more recent tweets.

My server currently have 1061 tweets in 10 days, I can provide dump of the database in private if neccessary :)

### Issue Reproduction

 1. Go to twitter App
 2. Make a lot of tweets
 3. Disconnect then reconnect
 4. Open the twitter app again
 -> You will see older tweets first, latest tweets loading when scrolling

### Evidence

https://streamable.com/42yt3v

**Comment by itschip** [comment]
I thought I fixed this :(

**Comment by RockySouthpaw** [comment]
Define “a lot of tweets”

**Comment by TasoOneAsia** [comment]
@itschip Still an issue as well

**Comment by itschip** [comment]
Fixed in e97181d9d86105da07d3824964b55405b49a9d2c
