### ISSUE TITLE
Bug(Calling): Custom wallpapers don't show or show improperly.

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#449]
### Developement Issue

Yes

### Phone Version

Develop

### Issue Description

Normally when you're calling someone, the background is shown so long as it's a background defined within the phone. However, if you use a custom wallpaper it will be black when calling or the image is partially cut off.

it looks okay from this code `backgroundImage: `url(${getBackgroundPath(settings.wallpaper.value)})`,` so not too sure

### Issue Reproduction

1. Set a custom wallpaper
2. Call someone

### Evidence

With predefined:

![image](https://user-images.githubusercontent.com/55056068/147527672-7a5137aa-a5bf-48d9-8dbe-6b708670241a.png)

Custom:

![image](https://user-images.githubusercontent.com/55056068/147527676-0eb6e789-48e7-42fe-b082-e054685fe02f.png)

**Comment by itschip** [comment]
Fixed in 8a1220474ff83db5fbcc8b3056c66260f3c80f4e
