### ISSUE TITLE
Bug: Marketplace Open.

### ISSUE THREAD

**Issue by LittleFishyy** [project-error/npwd#453]
### Developement Issue

Unsure

### Phone Version

0.4.3

### Issue Description

I was testing and I entered the "Marketplace" and I got a fatal error.

### Issue Reproduction

  1. Open the phone.
  2. Click on "Marketplace App"

### Evidence

![image](https://user-images.githubusercontent.com/89689629/147594962-275e732e-c6a1-43d1-906e-c5c6d55b367f.png)

**Comment by TasoOneAsia** [comment]
Can you please provide the logs as well?

**Comment by LittleFishyy** [comment]
Asi es, voy dame un segundo.

**Comment by LittleFishyy** [comment]
That's right, give me a second. (( I closed without meaning to. ) ))

**Comment by LittleFishyy** [comment]
![image](https://user-images.githubusercontent.com/89689629/147595344-6b99f502-aa4b-49a1-a083-87774640f521.png)
This is the last log of the Marketplace.

**Comment by itschip** [comment]
Ah, did I never update the sql file?

**Comment by LittleFishyy** [comment]
Mmm, I added the SQL as it is in the file. I don't think so.

**Comment by itschip** [comment]
> Mmm, I added the SQL as it is in the file. I don't think so.

I did. Does you 'marketplace_listing' table contain the `reported` column?

**Comment by LittleFishyy** [comment]
![image](https://user-images.githubusercontent.com/89689629/147595506-62e03323-71cd-447e-8e25-6e166745588c.png)
The tables are created.

**Comment by itschip** [comment]
Still, does the 'marketplace_listings' table have the `reported` column?

**Comment by LittleFishyy** [comment]
Yes.

**Comment by LittleFishyy** [comment]
Fixed, thanks for your support.
