### ISSUE TITLE
Bug: Spanish translation.

### ISSUE THREAD

**Issue by LittleFishyy** [project-error/npwd#460]
### Developement Issue

No

### Phone Version

1.0.0

### Issue Description

When you change the phone language to Spanish, the translation fails.

### Issue Reproduction

 1. Go to Settings
  2. Click on Language
  3. See error

### Evidence

![image](https://user-images.githubusercontent.com/89689629/147857801-a3932f0a-f47a-41b9-ae01-c4d821908128.png)

**Comment by BombayV** [comment]
The translation doesn't fail, it's just that those are the missing keys.
See #442 for the translations,

**Comment by RockySouthpaw** [comment]
The pr mentioned above is being tested and will be merged soon, sit tight.

**Comment by RockySouthpaw** [comment]
Resolved with https://github.com/project-error/npwd/commit/ae11040bb00945f82fe1270c95d28a9764178970
