### ISSUE TITLE
Bug: Messages app error

### ISSUE THREAD

**Issue by Xxpromw3mtxX** [project-error/npwd#467]
### Developement Issue

Unsure

### Phone Version

I'm using the latest released version.

### Issue Description

The error that I'm encountering is this one:
```
[script:npwd] [NPWD] [messages] [error]: Failed to fetch messages groups, Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='
```

### Issue Reproduction

I don't actually know how to reproduce this error.
But I'm 100% sure that the messages app is the only one not working as intended.

### Evidence

https://streamable.com/dom3b3

**Comment by itschip** [comment]
This is an issue on your side. You'll have to make sure that all the tables used by npwd is using the same collation in your database, iirc.

**Comment by Xxpromw3mtxX** [comment]
Solved!
Thank you guys!
