### ISSUE TITLE
Bug(camera): photo could not be saved (Imgur related)

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#475]
### Developement Issue

Yes

### Phone Version

Develop but will occur on all future builds.

### Issue Description

Photo fails to upload to imgur causing it to be null. As we don't save null images in the database, an error is tossed on the phone. "Photo could not be saved :("

This cause correlation seems to be the following:
- Imgur is blocked in certain countries.
- Imgur token is placed into the `server.cfg` incorrectly. Should be the following: `setr SCREENSHOT_BASIC_TOKEN XXXXXXXXXXXXXXX`

### Possible Solutions
Need to focus test this still. But the team is aware of the issue currenlty and are working on exploring solutions.

**Comment by itschip** [comment]
Someone seems to be adding the `Client-ID` in the `config.json` as well. Do we need to improve docs here?

**Comment by RockySouthpaw** [comment]
> Someone seems to be adding the `Client-ID` in the `config.json` as well. Do we need to improve docs here?

The new docs are pretty clear on what to do but I can be even more clear.

**Comment by RockySouthpaw** [comment]
Might close this issue as this likely stems from people using the wrong screenshot-basic version and not the one from our org.

**Comment by RockySouthpaw** [comment]
Closing

**Comment by frazz1234** [comment]
still can't upload image
