### ISSUE TITLE
Bug(PlayerUnload): phone data isn't showing new player data

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#476]
### Developement Issue

No

### Phone Version

Develop

### Issue Description

When unloading a character via `exports.npwd:unloadPlayer(playerId)`, the phone isn't properly loading the subsequent player as the recoil state isn't being reset.. Resulting in characters sharing the same information

### Issue Reproduction

Unload a previously loaded character with the export and load a new one.

**Comment by RuisSoftware** [comment]
Same here ;)

**Comment by RockySouthpaw** [comment]
> Same here ;)

Fix it then.

**Comment by RuisSoftware** [comment]
> > Same here ;)
> 
> Fix it then.

Wow never gonna donate that's for sure.

**Comment by Destructor** [comment]
ETA?

**Comment by itschip** [comment]
Closing this. Fixed in 1a78500b3f24f5f49cc23113acb6617b919b19ec

**Comment by minipunch** [comment]
Should prob remove the warning from the docs warning about this now closed issue fyi
