### ISSUE TITLE
Bug(calling): call volume is too low

### ISSUE THREAD

**Issue by PlzAdoptMee** [project-error/npwd#478]
### Developement Issue

Unsure

### Phone Version

[Uploading npwd.zip…]()
[Uploading npwd-1.0.3.zip…]()

### Issue Description

Me and someone has been working in the files trying to see if we can adjust the volumes. We have the newest pma-voice installed. We are using ESX as well. When in game, me and someone try to call each other but I can hear him (very quietly) and he can't hear me. When we are walking around each other we can hear each other perfectly fine. We have the build file in the server but we are searching through both files to see if we can find a volume control. We also try tweaking things in pma-voices but nothing worked. The volumes for the notification and ringtones work perfectly fine as well.

### Issue Reproduction

1. Pull up phone
2. Call a player
3. Both players speak
4. Barely any volume to the phone

### Evidence

Kind hard to post evidence of the volume messing up.

**Comment by RockySouthpaw** [comment]
There is nothing within the resource to adjust the volume of someone in a call. 

All we do is use pma to set you into a call channel:
`exp['pma-voice'].setCallChannel(callData.channelId);` whatever voice issues that are occurring as a result isn’t something we’re setting.

We can explore an enhancement to set call volume though as that’s a neat idea and seems possible. 

Not 100% sure the cause of your issue though. May be something that you can open an issue about with PMA or ask within the FiveM discord.
