### ISSUE TITLE
Enhancement: Allow for Hooking Into Message/Call Requests

### ISSUE THREAD

**Issue by akassl-lab** [project-error/npwd#479]
### Application

Messages

### Dependency

No

### Feature Description

I saw a message the other day with an explanation on why a specific job message system wouldn't be on the table.

I do understand your opinion on this but hey let's try to make it a 50/50 situation for both the devs and the actual users?

Instead of making it a job based handler, how about an event where we can catch when a player is dialing a specific number and let us server owners decide what we should do with it? This means, for us that uses GCPhone with other stuff integrated in it and not just jobs, we will be able to switch over to NPWD and continue giving our players the experience they enjoy.

This is the only thing that is making me having a hard time to take the full decision to switch over since this is an essential feature. 

+ It shouldn't be much of a hassle to add it I am guessing? We just need that simple callback/export for when a player sends a message or even a phone call and us the dev will be able to do the rest through our external resources.

### References

`Just a simple callback/export to handle any outgoing messages or calls`

**Comment by itschip** [comment]
My idea was a simple export you can utilize. Pass in a number, and a callback with what you want to do when a user is calling said number.

Something like 

```lua
exports.npwd:onCall("911", function(phoneNumber)
 -- do something
end)
```

This obviously has to be discussed futher.

**Comment by RockySouthpaw** [comment]
We're already planning on exposing the message event so server owners can create messages to whoever they would like so functionality like "Sending a text message to x person when someone dies" would be possible. Idk the exact implementation we were going for though.

I'm **personally** not keen on job based messaging as it's an absurd practice, without even factoring in the unrealistic nature of it, to trigger a server event for a multitude of people at once (upwards to 20-25 people on higher pop servers.) and we will indirectly be blamed for it in the event some resource pops up that accomplishes this. GcPhone does extremely poor if population does exceed 64 slots and part of that is due to how poorly it integrated jobs into it.

Some server owners, not saying you in particular, are so use to these bad practices, and so are their players that they simply can't think outside of the box when it comes to this specific thing. 

While the rest of the team may feel differently about it, this is my personally opinion.

**Comment by akassl-lab** [comment]
> We're already planning on exposing the message event so server owners can create messages to whoever they would like so functionality like "Sending a text message to x person when someone dies" would be possible. Idk the exact implementation we were going for though and we still need to work out exactly how it would work.
> 
> I'm **personally** not keen on job based messaging as it's an absurd practice, without even factoring in the unrealistic nature of it, to trigger a server event for a multitude of people at once (upwards to 20-25 people on higher pop servers.) and we will indirectly be blamed for it in the event some resource pops up that accomplishes this. GcPhone does extremely poor if population does exceed 64 slots and part of that is due to how poorly it integrated jobs into it.
> 
> Some server owners, not saying you in particular, are so use to these bad practices, and so are their players that they simply can't think outside of the box when it comes to this specific thing.
> 
> While the rest of the team may feel differently about it, this is my personally opinion.

I do fully understand but the devs should never to be blamed for something that is being done externally. That's the thing with these type of resources, they should be developed in a way that it depends on the user on how he should utilize the resource. I personally, would step away from the "call a job via a phone" but just a simple way to catch a phone number and let us handle the rest would be perfect and if the server owners doesn't know how to make it in a proper way, well that's their issue and not yours since you're just providing us a way to have a better control over the phone system.

Mainly, me it's more for drug usages than jobs.

The four exports the most essential to make this possible would be a 

`onCall`
`sendMessage`
`onMessage`
`sendCall`

So we can handle it and perform further tasks using the information that was parsed via those exports

**Comment by RockySouthpaw** [comment]
> > We're already planning on exposing the message event so server owners can create messages to whoever they would like so functionality like "Sending a text message to x person when someone dies" would be possible. Idk the exact implementation we were going for though and we still need to work out exactly how it would work.
> > I'm **personally** not keen on job based messaging as it's an absurd practice, without even factoring in the unrealistic nature of it, to trigger a server event for a multitude of people at once (upwards to 20-25 people on higher pop servers.) and we will indirectly be blamed for it in the event some resource pops up that accomplishes this. GcPhone does extremely poor if population does exceed 64 slots and part of that is due to how poorly it integrated jobs into it.
> > Some server owners, not saying you in particular, are so use to these bad practices, and so are their players that they simply can't think outside of the box when it comes to this specific thing.
> > While the rest of the team may feel differently about it, this is my personally opinion.
> 
> I do fully understand but the devs should never to be blamed for something that is being done externally. That's the thing with these type of resources, they should be developed in a way that it depends on the user on how he should utilize the resource. I personally, would step away from the "call a job via a phone" but just a simple way to catch a phone number and let us handle the rest would be perfect and if the server owners doesn't know how to make it in a proper way, well that's their issue and not yours since you're just providing us a way to have a better control over the phone system.
> 
> Mainly, me it's more for drug usages than jobs.
> 
> The four exports the most essential to make this possible would be a
> 
> `onCall` `sendMessage` `onMessage` `sendCall`
> 
> So we can handle it and perform further tasks using the information that was parsed via those exports

A lot of people within the FiveM community are **heavily** reliant on others for scripts/snippets/ and even server packs. It would literally take 1 bad resource for a magnitude of issues to be directed at us. As such is/was the case with ESX where bad resources made use of certain practices and as such these same bad practices were utilized by others. Coming full circle to create a slew of unoptimized/vulnerable resources.

We want to have good practices and promote good practices within the community. That’s why this organization exist in the first place. While we could always toss some exports/event handlers at everything and say “Here do what you want”, it’s generally not the best idea. This is why `esx-npwd` exist so we could implement a wrapper properly and correctly.

On topic of this suggestion, I think an event handler for `onCallStart` would be fine. I’m a bit skeptical of one for onMessage in the event we do add group chats back as that doesn’t sound like the best idea imo. 

I would personally use `startCall` over `sendCall`. Something like this is how I would do it : `exports.npwd:startCall(displayName, number function(accepted)` so it returns if it was accepted or not so the call can be ended. Display name can be set Incase someone wants to change the name from the standard phone number.

**Comment by TasoOneAsia** [comment]
I am a fan of a hook type pattern for this, it would most likely provide the best overall freedom and would easily be ported into our current handling system. Here's an example API proposal.

```ts
interface CallCtx {
  incomingCallObject: ActiveCall
  next: () => void
  exit: () => void
  respond: (resp) => void
}

exports.npwd.useCallHandler((callCtxObj: ) => {
  // Holds information about the incoming call
  console.log(callCtxObj.incomingCallObject)
  
  // misc logic ..
  
  // This will just forward to NPWD regular handlers
  callCtxObj.next()
))
```

**Comment by akassl-lab** [comment]
Hello,

Is this being worked on?

**Comment by RockySouthpaw** [comment]
Yes?

**Comment by RockySouthpaw** [comment]
Messages is done. Just waiting on calls before this is closed.

**Comment by frazz1234** [comment]
> Messages is done. Just waiting on calls before this is closed.
> 
> You can currently use this:
> 
> ```lua
> Config                  = {}
> 
> Config.emergencyNumbers = {
>     '911',
>     '112',
> }
> 
> for i = 1, #Config.emergencyNumbers do
>     local number = Config.emergencyNumbers[i]
>     exports.npwd:onMessage(number, function(ctx)
>         print('Target Number: ['..ctx.data.tgtPhoneNumber..'] Message: ['..ctx.data.message..']')
>     end)
> end
> ```
> 
> No way to get source number atm from what i saw so will need to be added

Where are you putting this, im a little lost whit that
