### ISSUE TITLE
Enhancement: Additional lines to locales 

### ISSUE THREAD

**Issue by Rav3n95** [project-error/npwd#480]
### Application

Marketplace

### Dependency

No

### Feature Description

Hey, i wonder if there is a chance to add these lines to locale files: 

- New Listing
- Choose a image
- POST

### References

![kép_2022-01-04_095227](https://user-images.githubusercontent.com/69343477/148033464-3d7536c7-9a6a-4ad8-9231-415f1afa719c.png)

**Comment by RockySouthpaw** [comment]
I don’t see why not. Do you see any other places with missing translations?

**Comment by Rav3n95** [comment]
> I don’t see why not. Do you see any other places with missing translations?

Actually yea, on the setting site. Names of the themes, pictures. But i dont thinks so thats possible or even worth it. 
Rn since i updated the phone few app just loading contantly so im debuging rn.

**Comment by itschip** [comment]
You'll have to change the names on the thems and the backgrounds yourself @Rav3n95

**Comment by Rav3n95** [comment]
> You'll have to change the names on the thems and the backgrounds yourself @Rav3n95

Yeah, but later on if the do labels for it. It's benefit every other languages

**Comment by RockySouthpaw** [comment]
Chip said it was resolved so closing
