### ISSUE TITLE
Bug: 1.0.4 update started to error

### ISSUE THREAD

**Issue by Rav3n95** [project-error/npwd#481]
### Developement Issue

Unsure

### Phone Version

1.0.4

### Issue Description

Since i upgraded from 1.0.3 im getting this error, maybe becasue i changed my steam name?

### Issue Reproduction

See error

### Evidence

![kép_2022-01-04_100958](https://user-images.githubusercontent.com/69343477/148035678-84e6eefe-51a4-45f2-903e-b58a0fb51903.png)

**Comment by TasoOneAsia** [comment]
There were no changes to this specific code flow with 1.0.4. Did you change anything?

**Comment by Rav3n95** [comment]
> There were no changes to this specific code flow with 1.0.4. Did you change anything?

Deleted the old folder, copyed the new one

**Comment by Rav3n95** [comment]
Looks like few people have the same problem on discord support channel.

**Comment by TasoOneAsia** [comment]
Im gonna guess that you updated your `config.json` when you updated NPWD. Please make sure that configuration is still correct.

**Comment by Rav3n95** [comment]
<3
