### ISSUE TITLE
Bug: Add ESX Item

### ISSUE THREAD

**Issue by Sander2222** [project-error/npwd#485]
### Developement Issue

Yes

### Phone Version

1.0.4

### Issue Description

Hello, i want do handle the phone as an item by ESX, but i dont know how. in the config.json i placed this for the item:

```
{
  "PhoneAsItem": {
    "enabled": true,
    "exportResource": "es_extended",
    "exportFunction": "esx:getSharedObject"
  },
```

but when i start the phone and press F1 (the oppening button) i get this error and i dont what i am doing wrong can someone help me:
![image](https://user-images.githubusercontent.com/86840128/148124009-9358dc33-e67a-4e5e-abf2-ec0b2bab7ee0.png)

### Issue Reproduction

1. there are no steps

**Comment by TasoOneAsia** [comment]
This is not at all what this config option is for. The `exportResource` and `exportName` options should target an export that will check to see if NPWD can be opened or not.  For example

```json
  "PhoneAsItem": {
    "enabled": true,
    "exportResource": "my_resource",
    "exportFunction": "exportName"
  },
  ```
  
  In the `my_resource` client script
  
  ```lua
  exports('exportName', function()
      -- Now determine whether NPWD can be opened
      -- Indicates that NPWD can be opened, if it returns false then NPWD cant be opened.
      return true
  end)

**Comment by Sander2222** [comment]
thanks a lot

**Comment by Sander2222** [comment]
ok i coded the Script but now i get this error: 
![image](https://user-images.githubusercontent.com/86840128/148134642-8b9726f7-3f46-4ecb-925e-3193ae119687.png)

server.lua:

```
ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

ESX.RegisterServerCallback('phone_export:canUse', function(cb)
	local xPlayer = ESX.GetPlayerFromId(source)
	local xItem = xPlayer.getInventoryItem('phone')

	if xItem.limit > -1 and xItem.count >= xItem.limit then
		cb(false)
	else
		cb(true)
	end
end)
```

client.lua 

```
ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

exports('exportName', function()
    ESX.TriggerServerCallback('phone_export:canUse', function(canPickUp)

if canPickUp then
        return true
    else
        return false
     end
end)
end)

```

**Comment by TasoOneAsia** [comment]
You need to use promises as shown below.

```lua
local ESX = exports['es_extended']:getSharedObject()

exports('checkForPhone', function()
  local p = promise.new()
  
  ESX.TriggerServerCallback('phone_export:canUse', function(canPickUp)
    p:resolve(canPickUp)
  end)
 
  return Citizen.Await(p)
end)

**Comment by Sander2222** [comment]
thanks for anwer. the error is gone but now nothing happen do you know why, because i dont get it:

Server.lua:

```
ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

ESX.RegisterServerCallback('phone_export:canUse', function(cb)
	local xPlayer = ESX.GetPlayerFromId(source)
	local xItem = xPlayer.getInventoryItem('phone')

	if xItem.limit > -1 and xItem.count >= xItem.limit then
		cb(false)
	else
		cb(true)
	end
end)
```

client.lua:

```
local ESX = exports['es_extended']:getSharedObject()

exports('canUsePhone', function()
  local p = promise.new()

  ESX.TriggerServerCallback('phone_export:canUse', function(canPickUp)
    p:resolve(canPickUp)
  end)

  return Citizen.Await(p)
end)
```

**Comment by Sander2222** [comment]
is it because there is no if that checks if the player have **no** phone item?

**Comment by TasoOneAsia** [comment]
If you would like step-to-step troubleshooting instructions, I would recommend visiting our discord.

**Comment by Sander2222** [comment]
can you send me?
