### ISSUE TITLE
Bug: <short description>

### ISSUE THREAD

**Issue by FakeItalianMan** [project-error/npwd#490]
### Developement Issue

No

### Phone Version

Newest release

### Issue Description

[     script:esx-npwd] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export newPlayer in resource npwd

### Issue Reproduction

Starting the script up

**Comment by itschip** [comment]
How about starting with giving this issue an title, and we go from there.

**Comment by itschip** [comment]
You know what, create a new issue that is actually useful. This doesn't tell me anything.
