### ISSUE TITLE
When I go to open the phone it doesnt open I get nothing no F8 errors or console errors.

### ISSUE THREAD

**Issue by FakeItalianMan** [project-error/npwd#491]
### Developement Issue

No

### Phone Version

newest download version

### Issue Description

I got to open the phone in-game and it doesnt open I get no F8 or console errors. Then when I restart the phone script I get this error- [     script:esx-npwd] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export newPlayer in resource npwd

### Issue Reproduction

Error only shows when I restart the script.

**Comment by TasoOneAsia** [comment]
If you have not downloaded a tagged release, you must first build the phone.

**Comment by FakeItalianMan** [comment]
Is there documentation on how to do that?

**Comment by TasoOneAsia** [comment]
Oh, apologies, didn't see last part regarding timing of the error.

**Comment by FakeItalianMan** [comment]
> Oh, apologies, didn't see last part regarding timing of the error.

Do you have any idea on how I can fix this? Thanks.

**Comment by FakeItalianMan** [comment]
New Error when I start up the server with the phone started in  the CFG.

[     script:esx-npwd] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export newPlayer in resource npwd
[     script:esx-npwd] > cb (@es_extended/server/main.lua:215)
[     script:esx-npwd] > cb (@async/async.lua:24)
[     script:esx-npwd] > ref (@es_extended/server/main.lua:208)
[     script:esx-npwd] > <unknown> (@mysql-async/mysql-async.js:15543)

**Comment by TasoOneAsia** [comment]
I would suggest you stay patient and wait for a reply. I am currently at work and other members are busy.  They will reply to this issue when they get a chance.

**Comment by BombayV** [comment]
> I get the following error: No such export: newPlayer in resource npwd
> This export is only available when the useResourceIntegration is set to true. See here: https://github.com/project-error/npwd/blob/fc2a905f0fd85db797b716053b8f0d4398b8bd61/config.json#L8

Refer to this. It might help. @FakeItalianMan

**Comment by FakeItalianMan** [comment]
> > I get the following error: No such export: newPlayer in resource npwd
> > This export is only available when the useResourceIntegration is set to true. See here: https://github.com/project-error/npwd/blob/fc2a905f0fd85db797b716053b8f0d4398b8bd61/config.json#L8
> 
> Refer to this. It might help. @FakeItalianMan

No still get the same issues. Thanks though.

**Comment by tehface** [comment]
same issue 
its set to false as post above

```
[      script:qb-npwd] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:878: No such export newPlayer in resource npwd
[      script:qb-npwd] > safeCallback (@oxmysql/oxmysql.js:20087)
[      script:qb-npwd] > <unknown> (@oxmysql/oxmysql.js:20094)
[      script:qb-npwd] > processTicksAndRejections (node:internal/process/task_queues:96)
```

**Comment by RockySouthpaw** [comment]
This export is only available when the `useResourceIntegration` is set to true. See here: <https://github.com/project-error/npwd/blob/fc2a905f0fd85db797b716053b8f0d4398b8bd61/config.json#L8>

**Comment by RockySouthpaw** [comment]
> New Error when I start up the server with the phone started in the CFG.
> 
> [ script:esx-npwd] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export newPlayer in resource npwd [ script:esx-npwd] > cb (@es_extended/server/main.lua:215) [ script:esx-npwd] > cb (@async/async.lua:24) [ script:esx-npwd] > ref (@es_extended/server/main.lua:208) [ script:esx-npwd] > (@mysql-async/mysql-async.js:15543)

Yours is the same issue as mentioned above and by bombay. The only other instance of this errow would be a race condition in which NPWD was having that export called before the resource was ready. You can try starting npwd before your core/framework.

**Comment by tehface** [comment]
> This export is only available when the `useResourceIntegration` is set to true. See here:
> 
> https://github.com/project-error/npwd/blob/fc2a905f0fd85db797b716053b8f0d4398b8bd61/config.json#L8
> 
> @tehface

mine is set to false already, i've not even changed the config, everything is default

**Comment by RockySouthpaw** [comment]
Thats the problem. As i stated, it needs to be **set to true** for this export to be available.

**Comment by tehface** [comment]
> Thats the problem. As i stated, it needs to be **set to true** for this export to be available.

just tried it to true... still the same

**Comment by RockySouthpaw** [comment]
Please reach out on the discord https://discord.com/invite/HYwBjTbAY5
