### ISSUE TITLE
Bug: <sql>

### ISSUE THREAD

**Issue by VoltexTV** [project-error/npwd#492]
### Developement Issue

Yes

### Phone Version

1.0.4

### Issue Description

[ script:npwd] [NPWD] [info]: Sucessfully started
[ script:npwd] Error: Unhandled promise failure: Error: Access denied for user 'u***********'@'81.*********' (using password: YES)
[ script:npwd] at l.query (@npwd/resources/dist/server/21a52c84805197a6caf4.server.js:16:54662)
[ script:npwd] at Object._rawExec (@npwd/resources/dist/server/21a52c84805197a6caf4.server.js:16:36540)
[ script:npwd] at @npwd/resources/dist/server/21a52c84805197a6caf4.server.js:24:19714
[ script:npwd] at Generator.next (<anonymous>)
[ script:npwd] at @npwd/resources/dist/server/21a52c84805197a6caf4.server.js:24:19245
[ script:npwd] at new Promise (<anonymous>)
[ script:npwd] at r (@npwd/resources/dist/server/21a52c84805197a6caf4.server.js:24:18990)
[ script:npwd] at t.findOrGeneratePhoneNumber (@npwd/resources/dist/server/21a52c84805197a6caf4.server.js:24:19510)
[ script:npwd] at Object.<anonymous> (@npwd/resources/dist/server/21a52c84805197a6caf4.server.js:16:31717)
[ script:npwd] at Generator.next (<anonymous>)
[ script:npwd] SCRIPT ERROR in event `npwd:getCredentials': TypeError: Cannot read properties of null (reading 'getPhoneNumber')
[ script:npwd] > <unknown> (@npwd/resources/dist/server/21a52c84805197a6caf4.server.js:24)
[ script:npwd]

### Issue Reproduction

nothing just the 1st start

**Comment by anes66** [comment]
> Access denied for user 'u***********'@'81.*********' (using password: YES)

that have nothing to do with this phone script or bug there is you problem the phone cant connect to the database

**Comment by ZypsohDEV** [comment]
> 

i have TypeError: Cannot read properties of null (reading 'getPhoneNumber') but my sql is running ok

**Comment by RockySouthpaw** [comment]
> > 
> 
> i have TypeError: Cannot read properties of null (reading 'getPhoneNumber') but my sql is running ok

open an issue or use the discord

**Comment by RockySouthpaw** [comment]
This issue is due to improper database configuration. Unrelated to npwd.
