### ISSUE TITLE
Enhancement: Phone Subscription or credit with a signal tower for sound quality

### ISSUE THREAD

**Issue by anes66** [project-error/npwd#493]
### Application

Other

### Dependency

No

### Feature Description

Hello team
This way I would have one suggestion to add for the phone so that you can choose whether you want to use a subscription phone or, for example, top up your credit and withdraw it from your account every hour, ie from the bank, depending on the number of calls and text messages. I hope you understand the point of my writing or my request it would also not be bad to do it as signal towers eg if we are somewhere in the mountains that the signal is weaker or a little worse sound quality or eg if there is a good signal in town that the sound quality is good

**Comment by RockySouthpaw** [comment]
Cell service areas was something I wanted to make but it was something I was unsure if people would actually use. 

As far as prepaid phones go, this is also a cool idea and probably not hard to implement with a 3rd party resource once we expose certain events.

**Comment by OhTanoshi** [comment]
cell service area would definitely be something awesome to have and make things a lot better for roleplay.

**Comment by RockySouthpaw** [comment]
> cell service area would definitely be something awesome to have and make things a lot better for roleplay.

Ill work on it eventually

**Comment by anes66** [comment]
any news about this

**Comment by WEEZOOKARP** [comment]
Yeah cell service would be a nice touch, you wouldn't be able to call someone on your phone from the doomsday bunkers for instance.
