### ISSUE TITLE
Enhancement: Phone Battery and Recharge

### ISSUE THREAD

**Issue by anes66** [project-error/npwd#494]
### Application

Other

### Dependency

No

### Feature Description

Hello

I remembered one good but probably simple idea but unfortunately so far no one has done it right. My suggestion would be that the phone loses some percentage of battery over time and when it reaches 0% for example to display a logo or icon as if the battery is empty and needs to be recharged for the phone to work again.

The ways it could be charged would be very simple
The first way would be In a car, truck, bus, etc., etc.
The second way would of course be the good old PowerBank with different capacity filled, for example, 3 types of powerbank, of which e.g.
The first Powerbank can charge 1 phone from 0% to 100%
Another Powerbank can charge 2 phones from 0% to 100%
Third Powerbank can charge 3 phones from 3% to 100%

I hope you like the idea :)

**Comment by RockySouthpaw** [comment]
No one’s implemented this properly because of the server limitations to do so.
A proper implementation would require someone to model a phone charger, including a cord, and attach said cord to the phone when charging from a power bank or wall/vehicle. 

You’d also need configured charging locations outside of vehicles because you can’t really get wall outlet locations. So you’d likely need to think out the box and just model a charging station that has outlets.

So we’re talking:
- Model for phone block
- Model for phone cord
- Configured areas to charge phone
   - Using a prop for this as well would make most sense
- Exports to handle it on outside resources 

The modeling aspect of this is the only major limitation imo. We initially had a battery indicator in the early stages of the phone but was scrapped. 

There’s also some math too that would need to be addressed to determine the rate at which the battery would deplete as it would need to deplete slower while not in use and faster when you’re in a call compared to when the phone is normally opened.

**Comment by anes66** [comment]
> No one’s implemented this properly because of the server limitations to do so. A proper implementation would require someone to model a phone charger, including a cord, and attach said cord to the phone when charging from a power bank or wall/vehicle.
> 
> You’d also need configured charging locations outside of vehicles because you can’t really get wall outlet locations. So you’d likely need to think out the box and just model a charging station that has outlets.
> 
> So we’re talking:
> 
> * Model for phone block
> * Model for phone cord
> * Configured areas to charge phone
>   
>   * Using a prop for this as well would make most sense
> * Exports to handle it on outside resources
> 
> The modeling aspect of this is the only major limitation imo. We initially had a battery indicator in the early stages of the phone but was scrapped.
> 
> There’s also some math too that would need to be addressed to determine the rate at which the battery would deplete as it would need to deplete slower while not in use and faster when you’re in a call compared to when the phone is normally opened.

no no, not so detailed, it would be fine, I think it is very easy to do, to add an icon eg charge and when you click on that icon to start charging the phone if a person is in one of the vehicles, as for the powerbank make a virtual item and if you have that item in the inventory, you can also charge the phone, what you wrote with the cable and all the checks, I understand that it is harder to perform, but these are simple variants that could be performed. I hope they understand me :)

**Comment by Marc85BPG** [comment]
i guess all you need is a simulated power from 0%(=phone turns off) to 100%
Then you need an item like a "powerbank" or a loadingCable(which you can use in vehicles to load the phone)

i know a person, who realised it with something like the "fuel Level" Cars ...
If fuel empty = car turns off

.........
Of course, its safe not easy as it sounds, but you really dont need any sort of locations, models etc.

"just" the function - and 1-maybe two items.

**Comment by RockySouthpaw** [comment]
> i guess all you need is a simulated power from 0%(=phone turns off) to 100% Then you need an item like a "powerbank" or a loadingCable(which you can use in vehicles to load the phone)
> 
> i know a person, who realised it with something like the "fuel Level" Cars ... If fuel empty = car turns off
> 
> ......... Of course, its safe not easy as it sounds, but you really dont need any sort of locations, models etc.
> 
> "just" the function - and 1-maybe two items.

For a proper implementation? Yes. For a simple copy and paste resource? No.

**Comment by Marc85BPG** [comment]
> For a proper implementation? Yes. For a simple copy and paste resource? No.

Okay we all know, theres always a proper way, and the "quick and (very) dirty way, 
all what i wanna say is, there`s always a "semi" simulation, and that can be a veery nice feature of that phone.

As an Example:
Via config you can say "okay after 60 min theres a decrease of XX% of power.  -> Easy way.
The more you are talking, in twitter, makeing photos, be on marketPlace etc. the more Power decreases -> Hard Way.

But i think an "easy" way is proper enough,

ps:dont get me wrong please. the "easy" way is definetly hard enough when you will do it correctly. Of course

**Comment by RockySouthpaw** [comment]
If we have the right event handlers we could probably just implement a simple export within the phone to set the battery icon imo. 

Like icon color and the fill level. And let outside resources do what they want. Can log the duration of phone open and decrease battery, can log when someone calls later, log when text ect

**Comment by Marc85BPG** [comment]
i can take a look for a resource in altV which is wrote in C#
but i think thats not really helpful here for fiveM ?

All what i can say is , they had oriented to the cars (motor=power -true-false) (fuel 0-100 / if fuel 0 then ..) 
and there was a powerbank which contains ... ya maybe fuel ? Anyway, theres only show % so ya....


i believe its a hard challenge, and the phone is great as its is, like it way more than gcphone etc.
i just personally wish that feature.
