### ISSUE TITLE
Bug: <short description>

### ISSUE THREAD

**Issue by AndrewMNGRP** [project-error/npwd#498]
### Developement Issue

Unsure

### Phone Version

1.04

### Issue Description

[ c-scripting-core] Creating script environments for oxmysql
[ citizen-server-impl] Started resource oxmysql
[ c-scripting-core] Creating script environments for pe-core
[ citizen-server-impl] Started resource pe-core
[ c-scripting-core] Creating script environments for screenshot-basic
[ citizen-server-impl] Started resource screenshot-basic
[ c-scripting-core] Creating script environments for npwd
[ script:npwd] [NPWD] [marketplace] [debug]: Marketplace service started
[ script:npwd] [NPWD] [player] [debug]: Player Service started
[ script:npwd] [NPWD] [calls] [debug]: Call service started
[ script:npwd] [NPWD] [notes] [debug]: Notes service started
[ script:npwd] [NPWD] [contact] [debug]: Contacts service started
[ script:npwd] [NPWD] [photo] [debug]: Photo service started
[ script:npwd] [NPWD] [messages] [debug]: Messages service started
[ script:npwd] [NPWD] [twitter] [debug]: Twitter service started
[ script:npwd] [NPWD] [match] [debug]: Match service started
[ citizen-server-impl] Started resource npwd

[ script:npwd] [NPWD] [player] [info]: Started loading for [X-1] A. Merrifield (3)
[ script:npwd] Error: Unhandled promise failure: Error: Unknown column 'user_identifier' in 'where clause'
[ script:npwd] at l.query (@npwd/resources/dist/server/21a52c84805197a6caf4.server.js:16:54662)
[ script:npwd] at Object._rawExec (@npwd/resources/dist/server/21a52c84805197a6caf4.server.js:16:36540)
[ script:npwd] at @npwd/resources/dist/server/21a52c84805197a6caf4.server.js:24:19714
[ script:npwd] at Generator.next (&lt;anonymous&gt;)
[ script:npwd] at @npwd/resources/dist/server/21a52c84805197a6caf4.server.js:24:19245
[ script:npwd] at new Promise (&lt;anonymous&gt;)
[ script:npwd] at r (@npwd/resources/dist/server/21a52c84805197a6caf4.server.js:24:18990)
[ script:npwd] at t.findOrGeneratePhoneNumber (@npwd/resources/dist/server/21a52c84805197a6caf4.server.js:24:19510)
[ script:npwd] at Object.&lt;anonymous&gt; (@npwd/resources/dist/server/21a52c84805197a6caf4.server.js:16:31717)
[ script:npwd] at Generator.next (&lt;anonymous&gt;)
[ script:pe-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1016: bad argument #1 to 'format' (number expected, got nil)
[ script:pe-core] &gt; handler (@pe-core/server/sv_main.lua:48)
[ script:pe-core] &gt; ref (@pe-core/server/sv_main.lua:37)
[ script:pe-core] &gt; query_default (@oxmysql/dist/server/build.js:16108)
[ script:pe-core] &gt; processTicksAndRejections (node:internal/process/task_queues:96)
[ script:pe-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1016: bad argument #1 to 'format' (number expected, got nil)
[ script:pe-core] &gt; handler (@pe-core/server/sv_main.lua:48)
[ script:pe-core] &gt; ref (@pe-core/server/sv_main.lua:29)
[ script:pe-core] &gt; query_default (@oxmysql/dist/server/build.js:16108)
[ script:pe-core] &gt; processTicksAndRejections (node:internal/process/task_queues:96)

### Issue Reproduction

See error in Issue Description, using pe-core latest version, mysql-async, npwd and oxmysql

**Comment by AndrewMNGRP** [comment]
Closing as this has been fixed

**Comment by CashTrouble** [comment]
how did you fix it?
