### ISSUE TITLE
Bug: Calls are not working properly

### ISSUE THREAD

**Issue by AndrewMNGRP** [project-error/npwd#500]
### Developement Issue

Unsure

### Phone Version

1.0.4

### Issue Description

When attempting to accept a phone call, the "accept" button on the receiver's side does not function. The following was in the server console: 
`[ script:npwd] [NPWD] [events] [silly]: netPromise &gt; npwd:beginCall &gt; RequestObj
[ script:npwd] [NPWD] [events] [silly]: { source: 1, data: { receiverNumber: '9728075990' } }
[ script:npwd] [NPWD] [calls] [debug]: Receiving Identifier: license:48dade34c17cf039cf7800b84f8b7441c92068ce
[ script:npwd] [NPWD] [calls] [debug]: Receiving source: 4
[ script:npwd] [NPWD] [calls] [debug]: Call obj set with key 9728075991, value:
[ script:npwd] [NPWD] [calls] [debug]: {
[ script:npwd] identifier: '9b3e76d6-9ef1-4636-a45b-c2f3daa1725d',
[ script:npwd] transmitter: '9728075991',
[ script:npwd] transmitterSource: 1,
[ script:npwd] receiver: '9728075990',
[ script:npwd] receiverSource: 4,
[ script:npwd] start: '1641491730',
[ script:npwd] is_accepted: false
[ script:npwd] }
[ script:npwd] [NPWD] [events] [silly]: Response Promise Event npwd:beginCall:3f6f5254-53d2-4235-be97-01a8ea61d3ac (10.554707ms), Data &gt;&gt;
[ script:npwd] [NPWD] [events] [silly]: {
[ script:npwd] status: 'ok',
[ script:npwd] data: {
[ script:npwd] is_accepted: false,
[ script:npwd] transmitter: '9728075991',
[ script:npwd] receiver: '9728075990',
[ script:npwd] isTransmitter: true
[ script:npwd] }
[ script:npwd] }
[ script:npwd] [NPWD] [events] [silly]: netPromise &gt; npwd:endCall &gt; RequestObj
[ script:npwd] [NPWD] [events] [silly]: {
[ script:npwd] source: 1,
[ script:npwd] data: { isTransmitter: true, transmitterNumber: '9728075991' }
[ script:npwd] }
[ script:npwd] [NPWD] [events] [silly]: Response Promise Event npwd:endCall:1d1466b7-e26c-4490-944b-c4292ed11e34 (2.033861ms), Data &gt;&gt;
[ script:npwd] [NPWD] [events] [silly]: { status: 'ok' }
[ script:npwd] [NPWD] [events] [silly]: netPromise &gt; npwd:createMessageGroup &gt; RequestObj
[ script:npwd] [NPWD] [events] [silly]: { source: 5, data: { targetNumber: '9728075991' } }
[ script:npwd] [NPWD] [events] [silly]: Response Promise Event npwd:createMessageGroup:aa768987-8651-4dd0-af1c-8055fc84aca1 (10.372188ms), Data &gt;&gt;
[ script:npwd] [NPWD] [events] [silly]: {
[ script:npwd] status: 'ok',
[ script:npwd] data: {
[ script:npwd] conversation_id: '5412059560+9728075991',
[ script:npwd] phoneNumber: '9728075991'
[ script:npwd] }
[ script:npwd] }
[ script:npwd] [NPWD] [calls] [error]: Error occured in accept call event (9728075991), Error: Cannot set properties of undefined (setting 'is_accepted')
[ script:npwd] [NPWD] [calls] [error]: Error occured in accept call event (9728075991), Error: Cannot set properties of undefined (setting 'is_accepted')
[ script:npwd] [NPWD] [calls] [error]: Error occured in accept call event (9728075991), Error: Cannot set properties of undefined (setting 'is_accepted')
[ script:npwd] [NPWD] [calls] [error]: Error occured in accept call event (9728075991), Error: Cannot set properties of undefined (setting 'is_accepted')
[ script:npwd] [NPWD] [calls] [error]: Error occured in accept call event (9728075991), Error: Cannot set properties of undefined (setting 'is_accepted')`

Or, this will occur:
`[ script:npwd] [NPWD] [calls] [debug]: Call with key 5412059560 was updated to be accepted
[ script:npwd] [NPWD] [debug]: {
[ script:npwd] identifier: '6c7d0d15-e3cf-4871-b01b-ed8389ed3408',
[ script:npwd] transmitter: '5412059560',
[ script:npwd] transmitterSource: 2,
[ script:npwd] receiver: '9728075990',
[ script:npwd] receiverSource: 1,
[ script:npwd] start: '1641494347',
[ script:npwd] is_accepted: true
[ script:npwd] }
[ script:npwd] [NPWD] [calls] [debug]: Call with key 5412059560 was updated to be accepted
[ script:npwd] [NPWD] [debug]: {
[ script:npwd] identifier: '6c7d0d15-e3cf-4871-b01b-ed8389ed3408',
[ script:npwd] transmitter: '5412059560',
[ script:npwd] transmitterSource: 2,
[ script:npwd] receiver: '9728075990',
[ script:npwd] receiverSource: 1,
[ script:npwd] start: '1641494347',
[ script:npwd] is_accepted: true
[ script:npwd] }
[ script:npwd] [NPWD] [events] [silly]: netPromise &gt; npwd:endCall &gt; RequestObj
[ script:npwd] [NPWD] [events] [silly]: {
[ script:npwd] source: 2,
[ script:npwd] data: { isTransmitter: true, transmitterNumber: '5412059560' }
[ script:npwd] }
[ script:npwd] [NPWD] [calls] [error]: Call with transmitter number 5412059560 does not exist in current calls map!
[ script:npwd] [NPWD] [events] [silly]: Response Promise Event npwd:endCall:5ce3439d-7cee-4042-9d86-2ac0c53d2c06 (2.436251ms), Data &gt;&gt;
[ script:npwd] [NPWD] [events] [silly]: { status: 'error', errorMsg: 'DOES_NOT_EXIST' }
[ script:npwd] [NPWD] [calls] [error]: Call with transmitter number 5412059560 does not exist in current calls map!`

### Issue Reproduction

1. Dialing a number/selecting a contact on the transmitter's end
2. Attempting to accept on the receiver's end but the "Accept" button not working properly.
3. The receiver attempting to dismiss the call but the ringtone keeps ringing after trying to decline the call

**Comment by RockySouthpaw** [comment]
Are you using pma-voice

**Comment by AndrewMNGRP** [comment]
Yes, we have pma-voice installed

**Comment by AndrewMNGRP** [comment]
Re-downloading pma-voice 6.2.5 made it work properly. Closing out this issue, Thanks for your assistance!
