### ISSUE TITLE
Enhancement(Core): Handle initial database insertion for new users

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#502]
### Application

Other

### Dependency

No

### Feature Description

The goal here is to abstract the need of [pe-core](https://github.com/project-error/pe-core) as this was only made as a resolution for those using menu based servers in the absence of npwd handling it. 

While this is a 'ok' solution, it's not the best as it adds oxmysql as a depency. On resource start and framework integration is set to false, we should simply select the playerTable from the config and create it if it doesn't exist including the identifier column and phone number columns. Subsequently, wed need to query when a player joins the server and insert them into it if they don't exist. We can use the config for this as well.

```json
 "identifierColumn": "identifier",
    "identifierType": "license",
```

Most menu based servers do have a database of some sort so it's not really a big deal to force them to use [pe-core](https://github.com/project-error/pe-core), it could be improved.

**Comment by itschip** [comment]
We probably need some additonal config options here. Any suggestions @RockySouthpaw ?

**Comment by c-wide** [comment]
> We probably need some additonal config options here. Any suggestions @RockySouthpaw ?

I'm thinking about 'generateDbSchema' as a boolean flag in the database section of the config.json but that doesnt really indicate that useResourceIntegration has to be set to false. Ideas?
