### ISSUE TITLE
Bug: Twitter not reloading correctly on character switch

### ISSUE THREAD

**Issue by Quostix** [project-error/npwd#506]
### Developement Issue

No

### Phone Version

1.0.4

### Issue Description

Upon switching characters, Twitter doesn't seem to function correctly afterwards.

1) First issue is that the account that appears in the account section is the first one you loaded and not the character you switched to.
[example]
I first load into the server as A, and then switch to character B. When I open Twitter and check the profile, it says character A when it should be character B.
[/example]

2) When Tweeting AFTER switching character, the Tweet sends, however, you cannot delete the Tweet as it's the report option and not the delete option (implying I am not the creator of the Tweet?)
[example]
After switching from player A to player B, I write a Tweet, player B sends the Tweet but I do not have the option to delete it, only report.
[/example]

3) When switching from player A, to player B, and then back to player A again we recieve a fatal error and are requested to reload NUI with the error: Cannot read property 'twitter' of null

4) Reloading doesn't appear to do anything, however, NUI focus is originally lost and regained by pressing F1 and then reload.

### Issue Reproduction

1. Switch character using the unload and load player exports
2. Check Twitter profile
3. Tweet
4. Switch characters again [fatal error]

### Evidence

[         script:npwd] [NPWD] [info]: Sucessfully started
[         script:npwd] [NPWD] [player] [debug]: Find user for number generation data >
[         script:npwd] [NPWD] [player] [debug]: [ { phone_number: '329-666-3851' } ]
[         script:npwd] [NPWD] [player] [info]: New NPWD Player added through event (3) (char2:110000101baeba1)
[         script:npwd] [NPWD] [player] [debug]: {
[         script:npwd]   source: 3,
[         script:npwd]   _identifier: 'char2:110000101baeba1',
[         script:npwd]   _phoneNumber: '329-666-3851',
[         script:npwd]   username: 'Quostix',
[         script:npwd]   _firstname: 'Harold',
[         script:npwd]   _lastname: 'Cartwright II'
[         script:npwd] }
[         script:npwd] [NPWD] [events] [silly]: netPromise > npwd:getOrCreateTwitterProfile > RequestObj
[         script:npwd] [NPWD] [events] [silly]: { source: 3, data: null }
[         script:npwd] [NPWD] [events] [silly]: netPromise > npwd:fetchMessageGroups > RequestObj
[         script:npwd] [NPWD] [events] [silly]: { source: 3, data: null }
[         script:npwd] [NPWD] [events] [silly]: Response Promise Event npwd:getOrCreateTwitterProfile:6081c346-5961-433a-ba01-b9875d5c3f50 (14.310767ms), Data >>
[         script:npwd] [NPWD] [events] [silly]: {
[         script:npwd]   status: 'ok',
[         script:npwd]   data: {
[         script:npwd]     id: 1,
[         script:npwd]     profile_name: 'Harold_CartwrightII',
[         script:npwd]     identifier: 'char2:110000101baeba1',
[         script:npwd]     avatar_url: 'https://i.file.glass/QrEvq.png',
[         script:npwd]     bio: null,
[         script:npwd]     location: null,
[         script:npwd]     job: null,
[         script:npwd]     createdAt: 2022-01-02T20:02:57.000Z,
[         script:npwd]     updatedAt: 2022-01-02T20:02:57.000Z
[         script:npwd]   }
[         script:npwd] }
[         script:npwd] [NPWD] [events] [silly]: Response Promise Event npwd:fetchMessageGroups:49e1be96-9754-4f5a-8971-b4f7581ad00e (17.351111ms), Data >>
[         script:npwd] [NPWD] [events] [silly]: { status: 'ok', data: [] }

-- The below is the console when switching characters

[      script:quostix] [quostix] [saved] [switching character] char2:110000101baeba1
[         script:npwd] [NPWD] [player] [debug]: Received unloadPlayer event for 3
[         script:npwd] [NPWD] [player] [info]: Unloaded NPWD Player, source: (3)
[         script:npwd] [NPWD] [player] [debug]: Find user for number generation data >
[         script:npwd] [NPWD] [player] [debug]: [ { phone_number: '877-824-7197' } ]
[         script:npwd] [NPWD] [player] [info]: New NPWD Player added through event (3) (char1:110000101baeba1)
[         script:npwd] [NPWD] [player] [debug]: {
[         script:npwd]   source: 3,
[         script:npwd]   _identifier: 'char1:110000101baeba1',
[         script:npwd]   _phoneNumber: '877-824-7197',
[         script:npwd]   username: 'Quostix',
[         script:npwd]   _firstname: 'Dwayne',
[         script:npwd]   _lastname: 'Stix'
[         script:npwd] }
[         script:npwd] [NPWD] [events] [silly]: netPromise > npwd:fetchAllListings > RequestObj
[         script:npwd] [NPWD] [events] [silly]: { source: 3, data: null }
[         script:npwd] [NPWD] [events] [silly]: Response Promise Event npwd:fetchAllListings:b2282089-f7cc-45c5-9fc7-26db8495fcf0 (15.250202ms), Data >>
[         script:npwd] [NPWD] [events] [silly]: { data: [], status: 'ok' }

-- Switching back to original character

[      script:quostix] [quostix] [saved] [switching character] char1:110000101baeba1
[         script:npwd] [NPWD] [player] [debug]: Received unloadPlayer event for 3
[         script:npwd] [NPWD] [player] [info]: Unloaded NPWD Player, source: (3)

-- And then we have the fatal error so nothing happens.

**Comment by TasoOneAsia** [comment]
Related to #476 and #488
