### ISSUE TITLE
Enhancement: Add more translations

### ISSUE THREAD

**Issue by AvarianKnight** [project-error/npwd#507]
### Application

Other

### Dependency

No

### Feature Description

Currently some applications lack a lot of proper error messages (like twitter)

This is probably something I'll try to tacke later, but its outside the scope of my current PR.

**Comment by RockySouthpaw** [comment]
Will compile a list of apps/text that need translation options later today.

**Comment by itschip** [comment]
> Will compile a list of apps/text that need translation options later today.

@RockySouthpaw Did you do such?

**Comment by RockySouthpaw** [comment]
> > Will compile a list of apps/text that need translation options later today.
> 
> @RockySouthpaw Did you do such?

No did you

**Comment by itschip** [comment]
@RockySouthpaw No, did u?

**Comment by RockySouthpaw** [comment]
> @RockySouthpaw No, did u?

No, did you?

**Comment by itschip** [comment]
Reopen if something major is missing.
