### ISSUE TITLE
Bug: Schema fails to load on newer build

### ISSUE THREAD

**Issue by AvarianKnight** [project-error/npwd#508]
### Developement Issue

Yes

### Phone Version

Development

### Issue Description

Local Storage fails to load JSON on the development branch.

### Issue Reproduction

Not much reproduction, the storage is corrupted.

Changing NPWD_STORAGE_KEY to npwd_settings_1 fixes the issue (although resetting the state)

### Evidence

![](https://i.dillonskaggs.dev/oIdRHYwM)

**Comment by itschip** [comment]
Resolved. Caused by a fetch never receiving a response, and a missing file in the client script.
