### ISSUE TITLE
Enhancement: Only play tweet sound on mention

### ISSUE THREAD

**Issue by AvarianKnight** [project-error/npwd#509]
### Application

Twitter

### Dependency

No

### Feature Description

Only play the tweet sound when a player specifically mentions the said player, or ahve some option to allow getting the sound notification for each tweet.

On most servers this sound is going to just be spamming and its very annoying

**Comment by RockySouthpaw** [comment]
Correct me if I’m wrong here, but do we not already have this?

**Comment by AvarianKnight** [comment]
> Correct me if I’m wrong here, but do we not already have this? 

Only option currently is to flat out disable notifications entirely

**Comment by itschip** [comment]
I can add the functionality, but I probably won't integrate this before we get the new notifications merged.

**Comment by RockySouthpaw** [comment]
![image](https://user-images.githubusercontent.com/55056068/148668950-2ba31c07-377e-4554-9335-d438db500529.png)
we already have this setting?

**Comment by RockySouthpaw** [comment]
So for reference, currently what happens is we play a sound for **every** tweet regardless if the notification is set to only @ mentions.

**Comment by RockySouthpaw** [comment]
Fixed
