### ISSUE TITLE
Enhancement(Versioning): Notify weirdos of new versions.

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#513]
### Application

Other

### Dependency

No

### Feature Description

Simply notify people that there is a new version of npwd so the xd-rp-servers can download it.

**Comment by TasoOneAsia** [comment]
If there are any interested parties for this issue, might be helpful to reference this. This is far down on my road of things I need to do, but a simple script literally just implements that.

https://gist.github.com/TasoOneAsia/8a915a357713c0f84a1b1d00cdea8020
