### ISSUE TITLE
Here not embedded with link in docs.

### ISSUE THREAD

**Issue by R3site** [project-error/npwd#519]
### Developement Issue

Unsure

### Phone Version

1.0.4 master

### Issue Description

In the NPWD docs if you go from Getting Started > Installation > General Configuration > toggleKey the "here" for a list of available keys isn't actually embedded with any sort of link.

### Issue Reproduction

N/A

### Evidence

![unknown](https://user-images.githubusercontent.com/61720260/148703064-81ad078d-8a5d-4716-8d1f-baf312982310.png)

**Comment by itschip** [comment]
@R3site Create an issue here https://github.com/project-error/projecterror.dev
