### ISSUE TITLE
Block Button

### ISSUE THREAD

**Issue by R3site** [project-error/npwd#521]
### Application

Other

### Dependency

No

### Feature Description

The ability to block contacts from contacting you via messenger and dilaer. Aswell as the ability to block twitter handles from being able to mention you.

### References

N/A

**Comment by RockySouthpaw** [comment]
We really would need to think of a way to make this user friendly. Adjusting this across every app would be annoying I think.

**Comment by R3site** [comment]
Agreed, personally I do not see why someone would block someone on twitter and not on their phone. Even if its just blocking the whole identifier identifier from being able to contact you when you click the block button. Then you could just have one function that checks if one identifier has the other identifier blocked and if it does it just returns and sends a notification that says something like "The person(s) you are trying to get in contact with have you blocked."  Just for simplicity of the code.

**Comment by R3site** [comment]
Ahh,another concept would be that the person can try to contact them; but the message never actually go's through on the client. That way you could just make it check if the user contacting them is blocked in whatever client event is triggered from the server, when one client tries to contact the other.
