### ISSUE TITLE
Contact Doesnt Show For Message Notification

### ISSUE THREAD

**Issue by R3site** [project-error/npwd#522]
### Developement Issue

Unsure

### Phone Version

1.0.4

### Issue Description

Whenever you receive message notifications regardless on if they're contact or not, and even if your client has seen that number as a contact.; the message notification will always have the phone number instead of the contact name.

### Issue Reproduction

1. Create a contact with a phone number 
2. Close the Phone 
3. Get the person with that Phone Number to message you in messenger

### Evidence

![image](https://user-images.githubusercontent.com/61720260/148724569-6af9a6a9-e733-43f3-83ed-46346d586643.png)

![image](https://user-images.githubusercontent.com/61720260/148724595-3121804d-f0aa-480b-80f2-5031883cb4c0.png)

**Comment by itschip** [comment]
Should be fixed in bbda65b16a7eb0c33028f80665f79e6e06116e40

**Comment by R3site** [comment]
Same problem with calling.

**Comment by RockySouthpaw** [comment]
> Same problem with calling.
Can you try latest release?

**Comment by R3site** [comment]
I have tried with latest release the messages is fixed, but calling is still broken.

**Comment by RockySouthpaw** [comment]
Open a seperate Issue for calling please :) @R3site
