### ISSUE TITLE
Group Chats in Messenger 

### ISSUE THREAD

**Issue by R3site** [project-error/npwd#523]
### Application

Messages

### Dependency

No

### Feature Description

You can have a group chat with multiple people within messenger instead of single direct messages.  It would even be better if there was an info tab in which you can see all the numbers in the gc and make contacts from there all though this isn't needed.

### References

N/A

**Comment by RockySouthpaw** [comment]
We actually had this functionality before but it was abstracted when messages was refactored. It’s already on the list to add back at some point :) so closing this.
