### ISSUE TITLE
Bug(DisabledPhone): Disabled phone doesn't prevent calls & notifications

### ISSUE THREAD

**Issue by dolutattoo** [project-error/npwd#527]
### Developement Issue

No

### Phone Version

origin/master

### Issue Description

Here something that currently block me to use the phone on my server:
If you set `PhoneAsItem.enabled` to true, and don't have any phone item in your inventory (tested on ESX), it will only prevent to open the phone, but you'll still receive tweets notifications, calls, etc.
I also tested to disable `twitter.showNotifications` to prevent tweets notifications but they are still poping

### Issue Reproduction

1. Set  `PhoneAsItem.enabled` to true in config.json
2. Make sure you don't have any phone in your inventory
3. Ask to another player to send a tweet, or to call you.
4. You'll receive everything

### Project Error Notes

This is actually an issue with `exports.npwd:setPhoneDisabled(true)` not working as intended. As when this is set, no notifications should go through. This would need to be set to true should the player not have the item unless we want to call the item check everytime we trigger a notification, which of course we don't.

**Comment by RockySouthpaw** [comment]
Have you tried using the export to disable the phone when they don't have the item?

`exports.npwd:setPhoneDisabled(true)`
This should prevent notifications hopefully

**Comment by dolutattoo** [comment]
I just tried but no, I still have tweets & SMS notifications.
I made a command to `print(exports.npwd:isPhoneDisabled())`, so I'm sure that phone is disabled when I receive notifications

**Comment by RockySouthpaw** [comment]
Okay so this is actually a bug with disabled phone not actually disabling notifications. Will change this to a bug and alter the issue.

**Comment by dolutattoo** [comment]
> Edit: I guess youd also need to handle when the item is removed and setting this state as well.
Yeah that's what I prepared :)

**Comment by itschip** [comment]
@dolutattoo @RockySouthpaw Should be fixed in develop.

**Comment by RockySouthpaw** [comment]
Fixed ish, the issue will still exist with notifications which is why I left comments on the PR prior to you merging it kek @itschip

**Comment by itschip** [comment]
> Fixed ish, the issue will still exist with notifications which is why I left comments on the PR prior to you merging it kek @itschip

I should've fixed notis.

**Comment by dolutattoo** [comment]
Yes it's fixed, amazing ! :)
Idk if this is linked or not but the phone is the same when swapping to another character (overextended+esx_multicharacter)

**Comment by itschip** [comment]
@dolutattoo See https://github.com/project-error/npwd/pull/488
