### ISSUE TITLE
Enhancement: Video Call and Video Clips

### ISSUE THREAD

**Issue by anes66** [project-error/npwd#528]
### Application

Camera

### Dependency

Yes

### Feature Description

Hello guys its me again i have a great idea if you can that would be nice to make a app like facetime or somthing like that so we can make video clips and live facetime with some other users i will provide here what i found HTML Render i hope it will help

[Html Render](https://forum.cfx.re/t/render-game-to-html-canvas-video-call-video-record/2823923)

**Comment by RockySouthpaw** [comment]
The thing with doing any sort of camera related stuff is the native that we currently use, and other people as well, prevent movement. So you couldn’t move while doing this at all.

Which is pretty clunky if you wanted to vLog or just move into a better position. That’s why all of these videos have people standing still.

**Comment by anes66** [comment]
> 

maybe you right about vlog but for evidence or like crime it would be very nice :)

**Comment by RockySouthpaw** [comment]
Idk how we already have camera functionality. Just screen record and send as a streamable or upload to discord. Then upload external link to twitter or whenever. Ez

**Comment by MJRamon** [comment]
> Idk how we already have camera functionality. Just screen record and send as a streamable or upload to discord. Then upload external link to twitter or whenever. Ez

Or talk in Discord and pretend it's a phone call, or send Discord PM and pretend it's SMS :) Actual profit here is an immersive real-time video chat, not the final result.Even if someone has to stand still - it's a little trade-off.

**Comment by RockySouthpaw** [comment]
Have you actually tried to use the camera within NPWD? It’s absurdly clunky. A few feet too far from where you want to be? Sucks to be you. Gotta re open it and go through that whole crap again.

I can’t image this feature even being liked in the current state of camera functionality so it’s something that would have to wait until that’s re designed.
