### ISSUE TITLE
Streamer Mode Blocking Phone Numbers

### ISSUE THREAD

**Issue by R3site** [project-error/npwd#529]
### Application

Other

### Dependency

No

### Feature Description

It would be helpful if streamer mode blocked phone numbers in messenger, settings, contacts, and in dialer. Just so that you're not leaking phone numbers on stream.

**Comment by R3site** [comment]
Numbers arnet targetted THAT often. However, they have been for me; and imagine if servers like Nopixel or Twitch RP start using the phone and then a big streamer is contacting another streamer and their number in game gets leaked. Then the owner or whoever manages the dbs has to go through and change it.

**Comment by frazz1234** [comment]
That's metagaming just ban people doing  that

**Comment by R3site** [comment]
> That's metagaming just ban people doing that

You are right it is metagaming, but functionality that stops it from happening > server owners being frustrated when their million+ sub streamer in their server leaves bc hundreds of trolls start spamming their number in server.
