### ISSUE TITLE
Bug: NUI Fatal error while received a new SMS and want open it

### ISSUE THREAD

**Issue by Deniel00** [project-error/npwd#534]
### Developement Issue

No

### Phone Version

v1.0.5

### Issue Description

NUI Fatal error while get a new sms and want open it

more info:
Fivem updatechannel: release
Fivem dlc The Contract (2545)

### Issue Reproduction

1. Open phone
2. Wait while receive a new Message
3. Go to Messages App
4. And click on new Message

### Evidence

![kép](https://user-images.githubusercontent.com/12788940/149525146-35b56984-c35d-4d55-b898-8f06b79d7553.png)

**Comment by dustinslane** [comment]
Are you using a framework where the phone numbers are stored in the database as an integer? I had this issue as well until I changed the phone number column to varchar.

**Comment by Deniel00** [comment]
Hm, well in db stored as INT.
Checked with a VARCHAR and work well. Thanks @dustinslane
