### ISSUE TITLE
Bug: Messages app restarts after receiving twitter notification

### ISSUE THREAD

**Issue by dustinslane** [project-error/npwd#537]
### Developement Issue

No

### Phone Version

1.0.5

### Issue Description

When I am in the messages app, I get a twitter notification on my phone. The messages app redraws itself and I have to start over with typing or reading.

### Issue Reproduction

1. Have 2 people on the server
2. Go to messages app
3. Enter a conversation with anybody
4. Have the other player create a twitter notification to your phone
5. This bug happens

### Evidence

https://streamable.com/zrfna3

**Comment by RockySouthpaw** [comment]
Have you tried with notifications off? Wonder if it would still do it or if it’s purely related to notifications

**Comment by dustinslane** [comment]
I have; it does not happen when notifications are off

**Comment by RockySouthpaw** [comment]
Cool thank you for the information :)

**Comment by dustinslane** [comment]
This seems to be fixed, we are testing 1.1.1
