### ISSUE TITLE
Bug: Phone bugs out when calling someone that is offline

### ISSUE THREAD

**Issue by Dakobra** [project-error/npwd#549]
### Developement Issue

Unsure

### Phone Version

1.0

### Issue Description

Calling a player that is offline bugs the phone out and locks the player in the "calling" animation.

### Issue Reproduction

1. Open phone
2. Call someone offline
3. End call
4. Bug happens
5. Cant get out of "calling" animation

**Comment by itschip** [comment]
Do you mean version `1.1.0` or `1.0.0`?

**Comment by kunaiknife452** [comment]
This exact bug is occurring consistently with the steps mentioned for our server on version 1.1.0.

**Comment by itschip** [comment]
Unable to recreate in develop, with or without a number being vaild.
