### ISSUE TITLE
Bug(Calling): Dialtone is recreated

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#558]
### Developement Issue

No

### Phone Version

Latest master

### Issue Description

While waiting on a call to be accepted, closing he phone or clicking the notification header will recreate the dialtone.

### Issue Reproduction

1. Start a call
2. Close phone
3. Open Phone
Sound recreates.

- Start a call
-  Click notification header
- Close notification.
Sound recreates.

### Evidence

https://discord.com/channels/791854454760013827/791854455468458042/931781378083803177

**Comment by RockySouthpaw** [comment]
@TasoOneAsia

**Comment by itschip** [comment]
@TasoOneAsia

**Comment by RockySouthpaw** [comment]
> Will be taken a look at later today. Seems to be fun rerender cascade, probably will find a couple sources of rerender shenanigans on the way.

Must be the longest day.

**Comment by itschip** [comment]
Fixed in https://github.com/project-error/npwd/commit/8d0992a680f049c7d5d3693a4fa5409b78646b18
