### ISSUE TITLE
Bug: <Changing toggleKey not working>

### ISSUE THREAD

**Issue by GoldenGramsTTV** [project-error/npwd#561]
### Developement Issue

No

### Phone Version

1.1.0

### Issue Description

I opened resources > npwd > config.json

Changed the "toggleKey" from f1 to "M" due to the qb-radial menu using the f1 key. After saving file and restarting resource, f1 still opened my phone. Double checked the file, restarted the entire server, still menu opened using F1. I tried changing the key from M to O and F1 still opened the phone and O did nothing.

### Issue Reproduction

1. Go to resources > npwd > config.json
2. Open config.json
3. Find 
  },
  "general": {
    "useResourceIntegration": true,
    "toggleKey": "f1",
    "toggleCommand": "phone"
4. Change "f1" to "O"
5. Save file
6. Restart server
7. Open FiveM
8. Hit "O" - No response.

### Evidence

![image](https://user-images.githubusercontent.com/98197236/150620763-af0c34dc-8cd0-4cae-a3cf-54356c4f32c0.png)

**Comment by BombayV** [comment]
Just do `unbind keyboard f1` in your f8 console and it should be working fine. For new users it will work fine,

**Comment by GoldenGramsTTV** [comment]
Ahh, thank you!

Also, is it normal for the f8 console menu to be getting spammed with script:npwd:nui messages?

**Comment by RockySouthpaw** [comment]
Yes it’s normal.

**Comment by GoldenGramsTTV** [comment]
Awesome. Thank you guys for being so quick to respond.

Probably asking some pretty noob questions but I've been teaching myself this stuff less than a week now xD

Amazing script by the way <3 thank you to everyone who pitched in!
