### ISSUE TITLE
Enhancement: <Cupple Idea>

### ISSUE THREAD

**Issue by frazz1234** [project-error/npwd#562]
### Application

Other

### Dependency

No

### Feature Description

 --  An easy way to change the browser  homepage to something personalize ! 
 -- Possibilty to change the Cell provider to a personnalize one ! 
--  Local File to change to change the language using in some application in the phone, not everything is translate! 
-- Possibility to use FaceTime!

**Comment by RockySouthpaw** [comment]
• You can. Just edit the source and build. 
- You can. Just edit the Config and build. https://github.com/project-error/npwd/blob/f244f01d83cc5a7d6c41763df30baa3d9d59f8f5/phone/src/config/default.json#L2
- Or you can pr a translation for what you want translated? There’s no reason to include a local file when we have 10+ translations. If something should have a translation and doesn’t then pr it.
- No.

**Comment by frazz1234** [comment]
Whats are the reason i cant acces to a normal website like the one of my server whit the phone ?

**Comment by RockySouthpaw** [comment]
> Whats are the reason i cant acces to a normal website like the one of my server whit the phone ?

Anything that blocks cross origin iframes doesn’t work unless you want to make a proxy for it. 

It’s a phone. Within a mod for a video game. Don’t expect it to be the next firefox or google chrome.

**Comment by RockySouthpaw** [comment]
That being said, most of your suggestions are already a thing if you take the time to read the docs and learn to build.

Improving our translations has been a thing to do but not high priority right now. FaceTiming others isn’t really in our scope right now ether.

**Comment by frazz1234** [comment]
Yes, i dint realise they are in the build.. if you chek the documentaiton nothing talk about this..! 

an other , could be nice if you add a kind of voice changer when we talk on the phone! 
A easy possibility to add ringtone and image whitout passing by the builder or what ever.. and easy possibility to change the icon too...

**Comment by RockySouthpaw** [comment]
If the document included every single thing you can edit with the source code I’d be writing the next Iliad.
