### ISSUE TITLE
Error when loading number

### ISSUE THREAD

**Issue by Quinten-Gelderland** [project-error/npwd#564]
[    c-scripting-core] Creating script environments for npwd
[         script:npwd] [NPWD] [marketplace] [debug]: Marketplace service started
[         script:npwd] [NPWD] [player] [debug]: Player Service started
[         script:npwd] [NPWD] [calls] [debug]: Call service started
[         script:npwd] [NPWD] [notes] [debug]: Notes service started
[         script:npwd] [NPWD] [contact] [debug]: Contacts service started
[         script:npwd] [NPWD] [photo] [debug]: Photo service started
[         script:npwd] [NPWD] [messages] [debug]: Messages service started
[         script:npwd] [NPWD] [twitter] [debug]: Twitter service started
[         script:npwd] [NPWD] [match] [debug]: Match service started
[ citizen-server-impl] Started resource npwd
[ citizen-server-impl] server thread hitch warning: timer interval of 151 milliseconds
[         script:npwd] [NPWD] [player] [info]: Started loading for GamenHaaDee (1)
[         script:npwd] [NPWD] [info]: Sucessfully started
[         script:npwd] [NPWD] [player] [debug]: Find user for number generation data >
[         script:npwd] [NPWD] [player] [debug]: []
[         script:npwd] Error: Unhandled promise failure: TypeError: Cannot read properties of undefined (reading 'phone_number')
[         script:npwd]     at @npwd/resources/dist/server.js:35243:30
[         script:npwd]     at Generator.next (<anonymous>)
[         script:npwd]     at fulfilled (@npwd/resources/dist/server.js:46:24)
[         script:npwd]     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Quinten-Gelderland** [comment]
[         script:npwd] SCRIPT ERROR in event `npwd:getCredentials': TypeError: Cannot read properties of null (reading 'getPhoneNumber')
[         script:npwd] > <unknown> (@npwd/resources/dist/server.js:38642)
[         script:npwd]

**Comment by RockySouthpaw** [comment]
Fill the issue out correctly.
