### ISSUE TITLE
Bug: <short description>

### ISSUE THREAD

**Issue by bohous04** [project-error/npwd#566]
### Developement Issue

Unsure

### Phone Version

1.1.0

### Issue Description

I cannot open phone

### Issue Reproduction

Restart npwd
it pops out

### Evidence

![image](https://user-images.githubusercontent.com/94115651/150677511-906fbb66-cd9e-42ca-a664-5a1f33f43a4d.png)

**Comment by YisusOnDev** [comment]
Tested with release and with master and no issues found.
