### ISSUE TITLE
Bug: Disabling an app and rebuilding causes NUI failure

### ISSUE THREAD

**Issue by TrAsKiN** [project-error/npwd#571]
### Developement Issue

Unsure

### Phone Version

master

### Issue Description

After commenting, to disable, one or more apps, a NUI error (`TypeError: Cannot read property 'icon' of null`) prevents the phone from displaying (but in the game, it's as if there is no problem).

When the apps are uncommented (and the phone rebuilt), it works fine.

### Issue Reproduction

- Comment one or more apps in the file `phone/src/os/apps/config/apps.tsx` (as shown in the doc)
- rebuild the phone
- restart the server
- launch the game
- open the phone

### Evidence

![image](https://user-images.githubusercontent.com/11407673/150771869-b0ae7d59-afdf-4a62-b328-3dba555744f2.png)

**Comment by itschip** [comment]
Hm, can you show me how you disable it? I'd like to see it.

**Comment by TrAsKiN** [comment]
I comment each app this way:
![image](https://user-images.githubusercontent.com/11407673/150777122-aa615a9b-e196-4057-9d5e-4206b67797f5.png)

**Comment by RockySouthpaw** [comment]
Seems right based off the docs. https://projecterror.dev/docs/npwd/dev/disable_apps/

**Comment by itschip** [comment]
@TrAsKiN You need to comment out the `useTwitterService` in `Phone.tsx`. I'll update the docs.

**Comment by TrAsKiN** [comment]
This works perfectly on the 1.1.1 branch.
