### ISSUE TITLE
Pma_voice

### ISSUE THREAD

**Issue by nassim121103** [project-error/npwd#572]
### Developement Issue

Unsure

### Phone Version

Last one

### Issue Description

hello to all I have a problem with pma_voice in my server I hear no player except when I call on the phone with npwd it works otherwise when I don't use the phone it doesn't work this is due to what please

### Issue Reproduction

I install it the phone respecting all the rules of the documentation the phone works well when I call my voice works when I talk to another player but when I hang up and talk normally it does not work

**Comment by itschip** [comment]
This has nothing to do with npwd.
