### ISSUE TITLE
Bug(Twitter): Old Twitter messages never get removed

### ISSUE THREAD

**Issue by AvarianKnight** [project-error/npwd#573]
Twitter messages never get removed from the UI, after so many new tweets the UI will begin to lag/lock up and then it freezes Nui :(

**Comment by AvarianKnight** [comment]
@TasoOneAsia @itschip

**Comment by RockySouthpaw** [comment]
Infinite scroll brr

**Comment by itschip** [comment]
@AvarianKnight is this still a thing in 1.1.7?

**Comment by itschip** [comment]
Closing this for now.
