### ISSUE TITLE
Bug: Message filter does not work for contact names

### ISSUE THREAD

**Issue by dustinslane** [project-error/npwd#574]
### Developement Issue

Yes

### Phone Version

1.1.0

### Issue Description

The phone filter does not work for contact names. It only works for phone numbers

### Issue Reproduction

1. Have some contacts 
2. Have some conversations. At least one from a contact
3. Send a message
4. Go back to message list
5. Search for their name
6. It does not come up with their conversation
7. Type in their phone number 
8. It does come up with their conversation

### Evidence

I think it is because the `display` is null so the regex always fails. This screenshot is a console.log from `messageConversations` in `filteredMessageConversations` in `state.ts` around line 44

![image](https://user-images.githubusercontent.com/7924312/151471219-92f606d2-c8a7-47d3-96bd-46d978390597.png)

**Comment by itschip** [comment]
@dustinslane I assume this is only after you have created a conversation. It should work.

**Comment by RockySouthpaw** [comment]
> @dustinslane I assume this is only after you have created a conversation. It should work.

Repro states they already have one

**Comment by dustinslane** [comment]
Did some more testing. It works when I just created the conversations. it stops working after I restart the server and log back in

**Comment by dustinslane** [comment]
F. Will investigate some more then and open a new one when needed
