### ISSUE TITLE
Enhancement: Marketplace notifications

### ISSUE THREAD

**Issue by dustinslane** [project-error/npwd#575]
### Application

Marketplace

### Dependency

No

### Feature Description

As a consumer, I would like to know when a new marketplace posting has been placed.
As a business owner, I would like my potential customers to know that my marketplace post is up.

Would like it to be similar to twitter notifications, complete with the ability to mute them.

**Comment by RockySouthpaw** [comment]
Seems like an oversight on our part, can see the appeal for this. 👍🏻

**Comment by itschip** [comment]
@dustinslane Added in 1f0d2971326450672b5d6004159b3453f0127c2f

**Comment by dustinslane** [comment]
Very nice!
