### ISSUE TITLE
Bug: Phone settings don't save

### ISSUE THREAD

**Issue by draobrehtom** [project-error/npwd#576]
### Developement Issue

Unsure

### Phone Version

1.1.1

### Issue Description

Phone settings don't save, have to turn off notification sounds and change the language everytime I join the server.

Server artifacts: 5181

### Issue Reproduction

1. Open settings and change the language of the phone;
2. `restart npwd`;
3. Open setting once again.

### Evidence

https://streamable.com/abyc6u

**Comment by itschip** [comment]
Is this latest master or the actual release 1.1.1?

**Comment by draobrehtom** [comment]
Actual release 1.1.1.

**Comment by TasoOneAsia** [comment]
Can confirm issue exists. Regression occurred in 925a269600dedc16806120fdabc18b85ca3b2d68. Fixed with f19b13ea65c6f6f5ef7cf39fe96bb973a0cdc766.
