### ISSUE TITLE
I've translated to Russian. Here's json file.

### ISSUE THREAD

**Issue by MJRamon** [project-error/npwd#578]
### Application

Other

### Dependency

No

### Feature Description

Here's ru.json locale.

Russian / **Русский**
[ru.zip](https://github.com/project-error/npwd/files/7967829/ru.zip)

**Comment by itschip** [comment]
Please create an Pull Request with these changes.

**Comment by MJRamon** [comment]
> Please create an Pull Request with these changes.

Sorry, cannot do it.
