### ISSUE TITLE
Bug: Console Error when trying to view matches on matchmaker app.

### ISSUE THREAD

**Issue by Mr-crazey** [project-error/npwd#580]
### Developement Issue

Unsure

### Phone Version

1.1

### Issue Description

When users attempt to view their matchmaker matches on the app, the matches page will appear to load indefinitely.  No errors appear on the users console.

On the server console the following error appears:
```
[         script:npwd] [NPWD] [match] [error]: Failed to retrieve matches, Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '='
```

### Issue Reproduction

1. Have to users match with each-other on matchmaker.
2. Have either user attempt to view their matches on the matchmaker app.
3. No errors appear in client console.
4. Above error appears in server console.

### Evidence

https://streamable.com/jclv6y

Server Console:
![image](https://user-images.githubusercontent.com/97853686/151888232-8dcfeca9-9ac2-4ca4-8c95-b47e1deb9464.png)

**Comment by TasoOneAsia** [comment]
Ensure that both your "users" table and the listings table have the same collation.
