### ISSUE TITLE
Bug: <short description>

### ISSUE THREAD

**Issue by nuageee** [project-error/npwd#581]
### Developement Issue

Unsure

### Phone Version

1.1.1

### Issue Description

I can't send message with the phone
Here is the error :
`[         script:npwd] [NPWD] [events] [silly]: { status: 'error', errorMsg: 'GENERIC_DB_ERROR' }
[         script:npwd] [NPWD] [messages] [error]: Failed to fetch messages groups, Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
[         script:npwd] [NPWD] [events] [silly]: Response Promise Event npwd:getContacts:ad1dfc41-bf83-47e0-b6c5-f008d893fd9a (13.846285ms), Data >>`

### Issue Reproduction

Go to 'Contact'
Click on 'message icon'
Click on 'send'
See error

**Comment by itschip** [comment]
@nuageee Take a look at #542
