### ISSUE TITLE
Bug: Cannot send messages to non-existent numbers

### ISSUE THREAD

**Issue by 0pax** [project-error/npwd#582]
### Developement Issue

Yes

### Phone Version

Master branch, newest update

### Issue Description

I cannot send a message to non-existent numbers, I'd like to use the onMessage export, but since the number doesn't exist it seems it won't let me send the number a message

### Issue Reproduction

1. Open the phone
2. Open the messages app
3. Create a new conversation with a non-existent number
4. Try to create/enter it
5. Error / result

### Evidence

https://cdn.discordapp.com/attachments/791854455468458040/938136756031733770/unknown.png

**Comment by itschip** [comment]
@0pax Can you send a screenshot of the full conversation row in the db table?

**Comment by 0pax** [comment]
@itschip https://cdn.upload.systems/uploads/xDDsMz7V.png This?

**Comment by itschip** [comment]
Do these conversations with '112' and '911' work?

**Comment by 0pax** [comment]
> Do these conversations with '112' and '911' work?

No, they dont

**Comment by RockySouthpaw** [comment]
@itschip You tested this when you pushed it to master right?

**Comment by itschip** [comment]
@RockySouthpaw Yes, worked when I tested. Ill look into it shortly.

**Comment by itschip** [comment]
@0pax can I close this?

**Comment by 0pax** [comment]
> @0pax can I close this?

Done @itschip
