### ISSUE TITLE
Enhancement: image zoom

### ISSUE THREAD

**Issue by MJRamon** [project-error/npwd#583]
### Application

Other

### Dependency

No

### Feature Description

Would be great to enlarge images/photos on click. Right now they are way too small.

**Comment by RockySouthpaw** [comment]
You can already do so for photos but I assume you mean within messages? In which case this already on the roadmap

**Comment by itschip** [comment]
Sounds like fun

**Comment by MJRamon** [comment]
> You can already do so for photos but I assume you mean within messages? In which case this already on the roadmap

Yes, in any app: messages, Twitter, etc.

**Comment by MJRamon** [comment]
> You can already do so for photos but I assume you mean within messages? In which case this already on the roadmap

Actually, you can't. Image stays inside phone and is still too small to see details. I am talking about showing image as big as possible on the screen.

**Comment by RockySouthpaw** [comment]
> > You can already do so for photos but I assume you mean within messages? In which case this already on the roadmap
> 
> Actually, you can't. Image stays inside phone and is still too small to see details. I am talking about showing image as big as possible on the screen.

It’s already as big as possible without stretching? If you’re talking about adjusting the image size to be essentially scaling to the entire monitor screen instead of phone then what is the point of viewing it on the phone? 

Just copy and paste the link into your browser? Why be fucking weird about it.

**Comment by MJRamon** [comment]
> > > You can already do so for photos but I assume you mean within messages? In which case this already on the roadmap
> > 
> > 
> > Actually, you can't. Image stays inside phone and is still too small to see details. I am talking about showing image as big as possible on the screen.
> 
> It’s already as big as possible without stretching? If you’re talking about adjusting the image size to be essentially scaling to the entire monitor screen instead of phone then what is the point of viewing it on the phone?
> 
> Just copy and paste the link into your browser? Why be fucking weird about it.

Cause in real life you can zoom into image and look at details, and here we are talking about gaming conventions that are making life harder.
Why should I copy link (and I can't, if it's in SMS or Twitter from other people), if we do need a way to zoom in without quitting the game? Isn't that the point to view it in the game?
Stop being fucking asshole.

**Comment by TasoOneAsia** [comment]
@itschip This should be fairly easy to implement and I can understand the desire. Me or you?

**Comment by TonybynMp4** [comment]
@itschip 🔫 make !

**Comment by TonybynMp4** [comment]
bad bot it already implemented

**Comment by itschip** [comment]
@TonybynMp4 does it work fine?

**Comment by TonybynMp4** [comment]
> @TonybynMp4 does it work fine?

afaik it work yes
