### ISSUE TITLE
Enhancement(FrameworkDebug): Check and warn if wrappers are not found

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#595]
### Application

Other

### Dependency

No

### Feature Description

Essentially check if resources like “es_extended” and “qb-core” are started and if their respective wrappers are started or not.

This would help with support, and general lack of reading the instructions.

**Comment by c-wide** [comment]
Some example code below, I think the dependencyLists object should be a json file but not sure where to place it, maybe it can be combined with the config checks you're looking to perform in the other issue?

I would add checkResourceDependencies() to the server/utils folder and then call it server/server.ts in the onResourceStart event or would you prefer another way?

```
// JSON file preferably - [resourceName]: dependencyArray format
const dependencyLists = {
  "es_extended": ['esx-npwd'],
  "qb-core": ['qb-npwd']
}

// On resource start, gather all resource names that are started,
// iterate over dependencyLists, if target resource is started,
// make sure all dependencies are started.
function checkResourceDependencies() {
  let startedResources: string[] = [];

  // normally would be looping until GetNumResources() and 
  // using GetResourceByFindIndex() to get the resource name.
  for (let i = 0; i < 1; i++) {
    startedResources = ['es_extended', 'esx-npwd', ...startedResources]
  }

  for (const [resourceName, depList] of Object.entries(dependencyLists)) {
    if (startedResources.includes(resourceName)) {
      if (!depList.every(elem => startedResources.includes(elem))) {
        console.log('YOURE MISSING A DEPENDENCY STUPID')
      }
    }
  }
}

checkResourceDependencies()
```

**Comment by RockySouthpaw** [comment]
> Some example code below, I think the dependencyLists object should be a json file but not sure where to place it, maybe it can be combined with the config checks you're looking to perform in the other issue?
> 
> I would add checkResourceDependencies() to the server/utils folder and then call it server/server.ts in the onResourceStart event or would you prefer another way?
> 
> ```
> // JSON file preferably - [resourceName]: dependencyArray format
> const dependencyLists = {
>   "es_extended": ['esx-npwd'],
>   "qb-core": ['qb-npwd']
> }
> 
> // On resource start, gather all resource names that are started,
> // iterate over dependencyLists, if target resource is started,
> // make sure all dependencies are started.
> function checkResourceDependencies() {
>   let startedResources: string[] = [];
> 
>   // normally would be looping until GetNumResources() and 
>   // using GetResourceByFindIndex() to get the resource name.
>   for (let i = 0; i < 1; i++) {
>     startedResources = ['es_extended', 'esx-npwd', ...startedResources]
>   }
> 
>   for (const [resourceName, depList] of Object.entries(dependencyLists)) {
>     if (startedResources.includes(resourceName)) {
>       if (!depList.every(elem => startedResources.includes(elem))) {
>         console.log('YOURE MISSING A DEPENDENCY STUPID')
>       }
>     }
>   }
> }
> 
> checkResourceDependencies()
> ```

Combining this with the other issue may be ideal but want to limit scope a bit so as to not creep too much into other checks here.

As far as json goes, we could just toss it into the misc file as a convar perhaps? Otherwise can just add it into whatever checker file is used. The misc file has quite literally 1 line. I don’t think it would break anything being there https://github.com/project-error/npwd/blob/master/resources/utils/misc.ts
