### ISSUE TITLE
Enhancement(Config): Check configuration on start

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#596]
### Application

Other

### Dependency

No

### Feature Description

Essentially check a few portions of the Config pertaining to database configuration and phone as item. Mostly this is to provide better debug logs for the end user and us when someone reports an issue.

Especially when people have the psuedo example code for phone as item but somehow set it to true. A truly wild sight to behold but not uncommon.

**Comment by c-wide** [comment]
What all checks are you looking for here?

If PhoneAsItem.enabled is true we can check to see if the default settings are 'my-core-resource' and 'myCheckerFunction' then warn the player there MAY be a problem (considering the fact someone may use that resource name and export name lol).

Afaik there is no way to check if an export exists which would be ideal here. 

What checks are you looking for pertaining to the database and rest of the config?

**Comment by thelindat** [comment]
> Afaik there is no way to check if an export exists which would be ideal here.

You just trigger the event and see if it returns a function reference; exports are just `__cfx_export_resource_event`.

**Comment by RockySouthpaw** [comment]
> What all checks are you looking for here?
> 
> If PhoneAsItem.enabled is true we can check to see if the default settings are 'my-core-resource' and 'myCheckerFunction' then warn the player there MAY be a problem (considering the fact someone may use that resource name and export name lol).
> 
> Afaik there is no way to check if an export exists which would be ideal here.
> 
> What checks are you looking for pertaining to the database and rest of the config?

Break down:
- Check that the player table exist as configured 
- Check the identifier column exist as configured 
- If phone as item is enabled, check if they’re using default configuration. We could do want linden said but this relies on a player loading so would need both. 

- If framework integration is set to true and esx/qbcore is started and the sub sequent wrappers are not started give warning. Otherwise, give confirmation.

**Comment by c-wide** [comment]
> > Afaik there is no way to check if an export exists which would be ideal here.
> 
> You just trigger the event and see if it returns a function reference; exports are just `__cfx_export_resource_event`.

How does this work? In the client-side example below "idk" is always undefined. Maybe I misread but I think this is what you are saying I can do right? 

```
on('__cfx_export_npwd_setPhoneVisible', (idk: any) => {
  console.log(idk);
});

TriggerEvent('__cfx_export_npwd_setPhoneVisible');
```

**Comment by thelindat** [comment]
Did this example quickly in Lua, cause that's how I work.
```lua
exports('icles', function() end)

local hasExport = false
TriggerEvent('__cfx_export_test_icles', function(ref)
    print('__cfx_export_test_icles', json.encode(ref))
    hasExport = not not ref
end)
print(hasExport)

hasExport = false
TriggerEvent('__cfx_export_test_eburger', function(ref)
    print('__cfx_export_test_eburger', json.encode(ref))
    hasExport = not not ref
end)
print(hasExport)
```
![image](https://user-images.githubusercontent.com/65407488/153532972-f90fdffe-f6fd-475c-96df-458def39f61e.png)

This is basically how errors are thrown for invalid exports in both JS and Lua, but you can do it yourself to test for exports and make a custom error message for people to ignore.

**Comment by RockySouthpaw** [comment]
> Did this example quickly in Lua, cause that's how I work.
Superior language
