### ISSUE TITLE
Bug(Messages): cannot read slice of null

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#597]
### Development Issue

No

### Phone Version

Master

### Issue Description

Seems to be related to invalid numbers. Issue doesn't occur when messaging valid numbers.

### Issue Reproduction

1. Open NPWD
2. Route to new message
3. Enter `911`
4. Send a message to `911`
5. Ensure npwd
6. Ensure subseqent addons
7. Open phone and click on the blank conversation box

Phone crashes.

### Evidence

![FiveM_b2372_GTAProcess_k3Td4c96uz](https://user-images.githubusercontent.com/55056068/153530931-42b744f9-91e0-4713-83be-1ad4441ed245.png)
![FiveM_b2372_GTAProcess_4Bwbei11VY](https://user-images.githubusercontent.com/55056068/153530935-04235dbe-4d50-4262-b280-246dd4f74c86.png)

**Comment by itschip** [comment]
Uh oh!

**Comment by RuisSoftware** [comment]
Same problem here!

Using multi character, my config:

```
  "general": {
    "useResourceIntegration": true,
    "toggleKey": "f2",
    "toggleCommand": "phone"
  },
  "database": {
    "useIdentifierPrefix": false,
    "playerTable": "characters_metadata",
    "identifierColumn": "citizenid",
    "identifierType": "license",
    "profileQueries": true,
    "phoneNumberColumn": "phone_number"
  },
```

**Comment by RuisSoftware** [comment]
This happens to me when a new thread is generated and the player tries to open this new thread. 

When i change npwd_messages_conversations - user_identifier to their number, than they can open the thread, but no notifications are received.

**Comment by RuisSoftware** [comment]
Testing it right now

**Comment by RockySouthpaw** [comment]
> This happens to me when a new thread is generated and the player tries to open this new thread.
> 
> When i change the user_identifier in npwd_messages_conversations to their number, than they can open the thread, but no notifications are received.
> 
> After changing this database info, i edited the script to see if it works from there too: From:
> 
> ```ts
>     await MessagesDB.createMessageGroup(sourcePhoneNumber, conversationId, sourcePhoneNumber);
>     await MessagesDB.createMessageGroup(sourcePhoneNumber, conversationId, tgtPhoneNumber);
> ```
> 
> To:
> 
> ```ts
>     await MessagesDB.createMessageGroup(tgtPhoneNumber, conversationId, sourcePhoneNumber);
>     await MessagesDB.createMessageGroup(sourcePhoneNumber, conversationId, tgtPhoneNumber);
> ```
> 
> in messages.utils.ts
> 
> This makes opening the thread work for all my players, but the thread creator is not getting notification on receiving new messages. I know this is not what you intended but at least the thread opens now.
> 
> Phone numbers are taken from the player metadata and i used their original number used for gcphone. My phone number: 25619342 Friend number: 0118785285
> 
> I'm using the 'official' QB bridge resource. Other apps are working great!

It’s like what happens to you is exactly as described in the issue write up. *Shocking*. Don’t need someone to confirm the issue exist with reproductions written.

**Comment by RuisSoftware** [comment]
> > This happens to me when a new thread is generated and the player tries to open this new thread.
> > When i change the user_identifier in npwd_messages_conversations to their number, than they can open the thread, but no notifications are received.
> > After changing this database info, i edited the script to see if it works from there too: From:
> > ```ts
> >     await MessagesDB.createMessageGroup(sourcePhoneNumber, conversationId, sourcePhoneNumber);
> >     await MessagesDB.createMessageGroup(sourcePhoneNumber, conversationId, tgtPhoneNumber);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To:
> > ```ts
> >     await MessagesDB.createMessageGroup(tgtPhoneNumber, conversationId, sourcePhoneNumber);
> >     await MessagesDB.createMessageGroup(sourcePhoneNumber, conversationId, tgtPhoneNumber);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in messages.utils.ts
> > This makes opening the thread work for all my players, but the thread creator is not getting notification on receiving new messages. I know this is not what you intended but at least the thread opens now.
> > Phone numbers are taken from the player metadata and i used their original number used for gcphone. My phone number: 25619342 Friend number: 0118785285
> > I'm using the 'official' QB bridge resource. Other apps are working great!
> 
> It’s like what happens to you is exactly as described in the issue write up. _Shocking_. Don’t need someone to confirm the issue exist with reproductions written where it’s clear it’s reproducible.

Bro wake up and take a coffee next time before you respond please.

**Comment by RockySouthpaw** [comment]
@itschip Can unpin issue as it’s resolved.
