### ISSUE TITLE
Bug: not receiving the text message notification

### ISSUE THREAD

**Issue by RuisSoftware** [project-error/npwd#599]
### Development Issue

Unsure

### Phone Version

1.1.6 and 1.1.5

### Issue Description

We do not get a notification on message receive. All other phone notifications are working.

We use multi character setup with config: 
```json
  "general": {
    "useResourceIntegration": true,
    "toggleKey": "f2",
    "toggleCommand": "phone"
  },
  "database": {
    "useIdentifierPrefix": false,
    "playerTable": "characters_metadata",
    "identifierColumn": "citizenid",
    "identifierType": "license",
    "profileQueries": true,
    "phoneNumberColumn": "phone_number"
  },
```

### Issue Reproduction

Clear database tables
Restart server
Create a character
Message another online player
This other player does not receive a notification

**Comment by itschip** [comment]
Is this a 'other player' in current conversation already?

**Comment by RuisSoftware** [comment]
> 

The other player has closed the phone, but is logged in.
We tested the case of a newly created thread (no text message send before)
   and all other following messages but all are not sending a notification.

**Comment by itschip** [comment]
@RuisSoftware are these resolved in develop?

**Comment by RuisSoftware** [comment]
Nope, this issues is still here on develop and 1.1.7

**Comment by itschip** [comment]
@RuisSoftware closing this. If you haven't updated the phone since this was reported, do such and create a new issue if this occurs again.
