### ISSUE TITLE
Enhancement: default web home page

### ISSUE THREAD

**Issue by MJRamon** [project-error/npwd#601]
### Application

Browser

### Dependency

No

### Feature Description

Ability to set in config default home page for browser.

**Comment by Patilhas** [comment]
Hi, you can set the default page in phone/src/config/default.json. Of cource if you have the development version. If you don't I don't think there is another way to do it besides changing and then build.

**Comment by TasoOneAsia** [comment]
Patilhas is correct, unfortunately due to some websites having their iframe policy set disallowing embedding, we are unable to *guarantee* access without setting up some intermediate proxy that rewrites headers.
