### ISSUE TITLE
Enhancement: Twitter Logins

### ISSUE THREAD

**Issue by Solositeous** [project-error/npwd#606]
### Application

Twitter

### Dependency

No

### Feature Description

Allow creating of multiple Twitter accounts with unique logins so player-run businesses can make Twitters for themselves so they can do Twitter marketing and allow multiple players to sign into that account.

**Comment by TasoOneAsia** [comment]
This would require a substantial rewrite of how the system works at the moment. We don't have the appropriate dev time to do that, at the moment.
