### ISSUE TITLE
Enhancement: Twitter mentions

### ISSUE THREAD

**Issue by itschip** [project-error/npwd#607]
### Application

Twitter

### Dependency

No

### Feature Description

Show mentions in tweets, instead of just default text. Perhaps autocomplete for tags as well. Select recent users that has tweeted.

### References

Twitter, duh...

**Comment by TasoOneAsia** [comment]
Autocomplete for tags seems like it might be decently heavy. How were you thinking of executing this?

**Comment by itschip** [comment]
Could do this ourselves. It's somewhat of a hassle, and I don't know if I want drag more potential "mess" into the codebase. I'll probably introduce some lib for this.
