### ISSUE TITLE
Enhancement: Redesign Marketplace

### ISSUE THREAD

**Issue by itschip** [project-error/npwd#611]
### Application

Marketplace

### Dependency

No

### Feature Description

Let's come up with a new design for this shit app.

**Comment by TasoOneAsia** [comment]
For contributors, this is a Figma concept that was created a while ago.

![image](https://i.tasoagc.dev/8uDM)

**Comment by antonstjernquist** [comment]
Hey, can I take this? :)

**Comment by itschip** [comment]
> Hey, can I take this? :)

Sure @antonstjernquist
