### ISSUE TITLE
Bug: Phone can only be opened when pressed F2

### ISSUE THREAD

**Issue by Gamesuchti** [project-error/npwd#618]
### Development Issue

Unsure

### Phone Version

Version 1.1.6

### Issue Description

When I made the config I set the phone-open key to F1, but the phone still opens with F2

### Issue Reproduction

1. Set config to F1
2. Save
3. Restart Server
4. Phone still opens with F2

**Comment by TasoOneAsia** [comment]
This doesn't have anything to do with NPWD behavior, rather how FiveM handles key mapping. The config only applies for any **new** users, old users will need to change this manually in their GTA settings.
