### ISSUE TITLE
Enhancement: Implicit default config and config file language interoperability

### ISSUE THREAD

**Issue by TasoOneAsia** [project-error/npwd#621]
### Application

Other

### Dependency

No

### Feature Description

We may be confusing users by presenting them too many options at one time in the `config.json` file. One approach to fix this would be to have an implicitly set default config, that is overwritten by a `config.json` and its keys. 

It may also be beneficial to allow for multiple configuration language files to be interoperable and is the norm in many NPM packages (as well as many libraries in general). This proposed interoperability would allow for `.yml, .json, or .js` configuration files to all be valid. Convar configurations should also be taken into account.

We could also go fully towards ConVars as the primary configuration approach. This should be discussed.

### References

**Valid ESLint Config Formats**
https://eslint.org/docs/user-guide/configuring/configuration-files

**Valid Prettier Config Formats**
https://prettier.io/docs/en/configuration.html

**Comment by c-wide** [comment]
I personally dont see the advantage of using convars vs normal config files despite everyone being hyped over them currently. I think they introduce unnecessary confusion in the best of cases.

**Comment by TasoOneAsia** [comment]
> I personally dont see the advantage of using convars vs normal config files despite everyone being hyped over them currently

I believe CFX's intention with encouraging ConVar use is to provide a generic interface that can be utilized flexibly while still being also being handled easily in a standardized format across the ecosystem. For example, FxDK could abstract resource configuration if resources were able to stick by the ConVar format. This could also be utilized by txAdmin for resource configuration as well, if standardized. They are somewhat like `FX Manifest` metadata properties. 

They also have some parallels with environment variables.

**Comment by c-wide** [comment]
I dont know many usecases where script x will need access to script y's config file and I think it's alot easier to understand editing values in a config file rather than some random lua file with convar functions.

Take for example pma-voice, reading over the readme, how does anyone know where to put those convars unless you're a developer already familiar with convars? 

The current users we have already have problems setting up the config file, I think convars will add unnecessary complexity for end users and just serve to clutter the code base.

**Comment by itschip** [comment]
https://github.com/davidtheclark/cosmiconfig just leaving this here as well

**Comment by antonstjernquist** [comment]
A version one might be creating a `config.default.json` file and merge the config.json with that. Would eliminate issues with file endings and having to load config client etc. Perhaps with schema support as well :o
