### ISSUE TITLE
Enhancement: blacklist words

### ISSUE THREAD

**Issue by Spykespy** [project-error/npwd#622]
### Application

Other

### Dependency

No

### Feature Description

Hello! It would be awesome to have a blacklist that automatically blocks twitter messages, tinder profiles, marketplace ads etc. with that word in it. To more easily prevent shit like the attatched image (a dutch swearword being spammed).

Oh, and while I'm at it, maybe a system to allow server moderators to delete twitter messages etcetera if they are allowed a certain ace. Moderation is still quite the effort.

![image](https://user-images.githubusercontent.com/40208312/154753807-c3734a98-3422-494d-b313-5a03b359eedb.png)

**Comment by Mojito-Fivem** [comment]
Added in #623

**Comment by TasoOneAsia** [comment]
Keep in mind, the Scunthorpe dilemma.

https://en.m.wikipedia.org/wiki/Scunthorpe_problem

**Comment by itschip** [comment]
Merged with https://github.com/project-error/npwd/pull/625
