### ISSUE TITLE
Bug: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Destructor** [project-error/npwd#626]
### Development Issue

Unsure

### Phone Version

1.1.7

### Issue Description

Hi,

I use last release 1.1.7 and i have this error.
I have a multichar server with MF-MultiChar and i use esx-npwd.

![image](https://user-images.githubusercontent.com/1570770/154845231-c32e3b77-cb44-446f-a9a9-a6bca3fdb1ef.png)
![image](https://user-images.githubusercontent.com/1570770/154845247-7e5d6805-4d9a-4fe2-818c-140270ceaf54.png)
![image](https://user-images.githubusercontent.com/1570770/154845255-4046a441-da77-4c60-9884-3fe66afbafc0.png)

### Issue Reproduction

1.Connect
2.Select Player
3.Open phone
4.Use app contact

### Evidence

https://streamable.com/1ku7bn

**Comment by itschip** [comment]
@Destructor Can you please show me your config.json file? Create a pastebin or so. I assume you're missing something there.

**Comment by Destructor** [comment]
https://pastebin.com/XFBrjk1b

**Comment by itschip** [comment]
@Destructor Do you by any chance happen to start `npwd` before `esx-npwd`?

It would also be great if you changed the `debug.level` to silly, in order to get more detailed logs.

**Comment by mrgwilliam** [comment]
Hey, I am also encountering this issue, I have it with the qb-framework. I use the qb-npwd module. 

Module Order: - I've tried both, NPWD first and then qb-npwd module and flipped them to no success

Attached a copy of server logs:
https://gist.github.com/mrgwilliam/ba34028f92c05d8d062288355c850bad

**Comment by itschip** [comment]
@mrgwilliam Thanks. I'll checks what's going on. In the meanwhile please read https://projecterror.dev/docs/npwd/framework/qb-core/ and make sure your config is correct.

**Comment by itschip** [comment]
Closing this. If you're still on 1.1.7, please update.
