### ISSUE TITLE
Enhancement: Activate "strictNullChecks" in tsconfig

### ISSUE THREAD

**Issue by antonstjernquist** [project-error/npwd#632]
### Application

Other

### Dependency

No

### Feature Description

Hey,

Currently "strictNullChecks" is set to false in the tsconfig which is more than likely causing some bugs. I think this is the minimum you should have active to get real benefit from Typescript.

Currently this is allowed:
![image](https://user-images.githubusercontent.com/32514829/155087687-cf80db82-1bda-4507-99d1-88ac092133da.png)

After strictNullChecks:
![image](https://user-images.githubusercontent.com/32514829/155087896-7ba61a25-fee6-4fb1-adf3-70f220ec9283.png)

**Comment by itschip** [comment]
@antonstjernquist should we close this issue, or what's up?
