### ISSUE TITLE
Bug: cannot create a message

### ISSUE THREAD

**Issue by alexwilliamlex** [project-error/npwd#637]
### Development Issue

No

### Phone Version

1.1.7

### Issue Description

 I have a problem, when I want to send a message it does not work, I have these errors in my F8
![image](https://user-images.githubusercontent.com/24566508/155417782-b044bd3a-3dc3-41bc-a21f-0d71dc05a41b.png)

### Issue Reproduction

I don't know how to reproduce it.

**Comment by itschip** [comment]
Are there no server-side errors?

**Comment by alexwilliamlex** [comment]
no ..

**Comment by itschip** [comment]
Oh well....your trying to create a conversation with a already created contact, or something random?

**Comment by alexwilliamlex** [comment]
both and it doesn't work :/

**Comment by itschip** [comment]
Will be fixed once develop is merged.

**Comment by alexwilliamlex** [comment]
thank's
