### ISSUE TITLE
Bug: SetCallVolume

### ISSUE THREAD

**Issue by CrownZeroGaming** [project-error/npwd#638]
### Development Issue

No

### Phone Version

V.1.1.7

### Issue Description

No such export SetCallVolume in pma-voice.
I'm using the 5181 Artificat, and 6.6.1 Version of PMA-Voice
Provided a screenshot of the error in the F8 Console.

[https://prnt.sc/0rCMJAU5gGoY](url)

### Issue Reproduction

1. Start server
2. Load in
3. Press F8
4. Spot error

### Evidence

[https://prnt.sc/0rCMJAU5gGoY](url)

**Comment by TasoOneAsia** [comment]
Ensure that pma-voice is started prior to NPWD. This is most likely resulting from that. Feel free to reopen the issue if this isn't the case.
