### ISSUE TITLE
Turn off Retweets config

### ISSUE THREAD

**Issue by sassyx** [project-error/npwd#639]
### Application

Twitter

### Dependency

No

### Feature Description

Would like to see the feature for a config bit that turns off the option of retweets since sometimes it actually breaks the phones and in my server at least its becoming a issue sometimes when you have 10-20 retweets it makes the hole server Lagg.

**Comment by TasoOneAsia** [comment]
@itschip @antonstjernquist An urgent issue to solve is handling of our stores in response to hydration from the backend API. We continually store items and displaying without culling. I'm not sure if the infinite scroll is still applicable but we should be paginating in some fashion from our store.

**Comment by itschip** [comment]
> An urgent issue to solve is handling of our stores in response to hydration from the backend API. We continually store items and displaying without culling. I'm not sure if the infinite scroll is still applicable but we should be paginating in some fashion from our store.

@TasoOneAsia This is resolved already. For the time being, inf scroll is disabled, and we're removing tweets after a certain amount of tweets.

**Comment by itschip** [comment]
@sassyx Available in 1.1.8
