### ISSUE TITLE
Bug: Screenshot Tooltip Present in Picture

### ISSUE THREAD

**Issue by ch0sguy** [project-error/npwd#643]
### Development Issue

Unsure

### Phone Version

Latest Version (as of 2/25/2022)

### Issue Description

How images appear within the gallery after they're captured:
![photroingallery](https://user-images.githubusercontent.com/62267705/155677168-5c84999d-e029-4e50-80e0-b6fb1d6e7fd5.PNG)

How they're displayed using the URL from said image within the gallery:
![mdwpicture](https://user-images.githubusercontent.com/62267705/155677521-3e4e7636-7133-4ce3-bff0-6aec3c9eb1ee.PNG)

This is the case for every instance (twitter, marketplace, external usage, etc).

This is most definitely an issue with the screenshotting toolkit utilized, the qb-phone utilizes a different, buggier variant that doesn't replicate this due to it not displaying any form of instruction on the user's screen; if possible, they could delay the capture to remove said obstruction moments before saving the player's screen.

### Issue Reproduction

Just take any picture in game and utilize the link.

**Comment by itschip** [comment]
This is fixed.
