### ISSUE TITLE
Bug: displaying "touch" 

### ISSUE THREAD

**Issue by antonstjernquist** [project-error/npwd#644]
### Development Issue

Yes

### Phone Version

latest

### Issue Description

It should probably not show the touch event thing when pressed ingame?

### Issue Reproduction

1. Hold finger on icon ingame

### Evidence

![image](https://user-images.githubusercontent.com/32514829/155720182-5907f396-9fab-4970-9b3a-18bf0baf089a.png)

**Comment by itschip** [comment]
Fixed.
