### ISSUE TITLE
Bug: Messages sent to offline players don't populate to those players when they come online

### ISSUE THREAD

**Issue by RageOps** [project-error/npwd#645]
### Development Issue

Unsure

### Phone Version

1.1.7

### Issue Description

A text is sent to a player that is offline. This message successfully populates in the database but is not seen by the player that it was sent to when that player comes back online.

Upon testing this myself, I noticed that this issue is hard to reproduce consistently. It appears to function as intended when I log off on my -cl2 and send a message to myself while offline, it populates when I log back in. I'll do some more digging in the meantime with my players to see if I can outline any better repeatable steps.

### Issue Reproduction

Player 1: Sender
Player 2: Receiver

Player 2 is offline. Player 1 sends them a text. Player 2 comes online and checks their phone. The message that was sent to Player 2 is not shown on Player 2's phone, but they will occasionally see the notification icon displaying that they have an unread message.

### Evidence

From one of my players, demonstrating how the message bubbles pop up but there are no messages to be seen: https://streamable.com/jhzwai

Two screenshots from another player demonstrating the notification being red but no texts to be seen:
https://i.imgur.com/nfx2WPY.png
https://i.imgur.com/TbvLJww.png

**Comment by itschip** [comment]
This will be fixed once we merge `develop` with the new message system.
