### ISSUE TITLE
Messages App: v.slice is not a function

### ISSUE THREAD

**Issue by FBFezz** [project-error/npwd#646]
### Development Issue

Unsure

### Phone Version

1.1.8

### Issue Description

Onesync Version:  Onesync on(infinity)
ESX Version: Legacy (Latest)
Server Version: 5365
Game Build: 2545

Going into messages app nearly always gives this error
![image](https://user-images.githubusercontent.com/43589668/155830963-6a11ed3c-20b5-444d-9015-48eb5fc4a0b0.png)

### Issue Reproduction

1. Go into messages app
(Thats it to my knowledge)

### Evidence

https://streamable.com/kv958k

**Comment by DooubleTap** [comment]
we get this error too when we click on a contact

**Comment by FBFezz** [comment]
Believe this is fixed in the latest pre version as said in
#597
