### ISSUE TITLE
Bug: Calls Map

### ISSUE THREAD

**Issue by TheDiego845** [project-error/npwd#647]
### Development Issue

Unsure

### Phone Version

1.1.7

### Issue Description

Call sound is buggy and can't be picked up

### Issue Reproduction

Go to calls
Call anyone
and error

### Evidence

https://streamable.com/erm90n
![image](https://user-images.githubusercontent.com/69425536/155879278-a6570ff6-1c53-4b7b-9c77-1553457f3964.png)

**Comment by Destructor** [comment]
Same Problem on 1.1.8
![error 2 and 2](https://user-images.githubusercontent.com/1570770/155879759-6e489a14-8c5b-4090-99e0-2cf45292ebd5.png)
![error 1 and 2](https://user-images.githubusercontent.com/1570770/155879763-397d16d7-db0a-4af0-845b-6335a9e0abc0.png)

Streamable
https://streamable.com/z86o44

**Comment by TheDiego845** [comment]
![image](https://user-images.githubusercontent.com/69425536/155881463-4c38c2f1-7c5a-42d7-b976-a11e101543bc.png)

**Comment by Mojito-Fivem** [comment]
https://streamable.com/cjd8gy I've just tried this on the master branch and I'm unable to reproduce

**Comment by TheDiego845** [comment]
I am using esx 1.1 final

**Comment by Destructor** [comment]
I tried switching to another version of NPWD but that didn't change anything. unable to make calls.

Still the same error as above

**Comment by antonstjernquist** [comment]
@TheDiego845 You have to provide some more information or a reproduction. 

Have you tried disabling all other resources?
Are you using this with esx, qb?
Is your config valid? 

You can reach out on Discord :)
