### ISSUE TITLE
Enhancement: Phone Number per individual item

### ISSUE THREAD

**Issue by TonybynMp4** [project-error/npwd#649]
### Application

Other

### Dependency

No

### Feature Description

My idea is basically : 
Instead of giving a phone number per player, 
give a phone number to the item, so you could buy phones and every phones would have their own numbers,
it would add the possibility, for example, to give your phone to another player, have multiple phones (like one for legal stuff and one for illegal stuff) etc...
I suggest it knowing that it's probably not gonna be possible since it would probably be hard to make it standalone since it looks like it would be very framework dependent, but i'm no developer so who knows maybe it could!

**Comment by Mojito-Fivem** [comment]
This is not really easily achievable in a framework agnostic way, there is an issue with unloading players outlined in #476 which once solved you may able to emulate this by loading and unloading players but for now this probably won't be implemented.

**Comment by frazz1234** [comment]
Using a SIM CARD system ? Aloud people change number . ?

**Comment by TonybynMp4** [comment]
> 

i guess it's an other way to do it yeah

**Comment by TonybynMp4** [comment]
Now that #476 is fixed (supposedly?) Do you think you could think about it? @Mojito-Fivem

**Comment by Mojito-Fivem** [comment]
> Now that #476 is fixed (supposedly?) Do you think you could think about it? @Mojito-Fivem

If `unloadPlayer` is working then people could implement this themselves, it's not something we can add directly to NPWD
