### ISSUE TITLE
Enhancement: move browserHomePage to config

### ISSUE THREAD

**Issue by xenfovn** [project-error/npwd#650]
I hope that in the next version it will be in config instead of having to edit it in the js file

**Comment by antonstjernquist** [comment]
Probably atleast want this before:
https://github.com/project-error/npwd/issues/621

**Comment by xenfovn** [comment]
at least it's simple, I can't create PR due to no js knowledge

> Probably atleast want this before: #621

**Comment by TasoOneAsia** [comment]
We also need to note that the browser is limited in the sites that it can target. Most popular sites prohibit rendering within an iframe for clickjacking purposes. For end-users, this could be solved by setting up an NGINX proxy tasked with rewriting the headers in question and forwarding requests.

This is also a pending issue upstream and may be solved at that level.
[@citizenfx/fivem#942](https://github.com/citizenfx/fivem/issues/942)
