### ISSUE TITLE
Enhancement: Add Crypto App

### ISSUE THREAD

**Issue by gerardojro** [project-error/npwd#653]
### Application

Other

### Dependency

Yes

### Feature Description

Add Crypto app (see qb-phone)

**Comment by Mojito-Fivem** [comment]
In an effort to keep NPWD standalone, features like cryptocurrency are heavily framework dependent so there are no plans to work on this. If you keep an eye on the work being done on module federation it may be possible to create your own apps as a separate resource in the future.

**Comment by itschip** [comment]
Closing this for now.
