### ISSUE TITLE
Bug: Photo could not be saved

### ISSUE THREAD

**Issue by Slypher** [project-error/npwd#655]
### Development Issue

No

### Phone Version

Pre-Release Build (dca889b2) | 03/01/22 | [unstable](https://github.com/project-error/npwd/releases/tag/unstable)

### Issue Description

When saving the photo I took, the phone displays the error: "The photo could not be saved :(". I followed all the steps described in the documentation. I don't get any errors on the client/server.

Screenshot Basic Version: [project-error/screenshot-basic](https://github.com/project-error/screenshot-basic)

Phone settings in server.cfg
![image](https://user-images.githubusercontent.com/39607799/156908177-a4909fc2-23c6-4566-9680-a70058e16737.png)

**OBS:** I'm from Brazil, I saw a notice saying that in some countries it's not possible to use the imgur service, I looked for a problem here but I didn't find an answer about.

### Issue Reproduction

1. I click on the camera
2. Take a picture
3. And when saving I get the error: **Photo could not be saved :(**

### Evidence

![image](https://user-images.githubusercontent.com/39607799/156908034-55ff67b5-0202-4aa0-b36a-5ec1f6cdac29.png)

**Comment by itschip** [comment]
I assume the server just logs 'data' as `null`?

**Comment by Slypher** [comment]
> I assume the server just logs 'data' as `null`?

Yes, I get null value

**Comment by PhantomPeppers** [comment]
find anything? im having same problem but from US

**Comment by Slypher** [comment]
> find anything? im having same problem but from US

I still haven't found the problem :/

**Comment by itschip** [comment]
@Slypher @PhantomPeppers did you change anything in your config.json?

**Comment by Slypher** [comment]
> @Slypher @PhantomPeppers did you change anything in your config.json?

I didn't change anything in config.json, the only changes made on the phone were the sets in the server.cfg

**Comment by Slypher** [comment]
> @Slypher @PhantomPeppers did you change anything in your config.json?

Here's the fork I'm using [phone](https://github.com/poderparalelo/npwd/tree/main)

**Comment by itschip** [comment]
@Slypher you could try and print the response from imgur. Might be some useful information there. I'd say that's the best thing to check first.

**Comment by Slypher** [comment]
> @Slypher you could try and print the response from imgur. Might be some useful information there. I'd say that's the best thing to check first.

When trying to upload the photo to imgur, I get the following warning:
![image](https://user-images.githubusercontent.com/39607799/158045829-cc92e968-c592-4e61-9de1-4fb36e4f84e7.png)

**Comment by itschip** [comment]
I'll investigate with a VPN. Thanks.

**Comment by BigBrainBernie** [comment]
In your cfg - do not change authorizationPrefix Client-ID to your id - works for me 

  "images": {
    "url": "https://api.imgur.com/3/image",
    "type": "imgur",
    "imageEncoding": "jpg",
    "contentType": "multipart/form-data",
    "authorizationPrefix": "Client-ID",
    "useAuthorization": true,
    "returnedDataIndexes": ["data", "link"]
  },

**Comment by itschip** [comment]
@Slypher is this resolved?

**Comment by itschip** [comment]
Closing this for now. Worth noting that we're working on our own service for those that has trouble with imgur and other services.
