### ISSUE TITLE
Enhancement: Ability to choose between pma-voice and Saltychat

### ISSUE THREAD

**Issue by LostJ3ster** [project-error/npwd#659]
### Application

Other

### Dependency

Yes

### Feature Description

We, as well as many other servers, use SaltyChat for all of our ingame voice.

For this phone we tested pma-voice.

We got the phone to work and except for some features we'd love to continue using it.
Problem now is, we also would love to continue using Saltychat. Therefor we'd like to choose between pma-voice and Saltychat in config.

Thank you for sharing this awesome phone, keep up the great work! :)

**Comment by Mojito-Fivem** [comment]
We won't be adding support for voice solutions which use weird third party teamspeak programs

**Comment by ulasdemirci0** [comment]
> We won't be adding support for voice solutions which use weird third party teamspeak programs
@Mojito-Fivem 
That is necessary thing. Server owners must have choose chance. Its open source project and its more complex than other phone scripts, so you have to be kind for that issue.

**Comment by Mojito-Fivem** [comment]
> > That is necessary thing. Server owners must have choose chance. Its open source project and its more complex than other phone scripts, so you have to be kind for that issue.
Thank you for your suggestion, this *is* open source you are right, and we (the maintainers), have decided we won't be willing to support these plugins. You are however welcome to fork the project

**Comment by ulasdemirci0** [comment]
I don't have enough knowledge for that. Most of server owners can't make that. You should reconsider this decision.
Thanks for your attention for these issues.

**Comment by ulasdemirci0** [comment]
@Mojito-Fivem can we contact on discord please i'm sure i can to persuade.

**Comment by itschip** [comment]
@ulasdemirci0 These are changes we expect you to do yourself. We have standarized pma-voice and it is not subject to change.
