### ISSUE TITLE
Bug: Unable to getIdentifier and phone number

### ISSUE THREAD

**Issue by tr1ckz** [project-error/npwd#661]
### Development Issue

No

### Phone Version

v1.1.8

### Issue Description

First off, I'm using ox legacy es_extended that has the esx-nwpd built in, using steam identifier (changed in es_extended already and all the other scripts work) and esx_multicharacter that makes all identifiers char1,char2,etc. 

My config:
![image](https://user-images.githubusercontent.com/48994713/158191436-b9adb962-759e-4653-b661-28dac6abd62e.png)
Error when logging in fresh after a restart:
![image](https://user-images.githubusercontent.com/48994713/158191537-17ab72f5-efc3-40e8-83e3-8e549ac6288d.png)
When opening the phone after logging in:
![image](https://user-images.githubusercontent.com/48994713/158191682-9553f854-9234-4539-8348-4a7d44ac02ff.png)
Also looks like it properly removes it when logging off:
![image](https://user-images.githubusercontent.com/48994713/158191919-272b3e90-4810-45fb-848a-321bf8c59e78.png)
Just in case this is the npwd from es_extended:
![image](https://user-images.githubusercontent.com/48994713/158192289-1305a6a1-2c57-489a-acf1-034d42130a48.png)
And server.cfg:
![image](https://user-images.githubusercontent.com/48994713/158192402-992cd71d-035c-406e-b49c-aee451489fa2.png)

### Issue Reproduction

It happens all the time, after logging in and opening the phone.

**Comment by itschip** [comment]
Closing this. Please use our support channel in the Discord guild.
