### ISSUE TITLE
Bug: Match Profile Error (Same player names)

### ISSUE THREAD

**Issue by YisusOnDev** [project-error/npwd#664]
### Development Issue

Yes

### Phone Version

v1.1.8

### Issue Description

If 2 or more players has the same name you get a console print showing an error because npwd_match_profiles has a unique key on "name" row

```
[NPWD] [match] [error]: Failed to get player profile, Duplicate entry 'James Cooper' for key 'name_UNIQUE'
```

### Issue Reproduction

Register 2 players using npwd newPlayer export with the same firstname and lastname.

### Evidence

![image](https://user-images.githubusercontent.com/52821987/158602289-4b0ca34f-1f11-4a0c-9ec5-08e53538d458.png)

**Comment by itschip** [comment]
I have allowed for duplicate names. I'll let you know when I release a patch for you to test.

**Comment by itschip** [comment]
@YisusOnDev Could you check if this persists in 1.2.94?

**Comment by YisusOnDev** [comment]
Can't reproduce it.
