### ISSUE TITLE
Bug: Number does not save

### ISSUE THREAD

**Issue by WilderMO** [project-error/npwd#669]
### Development Issue

No

### Phone Version

[1.2.1](https://github.com/project-error/npwd/releases/tag/1.2.1)

### Issue Description

The Phone works except that the created number is not saved in the SQL database.
Every time I join my server I get another number and it will not save.

### Issue Reproduction

1. Join the server
2. See problem

### Evidence

![image](https://user-images.githubusercontent.com/66009198/159128152-042ec928-7f3b-4446-86fb-c3e77e63d1a1.png)
![image](https://user-images.githubusercontent.com/66009198/159128183-f11166b8-36c1-4de9-851d-51a82e81acab.png)

**Comment by YisusOnDev** [comment]
The issue seems to be yours, for me all is working well.

You need to update your database with the generated number, i think npwd does not handle that for you, npwd only reads the number from the table you specify in the config.

**Comment by WilderMO** [comment]
@YisusOnDev But npwd generates a phone number. So why would it not save it?
thats my problem.
Do you have anything that saves the number for the npwd?

**Comment by YisusOnDev** [comment]
I'm using npwd since (months?) So when i create a new player i generate a phone and save into the database with all his character data, so i'm not using any npwd phone generator or saver.

**Comment by WilderMO** [comment]
ok thanks. Them Im going to look into this more now.

**Comment by itschip** [comment]
@WilderMO was this resolved?

**Comment by itschip** [comment]
Closing this for now. Try with 1.2.8.
