### ISSUE TITLE
Bug: New messages with phone opened make it crash

### ISSUE THREAD

**Issue by YisusOnDev** [project-error/npwd#672]
### Development Issue

Yes

### Phone Version

v1.2.3

### Issue Description

When you have an old conversation with someone and that someone message you when you have the phone opened the phone get bugged and "crash" (nui stuck).

Seems like a problem with routing? Will confirm if I get back with bottom navigation the issue exist or not.

### Issue Reproduction

1. Get a conversation with someone.
2. Leave your phone opened and tell that "someone" to message you.
3. Read the conversation and try to get back.
4. NUI get stuck and you need to restart.

### Evidence

[Video](https://streamable.com/1cyu7u)

**Comment by itschip** [comment]
Not able to reproduce. Probably related to #673
