### ISSUE TITLE
Bug: Deleted conversation still getting messages generating phone crash.

### ISSUE THREAD

**Issue by YisusOnDev** [project-error/npwd#673]
### Development Issue

Yes

### Phone Version

v1.2.3

### Issue Description

(Don't mind group chat or normal chat)

If you create or have a conversation and delete it, you keep getting messages for the deleted conversation so the phone gets errors and crash.

### Issue Reproduction

1. Tell someone to text you or send message to someone
2. Get a normal conversation
3. Delete the conversation
4. Tell the other to message you
5. See error and nui stuck

### Evidence

![image](https://user-images.githubusercontent.com/52821987/159159340-83c09eca-5844-42a9-9d59-6063e87fe9b2.png)

**Comment by itschip** [comment]
@YisusOnDev Does still happen in 1.2.6?

**Comment by itschip** [comment]
Should be fixed in 863d54a8184aa8bfc0a05d04628bf90ddc161554. I'll create a new release shortly you can test.
