### ISSUE TITLE
Bug: Incorrect arguments to mysqld_stmt_execute

### ISSUE THREAD

**Issue by AvaN0x** [project-error/npwd#674]
### Development Issue

No

### Phone Version

1.2.1

### Issue Description

Issue caused by MySQL version 8.0.22 and above (currently using 8.0.27). Whenever a query has a `LIMIT ?` there is the error "Incorrect arguments to mysqld_stmt_execute".

This issue has a fix that you can find here https://github.com/sidorares/node-mysql2/issues/1239#issuecomment-760314979.
Basically, every time there is a `LIMIT ?` with a number as value there will be the error. Having it passed as a string fixes it. (Same issue for the `OFFSET ?`)

So for example here : https://github.com/project-error/npwd/blob/165c90edccc7c484502d9b5c015ebfe2d61413dc/resources/server/messages/messages.db.ts#L44-L48

Having this would fix the error : 
```ts
    const [results] = await DbInterface._rawExec(query, [
      dto.conversationId,
      MESSAGES_PER_PAGE + "",
      offset + "",
    ]);
```

### Issue Reproduction

1. Update your mysql to 8.0.22 or above
2. Create a conversation
3. Try to open the conversation, you should get an error saying "Impossible to find messages"
![image](https://user-images.githubusercontent.com/27494805/159166367-4b70f3b7-4325-4f0e-9ff5-0cff77b9cc4e.png)
And the server console should show these : 
![image](https://user-images.githubusercontent.com/27494805/159166388-ede0ed18-26fa-4906-9cd1-308e74a3fcdc.png)
![image](https://user-images.githubusercontent.com/27494805/159166393-80634d13-f822-4dab-9dc7-6d3887a89fa4.png)

**Comment by itschip** [comment]
Fixed in 14c82ee1973fb4d43bc239d140a1af538c4125f8 and 90133a626a2445b549e9a67cef214a1382d0b426
