### ISSUE TITLE
Bug: Matchmaker app bugged after 100 or more likes

### ISSUE THREAD

**Issue by YisusOnDev** [project-error/npwd#675]
### Development Issue

Unsure

### Phone Version

v1.2.3

### Issue Description

When someone gets more than +99 matches with other people the app gets bugged.

### Issue Reproduction

1. Get more than 100 matches/likes in the app
2. App does not show properly again.

### Evidence

![image](https://user-images.githubusercontent.com/52821987/159172424-3381f930-d4f1-499d-9820-cf6e7cfd4d3c.png)

**Comment by Mojito-Fivem** [comment]
Do you have a reliable repro for this? I'm unable to recreate this in my dev environment after adding a few hundred entries to the mock data

**Comment by YisusOnDev** [comment]
No, people gets bugged when gets 100+ matches, on my server there are +300 players registered and so. I can only reproduct this on the live server

**Comment by itschip** [comment]
@YisusOnDev Please test this in 1.2.91
