### ISSUE TITLE
Bug: onMessage Export not working

### ISSUE THREAD

**Issue by YisusOnDev** [project-error/npwd#677]
### Development Issue

Unsure

### Phone Version

v1.2.3

### Issue Description

With the latest changes "onMessage export listener" does not work, u send a message and the listener never get called (didn't receive that someone message any number).

### Issue Reproduction

1. Register an onmessage export for 1 number 
2. Send a message to that number
3. nothing happens, listener not working

**Comment by Ehbw** [comment]
Can confirm, it appears that the tgtPhoneNumber and sourcePhoneNumber variables on the ``npwd:sendMessage`` event are always the same

**Comment by AvaN0x** [comment]
I can confirm it too, message sent from `456-456-4567` to `911` :
![image](https://user-images.githubusercontent.com/27494805/160600560-3995bdbc-cdcb-410a-adcf-18357d09bb4e.png)

**Comment by AvaN0x** [comment]
Hello, I just tested this on latest master and the issue is still occuring.

Message sent from `456-456-4567` to `911`:
![image](https://user-images.githubusercontent.com/27494805/164778309-808b74f5-0149-450f-bfb9-d2fed01a2cb0.png)
![image](https://user-images.githubusercontent.com/27494805/164778328-39bfd240-8bc3-4cb4-ba64-33d0ca445f2d.png)

The code I used with the export:
![image](https://user-images.githubusercontent.com/27494805/164778384-b32fec46-b5e5-4763-bd89-632bf05f8ae8.png)
The result:
![image](https://user-images.githubusercontent.com/27494805/164778425-3e247e0c-e554-4cc9-b947-20964ac246ff.png)

**Comment by itschip** [comment]
Thanks. I'll look into it.

**Comment by Mojito-Fivem** [comment]
64dfd1242e8037b9f041a889bcaa4b286ec154c2 should fix this on develop

**Comment by AvaN0x** [comment]
Thanks!
I just tested this and it worked.

--- 

PS: the silly logs still display the wrong tgtPhoneNumber:
![image](https://user-images.githubusercontent.com/27494805/165352515-e05bad1b-60f5-4bc3-baf0-229cae3568db.png)
![image](https://user-images.githubusercontent.com/27494805/165352850-3f9dc1ac-0a63-4121-b005-053321da58ee.png)
While the event display the right one:
![image](https://user-images.githubusercontent.com/27494805/165352548-d079fe9b-4930-4ddf-80f2-dc80c0655b89.png)

*Just thought it was worth pointing it out, even though it does not block the export from working.*

**Comment by Mojito-Fivem** [comment]
> Thanks! I just tested this and it worked!
> 
> PS: the silly logs still display the wrong tgtPhoneNumber: ![image](https://user-images.githubusercontent.com/27494805/165352515-e05bad1b-60f5-4bc3-baf0-229cae3568db.png) ![image](https://user-images.githubusercontent.com/27494805/165352850-3f9dc1ac-0a63-4121-b005-053321da58ee.png) While the event display the right one: ![image](https://user-images.githubusercontent.com/27494805/165352548-d079fe9b-4930-4ddf-80f2-dc80c0655b89.png)

Yeah it will do that because we had to change the approach to determining the target, group chat integration broke this export since there's no such thing as a "target number" anymore so we're just getting the target from the converation ID. This export will only work for 1 on 1 PMs for now.
