### ISSUE TITLE
Bug: Calling Via Messages App

### ISSUE THREAD

**Issue by CloakedManz** [project-error/npwd#681]
### Development Issue

Yes

### Phone Version

Latest Version

### Issue Description

When you are in the Messages app, if you try to call someone with the phone icon in the top right corner, it says "You cannot call your own number."

### Issue Reproduction

1. Open Phone
2. Open Messages
3. Select A Contact For Messaging
4. Click The Call Button In The Top Right
5. Error Should Reproduce

### Evidence

N/A

**Comment by Deniel00** [comment]
Valid problem in v1.2.3
![kép](https://user-images.githubusercontent.com/12788940/160256059-a1dd119f-2597-476f-9c31-95c301645fbb.png)

**Comment by AvarianKnight** [comment]
This was fixed in https://github.com/project-error/npwd/pull/671/commits/99be15b2d43343084548245c959dbd999d400a7a
