### ISSUE TITLE
Enhancement: Matchmaker app should use the built in gallery like other apps instead of external URL

### ISSUE THREAD

**Issue by pstomi** [project-error/npwd#682]
### Application

Matchmaker

### Dependency

No

### Feature Description

Matchmaker app should use the built-in gallery like other apps instead of external URL. Using external URL allows people to use NSFW pictures at their matchmaker profile.

**Comment by itschip** [comment]
Should it *only* use the gallery?

**Comment by itschip** [comment]
Fixed.
