### ISSUE TITLE
Bug: duplicate call history

### ISSUE THREAD

**Issue by Deniel00** [project-error/npwd#695]
### Development Issue

No

### Phone Version

v1.2.7

### Issue Description

Call history duplicated entry in nui, because in database had one entry, because after relog show only one entry.

### Issue Reproduction

1. Call someone
2. End call

### Evidence

![kép](https://user-images.githubusercontent.com/12788940/160642101-ddb1773a-df5a-44e2-b7ce-6f94eb9cdafa.png)
![kép](https://user-images.githubusercontent.com/12788940/160642136-17069131-76f9-40b1-8cb8-05094d28d5bf.png)
![kép](https://user-images.githubusercontent.com/12788940/160642369-397f175f-49de-424b-9666-9d4ffe3c08cb.png)

**Comment by itschip** [comment]
Does this only happen when you call someone that accepts? Or if you try to call someone, then end the call?

**Comment by Deniel00** [comment]
-  I'm call someone
- he/she accept call
- after some second end all

You can check this in database row

**Comment by itschip** [comment]
@Deniel00 Should be fixed in 1.2.8

**Comment by Deniel00** [comment]
Fixed in v1.2.8
