### ISSUE TITLE
Bug: stuck in nui if want accept call from notification bar

### ISSUE THREAD

**Issue by Deniel00** [project-error/npwd#696]
### Development Issue

No

### Phone Version

v1.2.7

### Issue Description

Block buttons (?)
If probaly accept call from notification bar blocking buttons (like cant walk, cant close phone with f1)

### Issue Reproduction

1. wait for call
2. get up phone (with f1)
3. accept call from notification bar

### Evidence

![kép](https://user-images.githubusercontent.com/12788940/160677595-28c6bb62-5f1e-4516-a841-050e1215869a.png)

**Comment by itschip** [comment]
I was able to reproduce it when I end the call right away. Seems like it's not picking up whatever.

**Comment by itschip** [comment]
1.- Open the phone (And keep it open)
2.- Tell someone to call u and cancel the call (you (1) keep the phone opened)
3.- You get the call stuck on the notification bar

From @YisusOnDev

**Comment by itschip** [comment]
#670

**Comment by Deniel00** [comment]
It's different from #670
in 670 call stuck in notification bar
in this lose control of character (can't move with character, can't toogle phone), but it fix if type `phone` command on console

Today probably repro this bug and reproduce, but still can't reproduce this

**Comment by itschip** [comment]
I think we'll have to tear call functionality apart and see what's going on. It's a shitshow of unreadable code, most of it.

**Comment by Deniel00** [comment]
Then no post new bug with call? 😅

**Comment by itschip** [comment]
@Deniel00 if you know of any other issues, please let me know here.

**Comment by itschip** [comment]
@Deniel00 Removed the notification alert since we already force you to be in the call modal. You should only see an alert when the phone is closed. See 1.2.8

**Comment by Deniel00** [comment]
We will check today after 2pm

**Comment by Deniel00** [comment]
Message order fixed and.. console.log :D 
![kép](https://user-images.githubusercontent.com/12788940/161259877-f9950671-af8c-4f8f-9d5c-fa4b34ca9832.png)

**Comment by Deniel00** [comment]
Tested.
Fixed.
