### ISSUE TITLE
Bug: div with buttons spacing problem in the settings app

### ISSUE THREAD

**Issue by pierrearma** [project-error/npwd#697]
### Development Issue

Unsure

### Phone Version

1.2.7

### Issue Description

There is a problem of spacing that changes when you open the "settings" app. This problem appears only in this app (or the problem is everywhere except in this application depending on the point of view).

### Issue Reproduction

1. Open the phone
2. Open settings app
3. Close settings app

### Evidence

Normal spacing:
![image](https://user-images.githubusercontent.com/46777166/160924514-391da1ad-3d76-435c-9b7f-2f76283f403b.png)

Spacing in settings app:
![image](https://user-images.githubusercontent.com/46777166/160924633-1d323aad-a536-4d8c-b536-404f0ca0976f.png)

**Comment by LukeWasTakenn** [comment]
This issue seems to be caused by the padding on the mui's list items pushing down on the bottom navigation component.

Removing one or more settings items seems to fix the sizing but adding a settings item doesn't do anything.
