### ISSUE TITLE
Bank Transfer

### ISSUE THREAD

**Issue by Talithaald** [project-error/npwd#698]
### Application

Other

### Dependency

Yes

### Feature Description

An App that allows people to transfer their Bank Money to other Players (needs to be online for ID) or Offline through Phone Number. 

### References

as far as I remember gcphone has Bank Transfer, didn't found any video about it tho, I don't mind posting a recording of the phone tomorrow when I'm on my computer

**Comment by itschip** [comment]
It is being developed at the moment.

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by ixhal** [comment]
Hey just wondering the current status on this as I am wanting to use the phone but without the banking app its pretty hard to replace our existing phone, Thanks!

**Comment by itschip** [comment]
> Hey just wondering the current status on this as I am wanting to use the phone but without the banking app its pretty hard to replace our existing phone, Thanks!

@ixhal as soon as the bank resource and microfrontend solution is done, we'll be able to add the bank app.
