### ISSUE TITLE
Bug: Matchmaker app - show people many times 

### ISSUE THREAD

**Issue by Deniel00** [project-error/npwd#703]
### Development Issue

No

### Phone Version

v1.2.8

### Issue Description

A, throws the same person many times.

### Issue Reproduction

1. just use app and you will see one person many times

### Evidence

![kép](https://user-images.githubusercontent.com/12788940/161317120-cb16c611-193a-40b8-848b-b4ab639c2fe6.png)

**Comment by itschip** [comment]
Currently introducing pagination for viewing matches. I'll look into this later.

**Comment by itschip** [comment]
@Deniel00 Please test this in 1.2.91

**Comment by Deniel00** [comment]
Next day will test it.

**Comment by Deniel00** [comment]
After update to 1.2.91 got this error: 
![kép](https://user-images.githubusercontent.com/12788940/163021078-05c019e5-71d3-469f-9382-cdad3fea2eb5.png)

**Comment by itschip** [comment]
@Deniel00 Could you try 1.2.92?

**Comment by Deniel00** [comment]
Same result in 1.2.92: (reseted db for cleary result)
![kép](https://user-images.githubusercontent.com/12788940/164260185-a12a8be1-fcda-4d7a-a873-f5863b0ee5f1.png)

**Comment by itschip** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Deniel00** [comment]
i'm think it's an angry `AAAAA...`

**Comment by itschip** [comment]
I'll check it out today or tmrw @Deniel00 :) Thanks

**Comment by Deniel00** [comment]
Maybe try this?
(https://github.com/project-error/npwd/blob/master/resources/server/match/match.db.ts#L22)
```
const query = `
  SELECT npwd_match_profiles.*,UNIX_TIMESTAMP(npwd_match_profiles.updatedAt) AS lastActive,Matches.createdAt FROM npwd_match_profiles 
  LEFT OUTER JOIN (SELECT id,`profile`,createdAt FROM npwd_match_views WHERE identifier = ? GROUP BY `profile`) AS Matches 
  ON npwd_match_profiles.id = Matches.profile
  WHERE npwd_match_profiles.identifier != ? AND (Matches.createdAt IS NULL OR DATEDIFF(CURRENT_DATE,Matches.createdAt) > 7) ORDER BY npwd_match_profiles.updatedAt DESC;
  LIMIT 25
`;
```
I'm tested both sql from your code, and this, and give same result.
