### ISSUE TITLE
Enhancement: distress message

### ISSUE THREAD

**Issue by minirovi95** [project-error/npwd#706]
### Application

Messages

### Dependency

No

### Feature Description

It would be great to implement the rescue system so that when someone dies, by pressing a key they can notify the ambulance since without this in the roleplay it is not in good taste...

**Comment by itschip** [comment]
This can easily be done without a phone.

**Comment by mr-capy** [comment]
> This can easily be done without a phone.

How its really helpful if u can provide some detail coz i am using this phone just due to distress
