### ISSUE TITLE
Help: Need Help Photo

### ISSUE THREAD

**Issue by minirovi95** [project-error/npwd#707]
I need help because I can't get the photos to be saved in the gallery... can someone help me please ?
![movilerror](https://user-images.githubusercontent.com/66905783/161377070-c7ebc550-28ba-4d56-a477-e5596fa89643.png)

**Comment by itschip** [comment]
Your config is most likely wrong. See docs.

**Comment by Deniel00** [comment]
Miss configuration not issue/bug
Please join to discord for faster help what you find on https://projecterror.dev/docs/ under `Community Links`
