### ISSUE TITLE
Your config is most likely wrong. See docs.

### ISSUE THREAD

**Issue by minirovi95** [project-error/npwd#708]
Your config is most likely wrong. See docs.

_Originally posted by @itschip in https://github.com/project-error/npwd/issues/707#issuecomment-1086688670_

I have read everything, I have your screenshot and everything and it still doesn't work for me, in the config option of: authorizationPrefix": "Client-ID", in the clientid do I have to put my imgur id?

**Comment by itschip** [comment]
The key `authorizationPrefix` in the config needs the value `Client-ID`. Your Client ID from imgur needs to be added as a convar in the *.cfg file you have.

**Comment by Deniel00** [comment]
Miss configuration it not issue/bug
Please join to discord for faster help what you find on https://projecterror.dev/docs/ under `Community Links`
