### ISSUE TITLE
Bug: Failed to get or create profile, input.replace is not a function

### ISSUE THREAD

**Issue by TheDiego845** [project-error/npwd#710]
### Development Issue

Unsure

### Phone Version

1.2.9

### Issue Description

I am using the latest version of npwd with esx-npwd in the latest version of legacy I have the error
Also i cant open the phone
[         script:npwd] [NPWD] [twitter] [error]: Failed to get or create profile, input.replace is not a function

### Issue Reproduction

Install npwd on latest version

### Evidence

![image](https://user-images.githubusercontent.com/69425536/161998924-f817dab4-16e9-41a4-8c85-9723b639d8dc.png)

**Comment by itschip** [comment]
@TheDiego845 Can you try 1.2.91

**Comment by TheDiego845** [comment]
![image](https://user-images.githubusercontent.com/69425536/162390678-d35e0331-7844-4b63-aeda-bdd9fa341bc1.png)
I have the same error

**Comment by TheDiego845** [comment]
bru
