### ISSUE TITLE
Enhancement: Dark Chat with Anonymous users

### ISSUE THREAD

**Issue by Haidee-hm** [project-error/npwd#713]
### Application

Other

### Dependency

No

### Feature Description

I would love to see the ability to use Dark Chat where the users are anonymous.

**Comment by itschip** [comment]
Would it be ideal to *not* receive notifications for such an app? Also, how would joining of groups work? IDs or named groups? I do believe GCPhone used some int ID with a # prefix. Is that preferred or should we attack this from another angle?

**Comment by VacEx0** [comment]
> Would it be ideal to _not_ receive notifications for such an app? Also, how would joining of groups work? IDs or named groups? I do believe GCPhone used some int ID with a # prefix. Is that preferred or should we attack this from another angle?

Dont know why the discussion stopped here, I'd love to see a "Dark Web" type app myself.

• I think similar to twitter you should be able to set it to all, mentions only, or none for the notifications.
• If by "joining of groups" you mean entering a secret chat. I think it would instead be interesting to have one central public chat like twitter where everyone can see every message in there. Bonus if you could add group chats / dms alongside it, in which case some secret token should be used to enter the group. Token would consist of numbers and letters: `N76HD562HJT`.

• If the apps chat is made public like twitter for everyone, consider having the app disabled by default and a client sided export should be called to enable it for example. This would then make it possible to put the app on only civilian phones, or even have a secret item for the phone which would add the app if used (in economy frameworks). All of this would have to be programmed by the server owner however. So maybe add a config option to enable / disable that functionality. 

Just throwing out ideas here :)

**Comment by itschip** [comment]
fuck off bot

**Comment by WEEZOOKARP** [comment]
Lol

**Comment by itschip** [comment]
https://github.com/project-error/npwd/pull/837 PR for darkchat
