### ISSUE TITLE
Bug: Reducing server console spam

### ISSUE THREAD

**Issue by Haidee-hm** [project-error/npwd#714]
### Development Issue

Unsure

### Phone Version

Apr 2, 2022 commit beffa2e

### Issue Description

Every message sent with the phone has a server console broadcast, despite the Debug enabled being set to false.  Can this certain message please be disabled when this is set to false?

### Issue Reproduction

1. Install phone - set Debug level: error, Debug enabled: false, Debug sentryEnabled: false
2. Wait for someone to send a text message to another player or a Tweet.
3. See server console spam.

### Evidence

![spam](https://user-images.githubusercontent.com/44797604/162146674-0b60b995-2aa4-4c3a-bde6-905dd5009d86.PNG)

**Comment by itschip** [comment]
I think this is fixed in develop or so.

**Comment by itschip** [comment]
Fixed in 1.2.91
