### ISSUE TITLE
Bug: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by csrpfivem** [project-error/npwd#715]
### Development Issue

Unsure

### Phone Version

Release 1.2.91

### Issue Description

Next error is showing in F8 console right after connection to server / spawning character:

`TypeError: Cannot read property 'length' of undefined (@npwd/resources/html/static/js/main.b672e25e.js:2)`

Error shows only 1 time. 

Additionally, when I'm trying to open the phone it triggers only player animation with prop and no UI is shown, and no errors.
### Issue Reproduction

1. Delete previous `npwd` folder and database.
2. Add 1.2.91 `npwd` and database
3. Connect to server and see error. 

### Evidence

![image](https://user-images.githubusercontent.com/85900432/162281367-f6c5fade-8825-43a5-93b9-388490a00810.png)

**Comment by csrpfivem** [comment]
![image](https://user-images.githubusercontent.com/85900432/162282296-be87632a-e5b6-4cf3-bf2f-4ececdfeca39.png)

**Comment by itschip** [comment]
@csrpfivem no server errors?

**Comment by csrpfivem** [comment]
> @csrpfivem no server errors?

No server errors unfortunately.

**Comment by itschip** [comment]
I'll look into it today.

**Comment by itschip** [comment]
@csrpfivem Can check if this is still an issue with 1.3.1
