### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by AayanAsim746** [project-error/npwd#716]
Whenever i open the phone it just shows a notification that tommy sent a message and does not shows the phon
![Screenshot 2022-04-08 172617](https://user-images.githubusercontent.com/77937350/162434979-2bf6704e-90ad-49f1-af6b-2661fb0872ba.jpg)
e

**Comment by itschip** [comment]
Tommy! Fucking Tommy!

**Comment by itschip** [comment]
I hate that guy!

**Comment by anes66** [comment]
> I hate that guy!

nooo he is a good guy xD
