### ISSUE TITLE
Match error

### ISSUE THREAD

**Issue by GeerdoDaGr8** [project-error/npwd#719]
### Development Issue

Yes

### Phone Version

1.2.91

### Issue Description

Not sure what the issue it but i am getting this on my server console quite a bit.

### Issue Reproduction

I believe this is just when going through match

### Evidence

![image](https://user-images.githubusercontent.com/56656726/163242234-e5a3acd1-ad69-40e1-8c54-b0017ff047ef.png)

**Comment by itschip** [comment]
@GeerdoDaGr8 Could you test 1.2.92?

**Comment by GeerdoDaGr8** [comment]
so far I am not seeing the error anymore but I i am getting this a lot now
[         script:npwd] [NPWD] [messages] [error]: Failed to broadcast message, Error: Cannot read properties of undefined (reading 'identifier')

**Comment by itschip** [comment]
Hm, does this only happen when you try to send a message to someone that is offline?

**Comment by itschip** [comment]
We should probably only display a warning or just some debug print.

**Comment by itschip** [comment]
@GeerdoDaGr8 Can you test this on the last release?
