### ISSUE TITLE
Bug: Script Error

### ISSUE THREAD

**Issue by erayko-dev** [project-error/npwd#721]
### Development Issue

Unsure

### Phone Version

1.x.x

### Issue Description

I just get this issue

### Issue Reproduction

idk tbh

### Evidence

![image](https://user-images.githubusercontent.com/76734458/163650566-3b259f8e-52da-4008-afca-75f85907798d.png)

**Comment by itschip** [comment]
@erayko-dev Make sure you download the release, not the source code.

**Comment by erayko-dev** [comment]
trying now @itschip :)

**Comment by erayko-dev** [comment]
no errors however, I want to change the toggle to "m" I changed every f1 I found to small and capital M but nothing, any help?

**Comment by itschip** [comment]
@erayko-dev The key is already registered for you as f1. You'll have to change it in-game. As for new users, it'll be "m"

**Comment by erayko-dev** [comment]
got that to work but 
![image](https://user-images.githubusercontent.com/76734458/163654609-78c3c481-f3ec-40e8-a5da-f426198fe6b2.png)

**Comment by erayko-dev** [comment]
no phone?

**Comment by itschip** [comment]
client or server error?

**Comment by erayko-dev** [comment]
nothing @itschip

**Comment by erayko-dev** [comment]
nvm, I get this:
![image](https://user-images.githubusercontent.com/76734458/163654878-a98411ba-67cf-431d-92af-46cbc3587f11.png)

**Comment by erayko-dev** [comment]
also this 
![image](https://user-images.githubusercontent.com/76734458/163655747-b7dac632-a932-492e-b1e6-1981f2851888.png)

**Comment by itschip** [comment]
yeah, i think it's quite clear what the issue is then

**Comment by itschip** [comment]
and use the discord for more support questions.
