### ISSUE TITLE
Enhancement: Preview of sounds in settings

### ISSUE THREAD

**Issue by Fripplo** [project-error/npwd#724]
### Application

Settings

### Dependency

No

### Feature Description

- a sound preview(a beep or whatever) on the volume while adjusting it on notification or ringtone.
- a sound preview(a play-button on the right side of the sound) when changing ringtone/notification so you know how it sounds without having to tell someone to call you just to know how it sounds like.

**Comment by itschip** [comment]
@Mojito-Fivem is this something you'd like to do before we merge #725

**Comment by Mojito-Fivem** [comment]
The sound volume doesn't really exist with the native implementation but I can look at adding a preview button to play a short clip of each sound.

**Comment by Mojito-Fivem** [comment]
Added in commit 8f4daf382fb239cc1557cc2d0a408aa9ea5deb31
