### ISSUE TITLE
a Consult:for my language

### ISSUE THREAD

**Issue by dingyu1126** [project-error/npwd#727]
![微信截图_20220423123650](https://user-images.githubusercontent.com/64310374/164877822-107dc2f9-af71-4be1-b16a-96c0fff1b95b.png)

**Comment by itschip** [comment]
Yes, you can create a Pull Request with changes to a language or create a translation for a new language.

**Comment by itschip** [comment]
FYI as long as there are no translation for this key for the language you're using, it wil default to English. Closing this for now.
