### ISSUE TITLE
Enhancement: Add Papirus Icons

### ISSUE THREAD

**Issue by VictorFeroli** [project-error/npwd#728]
### Application

Other

### Dependency

No

### Feature Description

Add [papirus](https://github.com/PapirusDevelopmentTeam/papirus_icons) android icon pack, to icon alternatives:

- [Twitter](https://github.com/PapirusDevelopmentTeam/papirus_icons/blob/master/src/apps_twitter.svg)
- [MatchMaker](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/apps/tinder.svg)
- [Text Messaging](https://github.com/PapirusDevelopmentTeam/papirus_icons/blob/master/src/system_messages.svg)
- [Calling](https://github.com/PapirusDevelopmentTeam/papirus_icons/blob/master/src/system_phone.svg)
- [Marketplace](https://github.com/PapirusDevelopmentTeam/papirus_icons/blob/master/src/apps_sber_market.svg) *(I couldn't find a better icon)*
- [Camera](https://github.com/PapirusDevelopmentTeam/papirus_icons/blob/master/src/system_camera.svg)
- [Contacts](https://github.com/PapirusDevelopmentTeam/papirus_icons/blob/master/src/system_contacts.svg)
- [Notes](https://github.com/PapirusDevelopmentTeam/papirus_icons/blob/master/src/system_notes.svg)
- [Calculator](https://github.com/PapirusDevelopmentTeam/papirus_icons/blob/master/src/system_calculator.svg)
- [Settings](https://github.com/PapirusDevelopmentTeam/papirus_icons/blob/master/src/system_settings.svg)

**Comment by itschip** [comment]
Would be nice if you could link some of the icons you'd like to have.

**Comment by VictorFeroli** [comment]
Done!
