### ISSUE TITLE
Bug: Error Sending messages

### ISSUE THREAD

**Issue by AMWARNING** [project-error/npwd#730]
### Development Issue

Unsure

### Phone Version

1.2.93

### Issue Description

When i try to send a message (one-to-one) it gives me a error

### Issue Reproduction

  1. Go to Contacts
  2. Click on Message icon
  3. Click on Send Message

OR

 1. Open Matchmaker
 2. Go to matches
 3. Click on the message icon
 4. Send message
 5. See error

### Evidence

Streanable down at the moment so i uploaded the video in another storage platform

Link: https://files.fm/u/ax2bfwt62

**Comment by Mojito-Fivem** [comment]
Can't reproduce

**Comment by AMWARNING** [comment]
Try this one https://www.veed.io/view/c5ae50ff-57b9-446a-88f6-04931ce0d308?sharingWidget=true

**Comment by Mojito-Fivem** [comment]
That's the same video

**Comment by AMWARNING** [comment]
Any clue of how i get this?

**Comment by Mojito-Fivem** [comment]
Without you showing anything, no

**Comment by itschip** [comment]
@AMWARNING , are you sure there aren't any server console errors at all?

**Comment by AMWARNING** [comment]
the problem is exacly that, i don't have something to show you, there are no errors

**Comment by AMWARNING** [comment]
@itschip sure

**Comment by itschip** [comment]
@AMWARNING I'll release a patch note that might help displaying an error. I'll let you know when its out.

**Comment by itschip** [comment]
@AMWARNING try this: https://github.com/project-error/npwd/releases/tag/1.2.94

**Comment by AMWARNING** [comment]
Thank you 4 your help, it gave me errors and ill fix them, it was db problems
