### ISSUE TITLE
Slice error with fillnewcontact export

### ISSUE THREAD

**Issue by Chubbbs** [project-error/npwd#737]
![image](https://user-images.githubusercontent.com/30705242/165584348-ba3228c1-79d6-465f-b198-f11e24f4e80e.png)

`exports.npwd:fillNewContact({ name = fullname, phone = SuggestionData.phone, avatar = 'https://i.imgur.com/rADs9v9.png' })`

**Comment by Mojito-Fivem** [comment]
The correct syntax is
```ts
// Data Struct
interface AddContactExportData {
  name?: string;
  number: string;
  avatar?: string;
}
```

**Comment by Chubbbs** [comment]
ass you see in the suggestiondata table it's all strings that are going into that. It's giving me a slice error still

**Comment by Chubbbs** [comment]
I even tried it with the example to see if that would work and still gets a slice error.o

**Comment by Mojito-Fivem** [comment]
Your data doesn't match the interface

**Comment by Chubbbs** [comment]
@Mojito-Fivem 
![image](https://user-images.githubusercontent.com/30705242/166070287-dabbee54-a83d-4691-8cce-5677bb050c64.png)

`exports.npwd:fillNewContact({ name = "test", phone = "123", avatar = "https://i.imgur.com/rADs9v9.png" })`

exact code I used
