### ISSUE TITLE
Enhancement: Timestamps in text messages

### ISSUE THREAD

**Issue by menkzy** [project-error/npwd#739]
### Application

Messages

### Dependency

No

### Feature Description

When reading text messages, it's difficult to know when a text message is received and looks like a wall of text.
It would be nice to know when the text message was sent/received, next to where it has the sender name, in this [screenshots](https://i.imgur.com/DG5wJRO.png) case next to UNKNOWN. 

It'd be nice for RP servers, as some people aren't active and spend time away from the server.

**Comment by itschip** [comment]
Added in d9e9d01260e9b71706a74a400b5b736135b48912
