### ISSUE TITLE
emitMessage create nui error: reloging after using the export creates nui error

### ISSUE THREAD

**Issue by PlouffeLuL** [project-error/npwd#742]
### Development Issue

Unsure

### Phone Version

1.2.96

### Issue Description

Reloging after receiving custom messages creates nui errors after using the same number to send the export

### Issue Reproduction

1: Send a message using any phone number
2: relog (you're going to have 2 convos)
3: Delete the convo (Not sure if nescessary)
4: Re send a message using the same phone number
5: Nui error

### Evidence

https://streamable.com/mpiwfw

**Comment by Mojito-Fivem** [comment]
Can you see if 07a8a8dff6e9ef677f39993ae14ca0155c699101 on develop fixes this ?

**Comment by PlouffeLuL** [comment]
So it seems like it fix half of it. I dont get the issue on relog and the conversation dont seem to be duplicated anymore.

But if i delete the conversation i still get the same error.

```
[    381141] [b2545_GTAProce]        CrBrowserMain/ Uncaught TypeError: Cannot read property 'id' of null (@npwd/resources/html/static/js/main.a2f0510c.js:2)
[    384469] [b2545_GTAProce]        CrBrowserMain/ Uncaught TypeError: Cannot read property 'unread' of undefined (@npwd/resources/html/static/js/main.a2f0510c.js:2)
```

**Comment by Mojito-Fivem** [comment]
Wouldn't it be nice to have source maps because I don't really have an idea of where in the frontend that's coming from
