### ISSUE TITLE
Enhancement: Crypto App

### ISSUE THREAD

**Issue by TonybynMp4** [project-error/npwd#744]
### Application

Other

### Dependency

Yes

### Feature Description

A Crypto App like QB-Phone's that lets players :

-  **Buy** 
-  **Sell**
-  **Exchange crypto currencies**
-  **See the STONKS and the NOTSTONKS of the currency**
-  **Transaction history for the player**

definitely very dependent on the framework but if the bank app could work why not this one !
(also kinda important for some QB scripts so that's why i ask lol)
Chip said it could be possible on his stream so here i am :p

### References

QB-Phone's App for reference:
![image](https://user-images.githubusercontent.com/97451137/166127207-27c6d532-779d-431a-ad27-cd104092a88d.png)

**Comment by Mojito-Fivem** [comment]
This has been requested a few times, this is too framework dependent and npwd is framework agnostic. Once module federation is incorporated this will allow qb developers to create their own apps for npwd as separate resources.
