### ISSUE TITLE
Bug: can't open phone

### ISSUE THREAD

**Issue by DutchMods** [project-error/npwd#746]
### Development Issue

Yes

### Phone Version

i tried it with the newest versions and all of them did give me the same error  

for now i tried versions:
[1.2.97](https://github.com/project-error/npwd/releases/tag/1.2.97)
[1.2.95](https://github.com/project-error/npwd/releases/tag/1.2.95)

### Issue Description

when i try to open my phone it won't let me, only after opening my map and closing it again all parts of the phone work as intended. i have no other errors exept that one.

### Issue Reproduction

1. downloaded the script
2. started it and forgot the database 
3. implemented the database
4. got error from database so made changes `'utf8mb4_general_ci'`
5. joined my server and couldn't open my phone

### Evidence

https://streamable.com/ojw3xb
![image](https://user-images.githubusercontent.com/104724906/166436224-4538a529-d24c-4968-a283-54b6badaaf5f.png)

**Comment by itschip** [comment]
@DutchMods Have you tried to clear your local storage in nui_devtools?

**Comment by itschip** [comment]
It might be that we have some unused values in our scheme, but try and clear it first. I'll look into it later, unless someone else does it :)

**Comment by DutchMods** [comment]
> 
maybe a dumb question but i don't have acces to nui_devtool command and don't see it in tools how can i fix this?

**Comment by wowjeeez** [comment]
> > 
> 
> maybe a dumb question but i don't have acces to nui_devtool command and don't see it in tools how can i fix this?

Either use the Canary channel, or turn on developer mode by starting FiveM with `+set moo 31337`

**Comment by DutchMods** [comment]
and how do i start fivem with that?

**Comment by wowjeeez** [comment]
Just edit the FiveM shortcut like so:
`C://path/to/fivem/FiveM.exe +set moo 31337`

**Comment by DutchMods** [comment]
yes thanks that worked now where do i clean the locas storage?

**Comment by wowjeeez** [comment]
same as you would in Google Chrome/Any chromium based browser (Application tab)

**Comment by DutchMods** [comment]
Okay i followed the steps on your FAQ on how to clean the storage, i have done that but the error stays there so i don't know what to do.

**Comment by itschip** [comment]
@DutchMods Thanks for testing it out atleast. Ill look into it later today.

**Comment by Racpy** [comment]
I think problem is in cl_controls ?
start to line 48.
I use ESX framework, the latest esx-npwd work fine the as Item in inventory
but when you enter PauseMenu, it will break the as Item function.
example: The phone is not in inventory and should not be able to be toggle on, but you can still toggle on after you enter PauseMenu and close.

**Comment by itschip** [comment]
@DutchMods Can you confirm that this is still an issue with 1.3.1?

**Comment by Sarbatore** [comment]
> .

I have this issue also

**Comment by itschip** [comment]
The screenshot provided by @DutchMods in the first comment is not an issue. You most likely have some server errors.
