### ISSUE TITLE
Bug: Failed to store phone number

### ISSUE THREAD

**Issue by kadins1** [project-error/npwd#752]
### Development Issue

Unsure

### Phone Version

Release 1.0

### Issue Description

When starting my server, I get a message that says:
[         script:npwd] [NPWD] [player] [error]: Failed to store phone number in database
[         script:npwd] [NPWD] [player] [error]: UPDATE users SET phone_number = 493-336-1695 WHERE identifier =*********
The stars being my steam hexadecimal
I have went into the FAQ, I followed the installation, I installed pe-core and imported all sql files, I have a great database that works fine.

### Issue Reproduction

This happens every time I start my server, as soon as it is fully started, it can be seen in the console.

### Evidence

![image](https://user-images.githubusercontent.com/66336559/167324911-72f83ca0-903e-4552-8a82-2b30afa314aa.png)

**Comment by TheConwayy** [comment]
I've been having the same issue as well!

**Comment by hellyet** [comment]
+

**Comment by itschip** [comment]
Either your db config for npwd is wrong, or you're not storing users in your db.

**Comment by itschip** [comment]
If you're running some 'menu server', and you're not handling players at all, use 'pe-core' to handle it.

**Comment by hellyet** [comment]
your sql request is wrong!
i replaced line 34741 in [server.js](https://github.com/project-error/screenshot-basic/blob/master/dist/server.js)
```const updateQuery = `INSERT INTO \`${config2.database.playerTable}\`(\`${config2.database.phoneNumberColumn}\`, \`${config2.database.identifierColumn}\`) VALUES (\'?\',\'?\')`;```

**Comment by itschip** [comment]
What exactly did you change?

**Comment by hellyet** [comment]
I changerd this line 
```const updateQuery = `UPDATE ${config2.database.playerTable} SET ${config2.database.phoneNumberColumn} = ? WHERE ${config2.database.identifierColumn} = ?`;```
to this
```const updateQuery = `INSERT INTO \`${config2.database.playerTable}\`(\`${config2.database.phoneNumberColumn}\`, \`${config2.database.identifierColumn}\`) VALUES (\'${gennedNumber}\',\'${identifier}\')`;```

**Comment by itschip** [comment]
Yeah, please don't do this. This is not the way to go about it. 

Please join the discord and we'll help you there. This is an issue on your side.

**Comment by hellyet** [comment]
Coudn't find a link

**Comment by itschip** [comment]
https://projecterror.dev/

**Comment by kadins1** [comment]
Alright, thanks everyone for the help!
