### ISSUE TITLE
Enhancement: Dynamically change twitter name and picture based on pre existing framework data.

### ISSUE THREAD

**Issue by VacEx0** [project-error/npwd#753]
### Application

Twitter

### Dependency

No

### Feature Description

Add the following exports:
```lua
-- Main Request:
> exports.npwd:setTwitterName("twitter_name")
> exports.npwd:setTwitterProfile("image_url")

-- Future Proofing, I guess:
> exports.npwd:getTwitterName() 	-- Returns players current twitter name.
> exports.npwd:getTwitterProfile() 	-- Returns players current twitter profile url.
```

And the following event:
```lua
-- Event to detect twitter profile changes. Should only fire if the user changes it, not a resource.
AddEventHandler('npwd:TwitterProfileChanged', function(data)
	local number = data.phoneNumber			-- Phone number of the person changing their twitter information.
	local old_name = data.oldName			-- Name before change
	local new_name = data.newName			-- Name after change
	local old_picture = data.oldPicture		-- Profile Picture before change.
	local new_picture = data.newPicture		-- Profile Picture after change.

    -- Code to store new name / profile picture into already existing frameworks database.
end)
```

***Twitter name and profile picture would be set after loading the player by pulling the info from a database, if the user changes their twitter info from the phone we would update it in the database with the event.***

**Why?**
Some frameworks, such as the one I use `(NAT2K15's Standalone Framework V2)`, store twitter information. It would be nice if the twitter app automatically changed your name and picture based on which character you are playing as.

If what I suggested becomes a feature though I would personally make my own resource and give it a separate database table, because my framework does not store profile pictures. The framework I use *does not* work with the phone by default, I had to modify its code, so if you're interested in seeing how i did that let me know. It is a paid resource so I cannot send any code I didnt personally add to the resource.

I have had users ask why the twitter app doesnt store twitter names which is why I am suggesting this. And making the phone automatically switch the name based on the characters name wouldnt work for my server, as their twitter names are ***mostly*** not their twitter name when making a new character.

---

**I am aware this may be overcomplicating things a bit, however this is all I can think of to make it possible on any framework including my own.**

**Comment by itschip** [comment]
We'll look into a solution for this, and update the issue as soon as we have something.

**Comment by VacEx0** [comment]
Sounds good, thanks!

**Comment by itschip** [comment]
@VacEx0 is this still an issue or a feature you would like to see?

**Comment by VacEx0** [comment]
> @VacEx0 is this still an issue or a feature you would like to see?

With the recent implementation of NPWD in the framework I use this has already been somewhat accomplished. However I am sure some other users of NPWD out there may have an arbitrary framework and would possibly like this if it were to be added.

With that being said I do not personally require such a feature any longer, but like I said it could be nice for others out there. Regardless this is already an amazing resource so take your time with any implementation or decision you make going forward in regards to this issue. 

Thank you! 😄

**Comment by itschip** [comment]
Thanks bot, you're doing a great job pissing me off.
