### ISSUE TITLE
Bug: Still changing phone numbers and can't save phone number to the database.

### ISSUE THREAD

**Issue by DodgeCZE** [project-error/npwd#754]
### Development Issue

Yes

### Phone Version

Latest

### Issue Description

Yesterday I Installed NPWD, everything works perfectly but when I restarted server It gives me error that "It failed to save number to the database' and then it will change the phone number. Before I have installed GCphone (Zap-Hosting ESX RP SERVER) and I literally don't know what to do with that so please help me :).

### Issue Reproduction

1.

### Evidence

![image](https://user-images.githubusercontent.com/105479208/168225280-457dd6cc-f150-456a-9d97-fe7a8335a18a.png)

**Comment by damian4092** [comment]
how did you fix it im a no framework sever with same issue
