### ISSUE TITLE
Light mode issues

### ISSUE THREAD

**Issue by IamLation** [project-error/npwd#756]
### Development Issue

Yes

### Phone Version

1.2.99

### Issue Description

On light mode, certain phone features are not updating correctly to make it properly usable. In the attached image(s) you can see the calculator app still utilizes a white background & fonts so numbers/buttons are not seen. In the second attachment is a picture of the browser app & the URL font color not updating but rather staying white & making it difficult to use/navigate.

![FiveM_b2372_GTAProcess_2022-05-14_11-49-22](https://user-images.githubusercontent.com/59341660/168439149-93071c6c-6bd1-431e-b083-dfffdf5bddfb.png)
![FiveM_b2372_GTAProcess_2022-05-14_11-51-40](https://user-images.githubusercontent.com/59341660/168439245-4ad5f760-aff7-4a00-932c-3b9df1240d5e.gif)

### Issue Reproduction

1. Open phone
2. Go to settings
3. Set phone theme to "Light"
4. Open Calculator or Browser.

**Comment by Mojito-Fivem** [comment]
@itschip tagging chip because he loves light theme

**Comment by itschip** [comment]
shit.

**Comment by Mojito-Fivem** [comment]
Should be fixed on develop 🙂
