### ISSUE TITLE
No audio/voice on phone calls

### ISSUE THREAD

**Issue by IamLation** [project-error/npwd#757]
### Development Issue

Unsure

### Phone Version

1.2.99

### Issue Description

When attempting to make a phone call, it works all fine & dandy until the receiver answers & neither of us can hear/speak on both ends of the call. No errors are received. Also using pma-voice of course.

### Issue Reproduction

1. Open the phone
2. Make a call
3. Try to speak

### Evidence

https://streamable.com/tsox2x

**Comment by UnaiAhedo** [comment]
I'm having the same problem, the voice chat and radio (pma-voice and rp-radio for pma) work great, but when making the call, I got no sound. Also no errors in server/client console.

**Comment by itschip** [comment]
Will look into it.

**Comment by UnaiAhedo** [comment]
Nevermind, in my case it's that I'm dumb and forgot to install the [esx_npwd](https://github.com/overextended/esx-npwd), try installing that and check it again @IamLation.

And sorry for the inconvenience @itschip.

**Comment by IamLation** [comment]
> Nevermind, in my case it's that I'm dumb and forgot to install the [esx_npwd](https://github.com/overextended/esx-npwd), if you forgot it like me, try installing that and check it again @IamLation.
> 
> And sorry for the inconvenience @itschip.

Hey, yes I just confirmed I have installed & started esx-npwd. Issue still persists.

**Comment by Cyril-Beeckman** [comment]
Update pma-voice, this fix the issue for me

**Comment by itschip** [comment]
Sounds about right. I looked through the docs now and we seem to up-to-date on our side on how we're integrating with pma-voice.

**Comment by dochardi** [comment]
Hello Wie use the last version of pma-voice and the voice not work how we can fix it

**Comment by kylemcshea** [comment]
Having slightly the same issue on my end. 
Setup - **esx-npwd**, **pma-voice**(connected to external mumble server) + npwd of course.

Several community members have voice calls that drop but with specific situations. 
I will send some bug reports here to add further information.

"when in a making call if you look at a tweet it bugs you and you cant hang up"
"Phone calls aren't always consistent with one person only being heard"

It is possible that the usage of apps can cause phone call failure. Does anybody else have this kind of issue?

**Comment by minipunch** [comment]
using latest pma voice helped me fix this also
