### ISSUE TITLE
error with phone

### ISSUE THREAD

**Issue by v4mp76** [project-error/npwd#759]
### Development Issue

No

### Phone Version

![image](https://user-images.githubusercontent.com/101667551/168860763-335f6127-bec5-4052-af78-39defa3f6bbf.png)

### Issue Description

Hello i have this issue in my console

### Issue Reproduction

I have this error in console

**Comment by Rav3n95** [comment]
Same here, using esx_multichar

**Comment by itschip** [comment]
Can I see your config.json and your database columns for the 'users' table?

**Comment by Rav3n95** [comment]
> Can I see your config.json and your table columns for 'users'?

Its happening because im using esx_multicharacter by Liden. So Char1: added before identifire. 

Thing is was working before, even esx_npwd drops error: 
No such export to npwd:newPlayer

**Comment by Rav3n95** [comment]
![image](https://user-images.githubusercontent.com/69343477/169713997-e3ab7481-d356-4c9e-85d5-65e8b6bdbfa6.png)

**Comment by Rav3n95** [comment]
![image](https://user-images.githubusercontent.com/69343477/169714108-62712c48-4576-4fc1-8ca0-8d88bd913e58.png)

**Comment by itschip** [comment]
@Rav3n95 set 'useResourceIntegration' to 'true'

**Comment by Rav3n95** [comment]
Fixed

**Comment by itschip** [comment]
@v4mp76 make sure you do the same.
