### ISSUE TITLE
Enhancement: matchmaker vs database

### ISSUE THREAD

**Issue by Spykespy** [project-error/npwd#761]
### Application

Matchmaker

### Dependency

No

### Feature Description

Hello,

Please give us an option to control how much crap gets thrown into the database. I love logging, but putting every single matchmaker view into a database is just a bit much.

![image](https://user-images.githubusercontent.com/40208312/168928788-2391f7cf-5c5d-4f4f-a4b4-6162ef4b1546.png)

![image](https://user-images.githubusercontent.com/40208312/168929225-28747479-69a8-449e-aa2e-e259a7f2fe5b.png)

As you can see, it's almost at 54mb, and over 292.000 rows of data. I understand that we can manually delete it ourselves or set up a system to do this automatically, but I don't know if this is a crucial part of the phone, so I don't want to take the risk. And either way we shouldn't have to bodge it like that. 

You're probably using this data to see if people matched, but I can't see why you wouldn't get away with a single row per user.

Is there a config option I missed? Or would it be possible to give us the option to just... not do this? Thanks in advance! :)

### References

Yeh, I can't see why you wouldn't store the matchmaker views in a string like this guy explains: https://www.youtube.com/watch?v=xvFZjo5PgG0

**Comment by itschip** [comment]
Thanks for the report. We'll look into it.

**Comment by itschip** [comment]
A "fix" have been pushed to develop. Should hopefully reduce the records by a lot

https://github.com/project-error/npwd/commit/73cc8dd80b62e9ed9d32408ed86555f2ecb46168
