### ISSUE TITLE
Bug: twitter profile duplication

### ISSUE THREAD

**Issue by Deniel00** [project-error/npwd#763]
### Development Issue

No

### Phone Version

1.2.95

### Issue Description

When want update Twitter profile name, script duplicate profile.
_(i'm geting more information about this.)_

### Issue Reproduction

1. Probably change name in Twitter app

### Evidence

![kép](https://user-images.githubusercontent.com/12788940/169701642-09f9f5a6-f02f-49f8-8a85-21213ff560ef.png)

**Comment by Deniel00** [comment]
I'm wrote bad version, correct: 1.2.98

**Comment by itschip** [comment]
@Deniel00 Please see if you can reproduce this issue on 1.5.0

**Comment by itschip** [comment]
Fixed in https://github.com/project-error/npwd/commit/fbab1480331555046831899672bb64a968797775

**Comment by Deniel00** [comment]
I'm checked on dev server, seems like its sloved. But today I update on prod server, will be check in 1-2 days.
