### ISSUE TITLE
Info bar appear when posting photos on twitter

### ISSUE THREAD

**Issue by baillianalexandre** [project-error/npwd#766]
### Development Issue

Yes

### Phone Version

https://github.com/project-error/npwd/releases/tag/1.2.99

### Issue Description

The info bar is always showing when I'm posting a photo on twitter

### Issue Reproduction

Take a photo from ur character's face, post it on twitter

### Evidence

https://i.imgur.com/2NOMXrm.jpg

**Comment by itschip** [comment]
I am unable to reproduce it.

**Comment by itschip** [comment]
@baillianalexandre You can test 1.3.1 and see if it still occurs.
