### ISSUE TITLE
useResourceIntegration

### ISSUE THREAD

**Issue by izMystic** [project-error/npwd#781]
### Development Issue

No

### Phone Version

1.3.1

### Issue Description

When useResourceIntegration is set to true the phone still expects there to be a user table, phone number column, etc

### Issue Reproduction

1. put useResourceIntegration to true
2. errors come in console about there not being a user's table

### Evidence

![Screenshot_20220613-195627_Microsoft Remote Desktop](https://user-images.githubusercontent.com/72127044/173466066-27eaa15f-ff87-42ee-bf7e-e64fee93368f.jpg)

**Comment by itschip** [comment]
Yes, we still expect a user table. The only difference is that 'useResourceIntegration' exposes a export (newPlayer) to get initial information about the player.
