### ISSUE TITLE
Enhancement: bank app

### ISSUE THREAD

**Issue by Missladee** [project-error/npwd#786]
### Application

Other

### Dependency

Yes

### Feature Description

I love the phone it is amazing, but something I feel it is lacking and I would love to see as an app is Banking App. A feature where we can see our account, current money, transfer money ect. Doesn't have to be super fancy but would be very useful. As many other phones have this and many people depend on it. 

Thank you for taking the time to read this. :)

**Comment by itschip** [comment]
This is being worked on.
