### ISSUE TITLE
Bug: phone number doesnt create on new character

### ISSUE THREAD

**Issue by Dejvi1** [project-error/npwd#793]
### Development Issue

Yes

### Phone Version

newest downloaded

### Issue Description

Im using legacy version and phone wont create phone number  value is null in users
I have esx_npwd resource and on connect its giving error on missing export in extended

### Issue Reproduction

1. i did installation as it was written on github
2. on esx 1.2 its working without any error
3. i tried many times to reinstall it to be sure im doing it right
4. error still occurs

### Evidence

![image](https://user-images.githubusercontent.com/58938630/175781411-62bfbdfb-8195-4dc0-8b9e-7e11cd14f3ca.png)

**Comment by Mojito-Fivem** [comment]
ESX is supposed to generate these numbers if I'm not mistaken

**Comment by Dejvi1** [comment]
yep it should automatically generate them on new registration but instead of it it throws error with update phone_number like screenshot shows

**Comment by itschip** [comment]
I guess your npwd config.json is has the wrong configuration.

**Comment by Dejvi1** [comment]
> I guess your npwd config.json is has the wrong configuration.

![image](https://user-images.githubusercontent.com/58938630/175834525-412140af-7e44-4389-ac77-8f49928196b1.png)

**Comment by itschip** [comment]
@Dejvi1 if you're using 'esx-npwd' as you mentioned, you'll need to set 'useResourceIntegration' to `true`.

**Comment by Dejvi1** [comment]
Ok, so issue with number was fixed, but now phone wont open when i join.
There is no error and works only when i restart resource..
I tried to put it under all resources in cfg also under extended etc but wont open until i restart it..
And after reconnect also wont open if i dont restart it

**Comment by itschip** [comment]
Does it open if you try opening the pause menu first? We seen some issues similar to what you're explaining. It could be something different, but I'd give it a try, just to confirm :)

**Comment by Dejvi1** [comment]
oh right it does work after that :O
Is there any way to fix that ?
Also thanks for help mate

**Comment by itschip** [comment]
@Dejvi1 We already have a fix for it. It'll be in the next release..
