### ISSUE TITLE
Bug: database error. maybe mariadb version not compatible?

### ISSUE THREAD

**Issue by boringwolf** [project-error/npwd#794]
### Development Issue

Unsure

### Phone Version

1.2.99

### Issue Description

I got this error when start the server.

```JSON
{"level":"error",
"message":"Error executing (SHOW TABLES WHERE `Tables_in_s81_es_extended`LIKE ? [\"users\"]) with error message Access denied for user 'u81_dIdBeCPR8S'@'172.18.0.2' (using password: YES)",
"module":"DBInterface",
"timestamp":"2022-06-25T16:16:20.940Z"}
```

and my mysql version
```
Server version: 10.6.8-MariaDB-1:10.6.8+maria~buster mariadb.org binary distribution
```

### Issue Reproduction

1. Use txAdmin Ox Base Template to create a Server
2. Start The Server
3. see this error
4. check the database config and permission.
5. restart the server
6. see error

**Comment by Mojito-Fivem** [comment]
This isn't an issue, either your password is incorrect or your password contains illegal characters
