### ISSUE TITLE
Bug: setPhoneDisabled export behavior 

### ISSUE THREAD

**Issue by frazz1234** [project-error/npwd#795]
### Development Issue

No

### Phone Version

last one

### Issue Description

exports.npwd:setPhoneDisabled(true)

is enable correctly, but when you press ESX, the phone can be use again whitout trouble . 

### Issue Reproduction

exports.npwd:setPhoneDisabled(true) after ESC and you can use

**Comment by Mojito-Fivem** [comment]
https://github.com/project-error/npwd/blob/ec573355f27c94cd026641c4c9d43b6dbd3de973/resources/client/cl_controls.lua#L48-L70
This lua code is causing this behavior, confirmed repro
