### ISSUE TITLE
Enhancement: endPhoneCall export

### ISSUE THREAD

**Issue by DarinBeard** [project-error/npwd#797]
### Application

Other

### Dependency

No

### Feature Description

there is a startPhoneCall export but no endPhoneCall export. I would like to see that added for a thing I am working on. Thanks.

**Comment by itschip** [comment]
@Mojito-Fivem sounds like something that would be easy enough to add, right?

**Comment by Mojito-Fivem** [comment]
Added with dfb33d5de1e5421b64537be7d435cc2b35a7e45c
