### ISSUE TITLE
Enhancement: Custom Identifiers

### ISSUE THREAD

**Issue by Demigod916** [project-error/npwd#798]
### Application

Other

### Dependency

No

### Feature Description

A configuration to use character identifiers outside of the normal things returned by GetPlayerIdentifiers(). my server for example uses an incremented database value as our character ids as a reference to everything in the characters user table to easily differentiate characters without having to do weird stuff with steam ids or game licensees for multi-character

**Comment by Mojito-Fivem** [comment]
We support this already, for example "qb-npwd" uses `citizenid` as its identifier.

**Comment by Demigod916** [comment]
I see. I guess my issue specifically is that i have citizen IDs built into a heavily modified ESX. And the citizen ID doesnt seem to be an option for the esx version currently. Which makes sense since its not in esx by default
