### ISSUE TITLE
Bug: Create new conversation with contact create a conversation with me

### ISSUE THREAD

**Issue by skrilax91** [project-error/npwd#803]
### Development Issue

Yes

### Phone Version

phone version 1.2.99
commit 14248fed9dcf3cde04eac978ddc914b27c6da402

### Issue Description

When i create a conversation with a friend contact, a conversation is created with our 2 numero (verified in DB) but tyhe conversation created take my phone number for name, and when i send message my friend receive it but can't close notification.
Also, he don't see the conversation and can't create conversation with me (saying that the conversation already exist).
For ending, when i close the conversation on my phone and re enter, all message sended are displayed on left, like if it was my friend message

### Issue Reproduction

add someone to your contact and create a conversation

### Evidence

https://streamable.com/9wl9dg

**Comment by frazz1234** [comment]
I will try it today.

I see an other bug, I'm using ESX legacy like I told you and ox inventory , I have everything set up good. 

But if I'm connect and I don't have the phone I can receive notifications from my phone when someone call. I can't answer.

**Comment by itschip** [comment]
Please try and reproduce it with 1.5.0.
