### ISSUE TITLE
Cant take pictures on camera or update twitter version

### ISSUE THREAD

**Issue by GlitchWeesocks** [project-error/npwd#808]
### Development Issue

Unsure

### Phone Version

I don't know the exact version, it is the most recent one

### Issue Description

It will not let me take pictures with my camera, when I get into the app there is just a +, if I click it nothing happens.
When I go onto twitter it tells me to make a name, when I try to make one it fails, Update: I also tried to open the marketplace app and it shows the error attached below.

### Issue Reproduction

1. Open phone
2. Open Camera App
3. Problem has occurred

1. Open Phone
2. Open Twitter App
3. Input Name
4. Press enter
5. Problem Occurs

### Evidence

![image](https://user-images.githubusercontent.com/75541042/180339100-d57c17ef-7d4a-4b2f-95fa-6af31a632e1b.png)
![image](https://user-images.githubusercontent.com/75541042/180339276-d2d99f5b-2866-4a79-96d4-f846f74365a2.png)
![image](https://user-images.githubusercontent.com/75541042/180339607-94dfcf29-8030-4bf3-83e5-29f22c6c8f1f.png)

**Comment by Mojito-Fivem** [comment]
With the latest versions of NPWD I can't reproduce this

**Comment by GlitchWeesocks** [comment]
> With the latest versions of NPWD I can't reproduce this

What do I do then?

**Comment by itschip** [comment]
@GlitchWeesocks Can you try and reproduce this with 1.5.0?
