### ISSUE TITLE
Enhancement: In-call muting

### ISSUE THREAD

**Issue by Jafool** [project-error/npwd#810]
### Application

Other

### Dependency

No

### Feature Description

Hey guys! Here's another issue.

This feature would be the ability to temporarily mute your ongoing phone call.
For instance, consider the following example;

1. You're speaking on a phone call
2. You want to speak to someone in your proximity for a moment
3. You tell your phone call interlocutor to shut up and hold on for a second
4. You mute the call
5. You yell obscenities at someone in your proximity
6. You resume the call
7. You can return to your call, with your phone call interlocutor none the wiser

The easiest way to achieve this would probably be to just toggle the user in- and out of the call channel in pma-voice.
However, if it's possible within pma-voice, you could even make it fancy enough to have 2 options;

- Microphone mute, meaning you would still be able to hear your phone call interlocutor, but they would not be able to hear you.
- "Full" mute, meaning your microphone is muted as well as your "speakers". This would basically be the "toggle call channel" solution I referenced earlier.

This would be a great addition to the core functionality of the project!

**Comment by Mojito-Fivem** [comment]
Should be working on developer with bac15c2a8c136fa9a1557ddd3157606f63d63910
