### ISSUE TITLE
Message while calling

### ISSUE THREAD

**Issue by ItzTrivial** [project-error/npwd#814]
### Development Issue

Yes

### Phone Version

1.3.3 Master

### Issue Description

If there is a notification for a message coming down from the top while calling someone Im able to press on it. It brings me to the messages. At this point im still hearing the sound of the phone calling someone, but I cant return to the call, since Im locked in the messages app. I cant go back to the home screen and I cant simply push the back button on the bottom right either. 

This happened to me while dialing 911 working on Mojitos npwd-dispatch script.

### Issue Reproduction

- Call someone
- Receive notification for message during the dial
- press on it to go to the messages-app
- try to go to the homescreen or somehow end the call.

**Comment by itschip** [comment]
:O I can see this happening. Thanks for the report. We'll look into it.
