### ISSUE TITLE
Message conversation bug

### ISSUE THREAD

**Issue by ItzTrivial** [project-error/npwd#816]
### Development Issue

Yes

### Phone Version

1.3.3 master

### Issue Description

When opening the contacts and pressing on the message button while a chat with the contact Im trying to message already exists it tells me with a pop-up message, that the chat already exists. In the messages-app to which it directs you when trying to send a message I cant open the chat up with the contact I just tried to message via the contact-app.

### Issue Reproduction

-open up a chat with a number
-write a message
-go to the contact app
-try to send a message to the exact same number via the contact app
-try to open the chat after receiving the error message, that the chat already exists.

**Comment by itschip** [comment]
Does it navigate from the contact app directly to the conversation, or do get to the modal where you have input the number again?

**Comment by ItzTrivial** [comment]
It sends you from the contact app to the screen right here: 
![image](https://user-images.githubusercontent.com/66124070/182044576-ba989332-0b89-41e7-af24-3a49b98b1421.png)
After clicking on send it sends you to the messages main screen showing up the error from the bottom

**Comment by itschip** [comment]
Alright, this should be an easy fix. Thanks.

**Comment by itschip** [comment]
@ItzTrivial fixed in develop.
