### ISSUE TITLE
Time on API text-replies wrong

### ISSUE THREAD

**Issue by ItzTrivial** [project-error/npwd#817]
### Development Issue

Unsure

### Phone Version

1.3.3 master

### Issue Description

When replying to a player with the emitMessage API the phone doesnt show the correct time the message was received.

### Issue Reproduction

-write code to emit message automatically
-check the sent time on the bottom left
-wrong time

### Evidence

![image](https://user-images.githubusercontent.com/66124070/181934467-8d316488-361f-444a-8b22-1b1f9d8f2b9a.png)
![image](https://user-images.githubusercontent.com/66124070/181934479-f80b091f-11e5-4c4c-9bc9-471d72f08a15.png)

**Comment by itschip** [comment]
Most likely because we're sending the data from the export directly to the client, instead of waiting for it to be stored, and fetch it again with the 'createdAt' column.

**Comment by itschip** [comment]
Should be fixed in https://github.com/project-error/npwd/commit/7b4dd852420bd9735fc89198186fafc88d44a178
