### ISSUE TITLE
Enhancement: (Imgur) Photo app preformance enhancements

### ISSUE THREAD

**Issue by xXxTHELAWxXx97** [project-error/npwd#818]
### Application

Camera

### Dependency

No

### Feature Description

# Problem
Photos take forever to load if you have too many of them causing a lag spike with the phone, sometimes even freezing it outright.

# Possible Solutions
1. Select multiple photos to be marked for deletion
2. Have it only generate a certain amount of photos when you first launch the camera app (~10) then have a button for show all photos.
3. Have a separate gallary app so when you go to take a new photo it won't try to load all of the other photos, maybe with implemintation of solution 2 as well.
4. 🧙the wizard Also mentioned possibly caching the images for faster load times and/or adding pagination. (I don't have a lot of knowledge in scripting so I have no Idea what pagination is.......)

**Comment by teidova21** [comment]
How about just having a progressive loading, only loading a few images at a time and only the visible ones.
It should go easier on the cpu that way ?
