### ISSUE TITLE
Enhancement: Selfies

### ISSUE THREAD

**Issue by TonybynMp4** [project-error/npwd#820]
### Application

Camera

### Dependency

No

### Feature Description

Add more features to the selfie thing, in the base gta selfie camera you can move the phone left / right / up / down or rotate a bit, change the character's expression and i think it'd be cool. you know like a wise man once said: 

> Make Selfies Great Again

### References

go to singleplayer and use the phone's selfie camera bro

**Comment by itschip** [comment]
You can already move the camera in said directions, and I don't want to bring in unrelated functionality like facial expression. There are resources doing such already.

**Comment by TonybynMp4** [comment]
> You can already move the camera in said directions, and I don't want to bring in unrelated functionality like facial expression. There are resources doing such already.

can you tho ?

**Comment by TonybynMp4** [comment]
@itschip https://streamable.com/c7vzrd
das the reference there u go
