### ISSUE TITLE
Enhancement: Message deletion

### ISSUE THREAD

**Issue by TonybynMp4** [project-error/npwd#822]
### Application

Messages

### Dependency

No

### Feature Description

Plz add the possibility to remove embedded messages (that you sent) and add a thing to select multiple messages to remove.

**Comment by itschip** [comment]
Fixed in develop

**Comment by TonybynMp4** [comment]
u sure 'bout that bud' ?

**Comment by itschip** [comment]
@TonybynMp4 In 1.3.8
