### ISSUE TITLE
Bug: cannot read properties of null (reading 'getPhoneNumber)

### ISSUE THREAD

**Issue by randomentity93** [project-error/npwd#823]
### Development Issue

Unsure

### Phone Version

1.3.7

### Issue Description

[         script:npwd] SCRIPT ERROR in event `npwd:getCredentials': TypeError: Cannot read properties of null (reading 'getPhoneNumber')
[         script:npwd] > <unknown> (@npwd/resources/dist/server/server.js:38798)

I have attached a screenshot of my config.json below

![image](https://user-images.githubusercontent.com/28087406/183358367-492a928d-ba9a-44f3-98a7-993dd98a893d.png)

### Issue Reproduction

1. Load into the server
2. Attempt to open phone using keybind
3. Nothing happens, server console throws error

### Evidence

![image](https://user-images.githubusercontent.com/28087406/183358187-051ce923-72a8-43b1-ba97-af8cb9d10a49.png)

**Comment by itschip** [comment]
@randomentity93 Can I see a full data record in the users table?

**Comment by randomentity93** [comment]
esx-npwd was missing, I have installed it, appears to be working fine now.
