### ISSUE TITLE
Bug: help message disappear too slow

### ISSUE THREAD

**Issue by TonybynMp4** [project-error/npwd#824]
### Development Issue

No, Blame Chip

### Phone Version

latest develop bruh

### Issue Description

when taking a pic the help text doesn't disappear and therefore appears on the photo.

### Issue Reproduction

cmon i don't need to tell you how to take a photo

### Evidence

https://i.imgur.com/yh159Ct.jpg
https://i.imgur.com/MUmzHE5.jpg
https://i.imgur.com/RV8k0BY.jpg

**Comment by itschip** [comment]
I am actually unable to reproduce this :/

**Comment by TonybynMp4** [comment]
;c

**Comment by TonybynMp4** [comment]
looks very much like it's lag, it doesn't happen everytime, but very very often (in like 15 pics it didn't happen only once so..)
Might want to add a key to hide the text manually & pump the delay up a bit like 500ms or even 1 sec something like that.

**Comment by TonybynMp4** [comment]
also a confirmation popup when deleting photos might be a good idea
maybe even a select all / select multiple to make it easier c:
