### ISSUE TITLE
Enhancement: photo embed

### ISSUE THREAD

**Issue by TonybynMp4** [project-error/npwd#829]
### Application

Messages

### Dependency

No

### Feature Description

Add a copy link and add to galery buttons in the ... of the photo embed
also GIVE US THE FUCKING CLICK TO PREVIEW SMOL PHOTO SUCKS

**Comment by WEEZOOKARP** [comment]
I think what the op wants is the ability to grab the image link, easiest way to do this would be through imgur or discord similarly to qb-phone, also some sort of preview image thing so if you click an image on Twitter it fills the screen or smth. Also it seems that op might need some anger management or smth.

**Comment by TonybynMp4** [comment]
i probably do tbh

**Comment by TonybynMp4** [comment]
grabbing the link would be pretty easy since you display the image using said link

**Comment by menkzy** [comment]
Grabbing the link.. you mean this right? ![this right?](https://i.imgur.com/QAwUxAL.gif)

that would copy [this](https://i.projecterror.dev/RGHwue22cSSnroeWNASMz5)

**Comment by TonybynMp4** [comment]
yeah basically

**Comment by menkzy** [comment]
already a thing bozo

**Comment by TonybynMp4** [comment]
> already a thing bozo

no bozo
