### ISSUE TITLE
Bug: Message Validation

### ISSUE THREAD

**Issue by mk3ext** [project-error/npwd#835]
### Development Issue

Yes

### Phone Version

develop

### Issue Description

When creating a new message, you are able to input any text in the field `Search contacts or type number and press enter`, this includes non existing phone numbers, you are then able to send messges to these non existing numbers.

### Issue Reproduction

1. Open your phone
2. Click on messages
3. Press the "+" button
4. Type in any text and hit enter
5. Press "send"
6. Open messages with newly created message

### Evidence

https://streamable.com/ufvf9o

**Comment by itschip** [comment]
Same as #836
