### ISSUE TITLE
Bug: New Contact Validation

### ISSUE THREAD

**Issue by mk3ext** [project-error/npwd#836]
### Development Issue

Yes

### Phone Version

develop

### Issue Description

When creating a new contact, you are able to input any text in the number field, this includes non existing phone numbers, you are then able to send messges to and call these non existing numbers.

### Issue Reproduction

1. Open your phone
2. Open the contacts app
3. Press the "+" button at the bottom right
4. Enter any value into the number field
5. Press "Add Contact"

### Evidence

https://streamable.com/0j2j4f

**Comment by qalle-git** [comment]
You should be able to call non-existing numbers, there is a handler for onCall for example services etc.

**Comment by itschip** [comment]
@mk3ext as @qalle-git says, this is intendet to save numbers that are used by the 'onCall/onMessage' export in order to listen to messages/calls
