### ISSUE TITLE
Bug: Cannot delete photos in gallery

### ISSUE THREAD

**Issue by xXJamieXx** [project-error/npwd#844]
### Development Issue

Yes

### Phone Version

1.5.1

### Issue Description

When selecting one or more photos to delete and clicking the trash icon, it will show an error in the phone saying "Photo could not be deleted :(" and also an error in the server console which says "[NPWD] [photo] [error]: Failed to delete photos, photoIds is not iterable".

### Issue Reproduction

1. Open camera app
2. Click pen icon in the top right
3. Select one or more photos
4. Click trash icon in the bottom right

### Evidence

![image](https://user-images.githubusercontent.com/11248045/185938111-64fdd08b-6a80-4d7d-89ed-fc3476c46275.png)

**Comment by SamShanks1** [comment]
Testing it now. Worked yesterday :/

**Comment by SamShanks1** [comment]
fixed in latest develop

**Comment by SamShanks1** [comment]
fixed in release now
