### ISSUE TITLE
Bug: Can't select images from camera to use in other apps

### ISSUE THREAD

**Issue by xXJamieXx** [project-error/npwd#846]
### Development Issue

Yes

### Phone Version

1.5.2

### Issue Description

When trying to choose an image to use in another app (Marketplace for example) there is no way to select the image.

### Issue Reproduction

1. Open app that allows image selection (e.g. Marketplace)
2. Click "Choose a image"
3. Be unable to select an image

### Evidence

https://streamable.com/uuh92q

**Comment by itschip** [comment]
Fixed 1.5.3
