### ISSUE TITLE
Bug: Error when change icons set in Settings App

### ISSUE THREAD

**Issue by jcabala14** [project-error/npwd#851]
### Development Issue

No

### Phone Version

1.5.3

### Issue Description

When you change the icon set from the settings app to NPWD Icons, the system throws the following error when refreshing the phone:

NPWD has encountered an error it was unable to recover from. You will need to reload the NUI window. The error is shown below for developer reference.

Element type is invalid. Received a promise that resolves to: undefined. Lazy element type must resolve to a class or function.

![image](https://user-images.githubusercontent.com/3659173/186896698-93d1cc19-3840-4046-8791-709a811e2343.png)

After that, you can't use the phone.

### Issue Reproduction

1.  Go to settings app
2.  Select Icons Set
3. Select NPWD Icons

**Comment by itschip** [comment]
@jcabala14 Have you added your own iconset, or is this the default set?

**Comment by jcabala14** [comment]
Hi @itschip, is the default set, I haven't made any changes
