### ISSUE TITLE
Bug: Darkchat bugs list 

### ISSUE THREAD

**Issue by Oldarorn** [project-error/npwd#854]
### Development Issue

Yes

### Phone Version

Develop branch

### Issue Description

- [ ]  1. First issue (by Qalle) : Offline members are not fetched in the members list

- [ ]  2. Online members are not fetched either

- [x]  3. Some translations aren't applied stop hardcoding things, you naughty Chip ♥

- [x]  4.  Join UI doesn't close when you click on join, if you don't pay attention you'll create the same channel multiple times

- [ ]  5. Last issue (with repro) : Rename a channel and send a photo give the channel it's old name

### Issue Reproduction

1. Join a channel
2. Rename the channel
3. Upload photo
4. The channel has it's old name back

Seems to be only an UI issue because if you go back to the app homepage the name is good

**Comment by qalle-git** [comment]
Issue 3 and 4 fixed in my PR

https://github.com/project-error/npwd/pull/853
