### ISSUE TITLE
Enhancement: twitter clout counter

### ISSUE THREAD

**Issue by TonybynMp4** [project-error/npwd#856]
### Application

Twitter

### Dependency

No

### Feature Description

Like / RT counter no cap.

**Comment by itschip** [comment]
What does clout mean?

**Comment by TonybynMp4** [comment]
temporary fame i think?

**Comment by TonybynMp4** [comment]
idk some youngling's word i'm too old to understand

**Comment by teidova21** [comment]
so you mean a counter in twitter profile page to see total rt and likes of your messages ?

**Comment by itschip** [comment]
@teidova21 No, on the like button. Show the amount of likes.

**Comment by TonybynMp4** [comment]
![image](https://user-images.githubusercontent.com/97451137/191813053-de99e122-6586-4e28-a9af-c156d0cf3b94.png)
@itschip work plz

**Comment by TonybynMp4** [comment]
sacrebleu! @itschip u forgot to close the damn issue with the release! smh i'll do it myself then..
