### ISSUE TITLE
Bug: Able to use other UI scripts while on phone

### ISSUE THREAD

**Issue by zentroxx** [project-error/npwd#860]
### Development Issue

No

### Phone Version

1.5.3

### Issue Description

So when the phone is visible you can still use for an example your inventory. Doesn't seem like other UI keys are disabled for other scripts while you have the phone up.

### Issue Reproduction

1. Open up your phone ingame.
2. Hit your inventory key, or use items key.
3. There ya go.

### Evidence

https://streamable.com/yqze7w

**Comment by qalle-git** [comment]
Don't think this has anything to do with the phone, isn't it like this with all UI:s?

**Comment by zentroxx** [comment]
> Don't think this has anything to do with the phone, isn't it like this with all UI:s?

Well, it haven't been a problem with other UI elements? This is the first one I've tested who had problems that the player can still use items and execute other UI elements while the phone is open.

**Comment by zentroxx** [comment]
I also forgot to mention that I run 1.5.4 instead of 1.5.3 x)

**Comment by zentroxx** [comment]
It seems like SetNuiFocusKeepInput(true); makes this kind of bug. I have disabled this on my end.

**Comment by qalle-git** [comment]
> It seems like SetNuiFocusKeepInput(true); makes this kind of bug. I have disabled this on my end.

You won't be able to walk with the phone open.

**Comment by zentroxx** [comment]
> > It seems like SetNuiFocusKeepInput(true); makes this kind of bug. I have disabled this on my end.
> 
> You won't be able to walk with the phone open.

Yeah, I'd rather not letting the player walk around than letting player accidentally uses his weapon while using the phone.

**Comment by qalle-git** [comment]
> > > It seems like SetNuiFocusKeepInput(true); makes this kind of bug. I have disabled this on my end.
> > 
> > 
> > You won't be able to walk with the phone open.
> 
> Yeah, I'd rather not letting the player walk around than letting player accidentally uses his weapon while using the phone.

I'm not sure how anyone would accidentally do that, when you're in a input the phone automatically disable all keys.
If you're not in a input you use the mouse to navigate so how would a weapon be picked up?

**Comment by Mojito-Fivem** [comment]
This only occurs with third party apps that aren't using the exposed text input components from npwd

**Comment by itschip** [comment]
> Yeah, I'd rather not letting the player walk around than letting player accidentally uses his weapon while using the phone.
I believe these controls are disabled, if not, you can just edit the 'controls.lua' file.
