### ISSUE TITLE
Bug: Text Notifications Not working

### ISSUE THREAD

**Issue by 123B3n** [project-error/npwd#861]
### Development Issue

Unsure

### Phone Version

1.5.4

### Issue Description

There are no notifications at all when texting contacts, everything else seems to give a notification except text messages. No popup, sound or anything. It's also not updating text messages live if you send to someone whilst having the phone open.

### Issue Reproduction

Send a text message to someone that is live and they shouldn't receive any notifcations.

**Comment by minipunch** [comment]
Can confirm

**Comment by itschip** [comment]
@minipunch @123B3n being fixed while refactoring notifications
