### ISSUE TITLE
Enhancement: App visibility

### ISSUE THREAD

**Issue by xXJamieXx** [project-error/npwd#862]
### Application

Other

### Dependency

No

### Feature Description

All apps (built-in and external) should have a visibility property so that they can be toggled on and off per player. 

The way I envision this being implemented is for each app to have a defaultVisibility property which is usually set to true by default which can be modified within the source code or by using an export:

`exports.npwd:setAppVisible("browser", false)`
`exports.npwd:setAppVisible("npwd_qb_banking", false)`

This functionality would allow for apps to be shown/hidden within other scripts with framework integration like having/using an item, running a command or having a specific job.

Perhaps storing this information locally would be a useful extension so that the export would only need to be triggered once to show or hide it and would persist between sessions.

**Comment by qalle-git** [comment]
This would be great, would make the darkchat more useful, if having a vpn of some kind to show the darkchat app.
