### ISSUE TITLE
Bug: Can't take pictures

### ISSUE THREAD

**Issue by CptNoHand** [project-error/npwd#863]
### Development Issue

Unsure

### Phone Version

1.5.4

### Issue Description

I get an console error if i try to take a picture. The circle starts spinning, but nothing happens.

### Issue Reproduction

Open phone
Go to camera
Take picture
Phone shows up
Circle spinning and a error:

script:npwd Error: Undhandled promise failure: Unexpected token T in JSON at position 0

### Evidence

![error npwd](https://user-images.githubusercontent.com/90973107/189183553-f2291806-1991-4b28-9aa6-1a24bf802eab.jpg)

**Comment by itschip** [comment]
@CptNoHand Can I see your config.json file?

**Comment by CptNoHand** [comment]
![npwd](https://user-images.githubusercontent.com/90973107/189203921-34a94655-ac49-4491-8d22-ac70142f06a9.PNG)
@itschip

**Comment by CptNoHand** [comment]
i fixed that now, it takes the sceenshot, but it says "picture can't be saved"

**Comment by itschip** [comment]
@itschip Any server or client errors? And you do have the imgur client id in your *.cfg file?

**Comment by CptNoHand** [comment]
Yes, i do an no error whatsoever..

**Comment by itschip** [comment]
@CptNoHand Do you have OUR fork of screenshot-basic?

**Comment by CptNoHand** [comment]
No used the newest screenshot basic

**Comment by itschip** [comment]
@CptNoHand Make sure you have this https://github.com/project-error/screenshot-basic

**Comment by CptNoHand** [comment]
Yes, works now. My bad. thank you.
