### ISSUE TITLE
Bug: No sounds or popup when receiving a message

### ISSUE THREAD

**Issue by CptNoHand** [project-error/npwd#864]
### Development Issue

Unsure

### Phone Version

1.5.4

### Issue Description

When someone receives a text message, the phone doesnt show the notification or a sound like it does for Twitter

### Issue Reproduction

Receive a message, you get no notification or sound

**Comment by itschip** [comment]
Will look into this when rewriting notifications.

**Comment by minipunch** [comment]
Can confirm, just installed the latest version and also noticed this issue

**Comment by minipunch** [comment]
Also it appears there are no unread message notifications when viewing conversations either
