### ISSUE TITLE
Bug: Error when uploading photo

### ISSUE THREAD

**Issue by fkk-cz** [project-error/npwd#865]
### Development Issue

Yes

### Phone Version

Latest on master

### Issue Description

When attempting to take a picture with the camera, the phone displays the following error: `Create/update request failed.`

Checking the server console shows this:

```
[script:screenshot-ba] SCRIPT ERROR in call ref: TypeError: Object(...) is not a function
[script:screenshot-ba] > Object.callback (@screenshot-basic/dist/server.js:9082)
[script:screenshot-ba] > _PhotoService.handleUploadPhoto (@npwd/resources/dist/server/server.js:52516)
[script:screenshot-ba] > <unknown> (@npwd/resources/dist/server/server.js:52638)
[script:screenshot-ba] > <unknown> (@npwd/resources/dist/server/server.js:50179)
[script:screenshot-ba]
[         script:npwd] [NPWD] [photo] [error]: Failed to upload photo, An error occurred while calling export requestClientScreenshot of resource screenshot-basic - see above for details
```

Using the correct version of screenshot-basic as well.

### Issue Reproduction

1. Open camera app
2. Attempt to take a picture
3. See error

**Comment by fkk-cz** [comment]
Turns out this was caused by a missing reference to `uuid` in tsconfig.json for screenshot-basic.

**Comment by tavomuzyka** [comment]
> Turns out this was caused by a missing reference to `uuid` in tsconfig.json for screenshot-basic.


and what would be the solution?

**Comment by Zer0sky** [comment]
What was the solution to get it to work for taking photos? What are the steps to follow?

**Comment by alerabello** [comment]
solution: tsconfig.json

{
    "compilerOptions": {
        "outDir": "./",
        "noImplicitAny": true,
        "module": "es6",
        "target": "es6",
        "allowJs": true,
        "lib": ["es2017"],
        "types": ["@citizenfx/server", "@citizenfx/client", "node", "uuid"],
        "moduleResolution": "node"
    },
    "include": [
        "./**/*"
    ],
    "exclude": [
        
    ]
}
