### ISSUE TITLE
Bug: missing translations

### ISSUE THREAD

**Issue by TonybynMp4** [project-error/npwd#869]
### Development Issue

Yes

### Phone Version

latest

### Issue Description

i'm gonna try and give u all the missing translations that remains
might just be french translation missing stuff btw

### Issue Reproduction

idk open the phone i guess

### Evidence

Messages:
![image](https://user-images.githubusercontent.com/97451137/189984502-b3f09baa-6839-4b99-a15b-be437e392420.png)
Camera:
![image](https://user-images.githubusercontent.com/97451137/189984903-07f235e3-03ae-4de9-9b77-19345c05f521.png)
Calls:
![image](https://user-images.githubusercontent.com/97451137/189985247-f035e87d-d08d-4e4d-b284-a81f1d96798f.png)
MatchMaker:
![image](https://user-images.githubusercontent.com/97451137/189985484-1ec447ca-4ebf-4830-88b5-2b05b854dfe7.png)
Messages:
![image](https://user-images.githubusercontent.com/97451137/191856367-1cb81809-86c1-4616-9d6f-435c03755181.png)

**Comment by TonybynMp4** [comment]
> Why not just create a PR for this?

cauz they're not keys 🤔

**Comment by itschip** [comment]
@TonybynMp4 You can create keys, then create translations for it :)

**Comment by TonybynMp4** [comment]
> @TonybynMp4 You can create keys, then create translations for it :) 

That sounds like a case of i'd broke everything lol

**Comment by TonybynMp4** [comment]
added one lol

**Comment by TonybynMp4** [comment]
Fak a u bot
