### ISSUE TITLE
QBCore - MultiChar phone number duplication

### ISSUE THREAD

**Issue by LySoon** [project-error/npwd#875]
### Development Issue

No

### Phone Version

[1.6.1](https://github.com/project-error/npwd/releases/tag/1.6.1)

### Issue Description

![image](https://user-images.githubusercontent.com/49767982/191089348-1a18fd28-3a53-4b84-b78b-f22c902cdff3.png)

So problem is, im using npwd on a QBCore server with QB-NPWD resource along, and phone is generating same phone number for all multicharacters created by same license.

On first, i have tried to use citizen id as identifier but i can't find a document to follow and see which options available to use as identifier. so i had to stick with default config and now phone number is same for all multichars that uses same license.

### Issue Reproduction

Config
![image](https://user-images.githubusercontent.com/49767982/191090207-adcd04f0-753a-4318-a36f-b5391da9746c.png)

### Evidence

![image](https://user-images.githubusercontent.com/49767982/191089578-b3e7aef9-cf0e-4acf-85f0-1fa98e4d5b93.png)

**Comment by Mojito-Fivem** [comment]
Please refer to the QB section of our docs
