### ISSUE TITLE
Enhancement: Cuter Twitter

### ISSUE THREAD

**Issue by teidova21** [project-error/npwd#878]
### Application

Twitter

### Dependency

No

### Feature Description

- profile pages with the tweets that person retweeted or wrote

This could allow for future other features like :
- allow for twitter pms
- adding ability to follow someone
- adding private accounts
- adding three feeds instead of one:
   - 'my feed' with only your tweets, rt of your tweets, comments to your tweets/comments and tweets from followed people
   - 'new tweets' feed with last public tweets from people
   - 'trendy tweets' feed with tweets from the last 48h with the most unique engagement (unique player doing like and/or rt and/or comment)

**Comment by itschip** [comment]
I've had similar ideas, but not sure if I will prioritize this at all. Feel free to pick this up and create such a feature. I support this.

**Comment by IKKaybe** [comment]
Would really like something like this, even just the ability to post a tweet under a "different name" or anonymously
