### ISSUE TITLE
Enhancement: Introduce DI design pattern to server side scripts

### ISSUE THREAD

**Issue by itschip** [project-error/npwd#879]
### Application

Other

### Dependency

Yes

### Feature Description

Introduce a DI container library such a `typedi` or `tsyringe`. Today we're doing a workaround with initializing the class, then exporting it.

**Comment by Mojito-Fivem** [comment]
No

**Comment by itschip** [comment]
Won't do as adding additional complexity would probably make further contribution harder, and the amount of work this requires shouldn't be prioritized now.
