### ISSUE TITLE
Bug: External garage app not loading

### ISSUE THREAD

**Issue by alfiswielki** [project-error/npwd#880]
### Development Issue

Yes

### Phone Version

new

### Issue Description

hello I upload everything the phone works, I try to add a garage and this is where the problems start....
I add the garage app to config.json and yet it is not on the phone and under f8 I have this, I will add a picture

How to do it? I am using the new qbcore
![telefon1](https://user-images.githubusercontent.com/111529419/192115432-1b7ec905-bcc8-42ff-aaab-d4b2d49da2dd.png)
![telefon2](https://user-images.githubusercontent.com/111529419/192115438-205dde64-f3a8-48b8-8e83-6d42ff5218fe.png)
![telefon3](https://user-images.githubusercontent.com/111529419/192115442-a6a70e52-66e5-483f-ac34-5380e2c4145b.png)

### Issue Reproduction

...

### Evidence

...

**Comment by itschip** [comment]
@alfiswielki You most likely did not download the compiled release files, meaning you have the source code. I can't think of anything else.

**Comment by alfiswielki** [comment]
> @alfiswielki You most likely did not download the compiled release files, meaning you have the source code. I can't think of anything else.

well and can you show me the pattern (code) for adding the application? How should it look like when I upload garage,crypto,emial etc?

**Comment by itschip** [comment]
You've added the app correctly in the config.json, but you need this zip file with compiled files if you don't want to build it yourself.

https://github.com/npwd-community/npwd_qb_garage/releases/download/1.0.6/npwd_qb_garage.zip

**Comment by alfiswielki** [comment]
good cum.... my mistake thanks for your help ahh this saturday :D

**Comment by alfiswielki** [comment]
> Aplikacja została dodana poprawnie w pliku config.json, ale potrzebujesz tego pliku zip ze skompilowanymi plikami, jeśli nie chcesz go samodzielnie budować.
> 
> https://github.com/npwd-community/npwd_qb_garage/releases/download/1.0.6/npwd_qb_garage.zip

![ehh](https://user-images.githubusercontent.com/111529419/192115964-d64758b0-0cec-429a-86bc-26d0aa04a9a2.png)
![ehh](https://user-images.githubusercontent.com/111529419/192115999-514c5d32-ff61-4db2-87cf-39df52c28dc2.png)
why do I now see garage and not crypto?

**Comment by Oldarorn** [comment]
Cause you have to write "apps": ["npwd_crypto", npwd_gb_garage"] ...

**Comment by alfiswielki** [comment]
I could not find any information about this....

**Comment by alfiswielki** [comment]
but I still have one or the other, no two at the same time

**Comment by alfiswielki** [comment]
> Bo musisz napisać "apps": ["npwd_crypto", "npwd_gb_garage"] ...

but I still have one or the other, no two at the same time

**Comment by alfiswielki** [comment]
![err](https://user-images.githubusercontent.com/111529419/192116237-4fe03504-e10b-41d1-826a-d107c3a033d4.png)

**Comment by itschip** [comment]
Yeah, that's correct.

**Comment by alfiswielki** [comment]
> Tak, zgadza się.

![err](https://user-images.githubusercontent.com/111529419/192116273-3845517e-9570-481b-98ba-3102e16ee47c.png)
to why do I have crypto and the garage does not? xD

**Comment by itschip** [comment]
Does both apps start before npwd?

**Comment by alfiswielki** [comment]
> Czy obie aplikacje uruchamiają się przed npwd?

![err](https://user-images.githubusercontent.com/111529419/192116358-f2e3cc20-fb7a-4bde-b890-2ad80fd88710.png)
yes both are in standalone

**Comment by alfiswielki** [comment]
the ones that type first, the ones that work

**Comment by alfiswielki** [comment]
`ensure qb-core
ensure [qb]
ensure qb-npwd
ensure [standalone] <<here have garage and crypto and see only one
ensure [voice]
ensure [defaultmaps]
ensure [skrypty]
ensure fivem-scenarios
ensure zdiscord
ensure npwd`

**Comment by alfiswielki** [comment]
ensure qb-core
ensure [qb]
ensure qb-npwd
ensure [standalone]
ensure [voice]
ensure [defaultmaps]
ensure [skrypty]
ensure fivem-scenarios
ensure zdiscord
ensure npwd

**Comment by alfiswielki** [comment]
> Does both apps start before npwd?

ensure qb-core
ensure [qb]
ensure qb-npwd
ensure [standalone] < here have garage and crypto and see ony one
ensure [voice]
ensure [defaultmaps]
ensure [skrypty]
ensure fivem-scenarios
ensure zdiscord
ensure npwd

**Comment by mahanmoulaei** [comment]
> ![err](https://user-images.githubusercontent.com/111529419/192116237-4fe03504-e10b-41d1-826a-d107c3a033d4.png)

you need to replace "npwd_gb_garage" with "npwd_qb_garage"

**Comment by itschip** [comment]
Please use the correct repository for these issues.
