### ISSUE TITLE
I keep getting an error saying "Failed to store phone number in database"

### ISSUE THREAD

**Issue by IndigoBerry** [project-error/npwd#881]
### Development Issue

Unsure

### Phone Version

1.6.1

### Issue Description

I dont know what i did wrong but when somebody joins my server it says this in the console:
[         script:npwd] [NPWD] [player] [error]: Failed to store phone number in database
[         script:npwd] [NPWD] [player] [error]: UPDATE users SET phone_number = 675-743-9363 WHERE identifier = eef92ab7dcef11325680163d0653768e80a43f14

i also get in oxymysql this:
[      script:oxmysql] SCRIPT ERROR in promise (unhandled): Error: pe-core was unable to execute a query!
[      script:oxmysql] Data too long for column 'identifier' at row 1
[      script:oxmysql] INSERT INTO ?? (??,??) VALUES (?,?) ["users","identifier","phone_number","license:372611967ce989ed30f3d3ffc6a921641a3f4848","200-983-3386"]
[      script:oxmysql] > <unknown> (@oxmysql/dist/build.js:21786)
[      script:oxmysql] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:oxmysql] > async rawQuery (@oxmysql/dist/build.js:21755)
[      script:oxmysql] 

### Issue Reproduction

1. Start Server
2. Join server
3. look at console
4. see error

### Evidence

![Screenshot_2](https://user-images.githubusercontent.com/112669566/192122884-9da3a4f0-f0e1-4e82-bea6-f23263daf9f7.png)

**Comment by Visloczki** [comment]
Hi!

Use database prefix. Example :
  
  "database": {
    "useIdentifierPrefix": true,
    "playerTable": "users",
    "identifierColumn": "identifier",
    "identifierType": "char1",
    "profileQueries": true,
    "phoneNumberColumn": "phone_number"
  },

and dont forget alter your users phone_number field to varchar(20)

Regards. Adam

**Comment by Itzyaboizordan2** [comment]
im also getting a error for this but i did what u said and nothing still gives a error or phone doesnt work at all

**Comment by Visloczki** [comment]
> im also getting a error for this but i did what u said and nothing still gives a error or phone doesnt work at all

You updated phone_number field type to varchar20 ?

**Comment by Blacky5613** [comment]
I have the exact same mistake and did it almost exactly as they wrote it down.

![Screenshot_2](https://user-images.githubusercontent.com/114885046/196031401-1e4ec552-61f3-4767-b701-afce81d5a405.png)

![Screenshot_1](https://user-images.githubusercontent.com/114885046/196031407-78c3051c-bcd4-440e-95df-f37b9b68b6ea.png)
![Screenshot_3](https://user-images.githubusercontent.com/114885046/196031424-90b416c1-a7bf-44c2-b9cb-396f3c053c73.png)

**Comment by Br4inFish** [comment]
> > im also getting a error for this but i did what u said and nothing still gives a error or phone doesnt work at all
> 
> You updated phone_number field type to varchar20 ?

Hey mate, I've followed your guide, I can't get this to work, Still get this error after the fix you provided. 
Do you mind sharing some more help for this ?

**Comment by TheOnly3aq** [comment]
I know I'm a bit late to this, but you need to install https://github.com/project-error/pe-core, this will put an identifier in your users table so that npwd can use that to link a phone number to a user. 

See: https://projecterror.dev/docs/npwd/start/installation#basic-configuration 

It says it in the caution area.
