### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Texdk** [project-error/npwd#888]
### Development Issue

No

### Phone Version

1.6.0

### Issue Description

![image](https://user-images.githubusercontent.com/109815352/194356616-91bdd2f5-754f-4465-806a-7ffc6a429e8b.png)

### Issue Reproduction

i have no idea how its happend

### Evidence

![image](https://user-images.githubusercontent.com/109815352/194356829-5783a438-883d-48a8-992d-c3d54163b552.png)

**Comment by Texdk** [comment]
update it happends when i add apps

**Comment by Texdk** [comment]
![image](https://user-images.githubusercontent.com/109815352/194360760-a9db379b-8757-49ba-9fbf-04c47e0bcf32.png)

**Comment by itschip** [comment]
@Texdk You have downloaded the source code. Either build the phone or download the bundled release files.

**Comment by Texdk** [comment]
@itschip do you have a link?
