### ISSUE TITLE
Bug: Twitter likes stuck on 0

### ISSUE THREAD

**Issue by xchopin** [project-error/npwd#892]
### Development Issue

No

### Phone Version

1.7.0

### Issue Description

Tweet doesn't update the like counter (on the UI) however the database gets the update.

Also if you like the tweet then close the phone and open it back the heart icon doesn't get filled anymore it's like if you didn't like it

### Issue Reproduction

Like a tweet.

### Evidence

<img width="202" alt="image" src="https://user-images.githubusercontent.com/15248061/194724199-99994b0c-b0fd-4c39-9bf8-860eb4886234.png">

**Comment by CptNoHand** [comment]
Same

**Comment by itschip** [comment]
Should be fixed in latest master. Clone/download to test.
