### ISSUE TITLE
Bug: No notifications for messages

### ISSUE THREAD

**Issue by CptNoHand** [project-error/npwd#893]
### Development Issue

Unsure

### Phone Version

1.7.0

### Issue Description

On my server we get no notification when we receive messages. 

### Issue Reproduction

Open Phone
Send Message
Receive Message
No notification

**Comment by Cyril-Beeckman** [comment]
Sometimes i got notifications, sometimes not...
Very difficult to provide a repro

**Comment by minipunch** [comment]
Can confirm this used to happen with an older version when we tried this phone

**Comment by anes66** [comment]
version '1.7.1'  no message notification when you get a new msg from a number
