### ISSUE TITLE
Bug: <exports.npwd:setPhoneVisible(false)> [ inActiveCall ]

### ISSUE THREAD

**Issue by NewEditOfficial** [project-error/npwd#894]
### Development Issue

Unsure

### Phone Version

Latest - 1.7.0

### Bug description

- After call is initialized, hiding phone via [exports.npwd:setPhoneVisible(true)] on CLIENT [A] (boothUser) - should work, but nope. 
- Phone should hide, when func is called, bypassing (Related logic picture via HasPhone), to ensure that call will not be rejected, even phoneUI is "hidden" 👍 

Related logic picture:

![image](https://user-images.githubusercontent.com/19749031/194727718-ef3e2527-ff07-4803-b4e0-ee57575e2de6.png)

### Issue Reproduction

CLIENT [A] - Target
CLIENT [B] - Initiator

1. CLIENT [B] call to CLIENT [A] (Booth user)
2. For CLIENT [A] hide phone via npwd:setPhoneVisible(false)
3. Result: Failed to hide phone for CLIENT [A]

Used code:

```json
  "PhoneAsItem": {
    "enabled": true,
    "exportResource": "booth",
    "exportFunction": "HasPhone"
  },
```

```lua
local function HasPhone()
    return true
end

exports("HasPhone", HasPhone)
```

### Evidence

CLIENT [A]

![unknown](https://user-images.githubusercontent.com/19749031/194727557-aa580dc5-ec2e-44ca-b157-e6d0fa302b0e.png)

CLIENT [B]

![unknown (1)](https://user-images.githubusercontent.com/19749031/194727562-3bb8b130-3c5b-4eb4-ae51-5c2b76003efc.png)

**Comment by Mojito-Fivem** [comment]
What? You just want it to hang up if you hide the phone?

**Comment by NewEditOfficial** [comment]
> What? You just want it to hang up if you hide the phone?

I want to able hide phoneUI, when perform exports.npwd:setPhoneVisible(false) - which looks like that doesnt work, when call is active.

**Comment by Mojito-Fivem** [comment]
And what usecase does this have for npwd other than for your own script?

**Comment by NewEditOfficial** [comment]
> And what usecase does this have for npwd other than for your own script?

I mean if the API is offered with function setPhoneVisible(false), then it should work? 🤔

**Comment by NewEditOfficial** [comment]
Or just simple export which will allow to pass boolean value and its resolved. @Mojito-Fivem 

👍 

![image](https://user-images.githubusercontent.com/19749031/195187481-2b34f99f-c6ab-4060-8c1e-92f3ea7523be.png)
