### ISSUE TITLE
Phone numbers 

### ISSUE THREAD

**Issue by Texdk** [project-error/npwd#895]
is it possible to change the settings so the phone generates eu numbers?

examble +45 ########

**Comment by Mojito-Fivem** [comment]
You can edit the function here to change the number generating behavior, this isn't something we can easily make configureable

https://github.com/project-error/npwd/blob/2166e03f92385c7fb21d70f6514c05bb2f680ed5/resources/server/misc/generateUniquePhoneNumber.ts#L27-L36

Perhaps we can allow the user to pass their own number generating function as an export, similar to the way we check for item presence such as this:

```json
{
    "customNumberGeneration": {
        "enabled": false,
        "exportResource": "your-script-here",
        "exportName": "generate-number":
    },
}
```

```lua
exports('generate-number', function()
    return '+45 #########'
end)
```

**Comment by Mojito-Fivem** [comment]
Experimental support for this has been added to [develop ](https://github.com/project-error/npwd/tree/develop) branch allowing you to define your own number generation logic. You will need to make your own export which returns either `string` or `Promise<string>` and add it to your config the same way as PhoneAsItem
