### ISSUE TITLE
Enhancement: Multicharacter support for settings

### ISSUE THREAD

**Issue by xSpiderMC** [project-error/npwd#900]
### Application

Settings

### Dependency

No

### Feature Description

Instead of using the same settings every time you log in, allow support for different characters to have different settings like background and case.

**Comment by cmgjones** [comment]
Would love to see this , Even if for qbcore it runs of the citizen id instead of the identifier . My guys on PD dont want the same twitter accounts and stuff on their crim char

**Comment by jcthiel13** [comment]
This is already a feature with qb-npwd/esx-npwd. Set your identifier to citizenid and point it to the right column in the database. In case of other frameworks check the original author to see if they have pushed a compatibility script. In the case they haven't you can always make your own. It was actually fairly simple to do for my community's framework and ended up getting released by the author of the framework.

**Comment by cmgjones** [comment]
@jcthiel13 Any chance you could help out ? , Everyone has the same phone number for all their characters  discord :  Ca11um#8510

**Comment by Br4inFish** [comment]
> @cmgjones: This is already a feature with qb-npwd/esx-npwd. Set your identifier to citizenid and point it to the right column in the database. In case of other frameworks check the original author to see if they have pushed a compatibility script. In the case they haven't you can always make your own. It was actually fairly simple to do for my community's framework and ended up getting released by the author of the framework.

Is there a way you could helpt out mate, I've tried everything can't get this to work..

**Comment by jcthiel13** [comment]
@Br4inFish I have a lot of projects I'm working on right now, send me a dm with the framework name and I'll see what I can do.

xXxTHE LAWxXx97#5924

**Comment by Br4inFish** [comment]
> @Br4inFish I have a lot of projects I'm working on right now, send me a dm with the framework name and I'll see what I can do.
> 
> xXxTHE LAWxXx97#5924

Thank you for the reply mate, I managed to get it working.
Once again, Thank you for taking your time to reply back.

**Comment by Br4inFish** [comment]
Thank you for the reply @jcthiel13 , I managed to get it working.
Once again, Thank you for taking your time to reply back.
