### ISSUE TITLE
BUg

### ISSUE THREAD

**Issue by 0NATI0** [project-error/npwd#902]
### Development Issue

No

### Phone Version

Latest

### Issue Description

So if you want to start an npwd phone you need to fill this :

  "database": {
    "useIdentifierPrefix": false,
    "playerTable": "users",
    "identifierColumn": "identifier",
    "identifierType": "license",
    "profileQueries": true,
    "phoneNumberColumn": "phone_number"
    
    But there is a problem beacouse if you want to do it on ox_core we have a problem becouse phoneNumberColumn and identifier column are on a diffrent table. Could soebody Help

### Issue Reproduction

  
  I dont know what this is

### Evidence

![image](https://user-images.githubusercontent.com/107504334/196012007-78e8eac7-e763-4fa7-8617-20f37fc36614.png)

**Comment by thelindat** [comment]
It’s characters and charid; but ox core already sets the config for you; start bows after it.
