### ISSUE TITLE
Bug: Error in DB

### ISSUE THREAD

**Issue by AceyV** [project-error/npwd#910]
### Development Issue

Unsure

### Phone Version

1.7.0

### Issue Description

I always get an error

### Issue Reproduction

None. its just there, i have done no settings!

### Evidence

When i start the server i got this error:

[         script:npwd] [NPWD] [DBInterface] [error]: Error executing (SELECT npwd_messages_conversations.id,
[         script:npwd]                           npwd_messages_conversations.conversation_list         as conversationList,
[         script:npwd]                           npwd_messages_participants.unread_count               as unreadCount,
[         script:npwd]                           npwd_messages_conversations.is_group_chat             as isGroupChat,
[         script:npwd]                           npwd_messages_conversations.label,
[         script:npwd]                           UNIX_TIMESTAMP(npwd_messages_conversations.updatedAt) as updatedAt,
[         script:npwd]                           npwd_messages_participants.participant
[         script:npwd]                    FROM npwd_messages_conversations
[         script:npwd]                             INNER JOIN npwd_messages_participants
[         script:npwd]                                        on npwd_messages_conversations.id = npwd_messages_participants.conversation_id
[         script:npwd]                    WHERE npwd_messages_participants.participant = ? ["354-102-9468"]) with error message Unknown column 'npwd_messages_conversations.conversation_list' in 'field list'

**Comment by Mojito-Fivem** [comment]
Your schema is outdated
