### ISSUE TITLE
Bug Server not starting

### ISSUE THREAD

**Issue by digbygaming1** [project-error/npwd#915]
### Development Issue

Unsure

### Phone Version

When i try to start the script it prompts me with this " script:yarn] Error: [yarn] error jest-worker@28.1.3: The engine "node" is incompatible with this module. Expected version "2.13.0 || 4.15.0 || 6.10.0 || >=17.0.0". Got "16.9.1" "

### Issue Description

When i try to start the script it prompts me with this " script:yarn] Error: [yarn] error jest-worker@28.1.3: The engine "node" is incompatible with this module. Expected version "2.13.0 || 4.15.0 || 6.10.0 || >=17.0.0". Got "16.9.1" "

### Issue Reproduction

added all the stuff needed and booted the server 

### Evidence

https://gyazo.com/4ae16ba5e2a8ceda903c25ba9b5bc245

**Comment by mikigoalie** [comment]
create .yarn.installed in root npwd

**Comment by digbygaming1** [comment]
now i am getting this error 
https://gyazo.com/4851130f7913b3a5d09959070e957fc4

**Comment by digbygaming1** [comment]
I fixed it
