### ISSUE TITLE
Bug: Error at ressource start.

### ISSUE THREAD

**Issue by xsoskiller** [project-error/npwd#919]
### Development Issue

Unsure

### Phone Version

1.7.1

### Issue Description

i got many error code while i start the ressource and while using it.

### Issue Reproduction

/start nwpd

that all it happpen at the script start.

### Evidence

![image](https://user-images.githubusercontent.com/66858021/200461718-2f9bec06-141b-41f6-8037-dbff9cb0bfa3.png)
![image](https://user-images.githubusercontent.com/66858021/200461780-0b0e9a2b-540a-46bb-9c72-c5435d24e101.png)
![image](https://user-images.githubusercontent.com/66858021/200461852-0e8d783c-2daa-449f-bb93-e356a9195032.png)
![image](https://user-images.githubusercontent.com/66858021/200461924-04b41e63-f4ce-4707-b28e-fc94926fcdec.png)
![image](https://user-images.githubusercontent.com/66858021/200461997-b5520a6c-da1f-483c-a5a6-acc47dafefb0.png)

**Comment by xsoskiller** [comment]
i'm using Ox_inventory 2.15.1, pma-voice and ESX 1.2 v1.7.5

**Comment by xsoskiller** [comment]
edit: i also got that error
```
[         script:npwd] SCRIPT ERROR in event `npwd:getCredentials': TypeError: Cannot read properties of null (reading 'getPhoneNumber')
[         script:npwd] > <unknown> (@npwd/dist/game/server/server.js:55836)
```

**Comment by Br4inFish** [comment]
Hey!

Don't start npwd in game.

Make sure the phone starts after Screenshotbasic->PMA->esx/qb-npwd then NPWD in the server.cfg.
Check the doc, since you are starting the phone in game with probably /start npwd.
Please read the docs again, since I think you miss understod the server.cfg part.

**Comment by xsoskiller** [comment]
Pma and screenshot-basic start from the same ensured folder and i manually started it from the /start command. I can try tho to unensure thefolder and manually start pma-screenshot-basic from the config.

Ill keep updated if it worked.

**Comment by AvarianKnight** [comment]
I'm going to assume you figure out, but incase you haven't your `identifierType` is invalid, you can find out how to set it up [here](https://projecterror.dev/docs/npwd/start/installation#basic-configuration)
