### ISSUE TITLE
Enhancement: App to play music from YouTube

### ISSUE THREAD

**Issue by QuantiumShade** [project-error/npwd#921]
### Application

Other

### Dependency

Yes

### Feature Description

Hi.
Could be nice to be able to play sound/music from YouTube on your smartphone.

I think this feature shouldn't take long to do if you know what you're doing.
If I find time, I might do it by myself and do a pull request.  In the meanwhile I'm sharing the idea, In case someone wants to do it before me :)

### References

Library to use :
https://github.com/Xogy/xsound

Example of UI :
https://mrsahil.tebex.io/package/5233768

  Could also do something more basic like :
> URL 
> Play Stop Resume

**Comment by Mojito-Fivem** [comment]
This has been in our won't do list for a very long time and won't be changing any time soon

**Comment by QuantiumShade** [comment]
Alright ! I've just found the "won't do list" . My bad
