### ISSUE TITLE
[v2] New UI design for NPWD. Any ideas and proposals are wanted.

### ISSUE THREAD

**Issue by itschip** [project-error/npwd#927]
With NPWD 2.0, we're moving away from MUI, and therefore a new design is needed. If you have any ideas, please share them here.

**Comment by dolutattoo** [comment]
ios?

**Comment by itschip** [comment]
I would rather like to see us design something new. Open to take inspiration from current designs from Apple, but I don't want to go down the iOS 100% route.

**Comment by Mojito-Fivem** [comment]
I'm totally against taking any "inspiration" from apple shitware. Fivem is full of "inspired" aka plagiarised designs, we should come up with a unique design

**Comment by TonybynMp4** [comment]
Ios sucks anyway.

**Comment by justshoveit** [comment]
Foldable phone design with 2 states; folded and unfolded where unfolded state maybe covers more area of the screen?
This way the phone would be able to act as replacement for multiple laptop resources

**Comment by xSpiderMC** [comment]
https://daisyui.com/ something similar to the design of these components could be cool

**Comment by Arctos2win** [comment]
Maybe an app store would be cool, 
also a new design more ios based would also 
be nice
