### ISSUE TITLE
[v2] Server-side architecture

### ISSUE THREAD

**Issue by itschip** [project-error/npwd#928]
I am not a fan of the current server-side impl with "fake" singletons. We should either just introduce proper DI, or find another pattern.

## ORM
We should also discuss we want to introduce an ORM like TypeORM etc. Would it make it harder/easier for the average user?

**Comment by Archangelza1** [comment]
In regards to development side i feel that NPWD 2.0 should not worry about the average user and more care about external developer contribution as I feel majority of servers install NPWD as the release package and use npwd community apps to cater for the rest where with more developer/"custom" focused server owners will want to customise the phone to best fit the servers needs and wants.

**Comment by Moozdzn** [comment]
To make it easier for the average user would be to switch to lua.
