### ISSUE TITLE
Event for giving phone number to nearby player

### ISSUE THREAD

**Issue by IamLation** [project-error/npwd#933]
### Application

Other

### Dependency

No

### Feature Description

Just thinking a nice feature would be an event we can use to give your phone number to a nearby player. As an example say someone is using a radial menu sort of thing, and there's a "Give Contact Info" option, would be nice if there was an event in NPWD that passed that number in a notification on the nearby player's phone to save the contact.

**Comment by AlamoRoleplayFiveM** [comment]
This would actually be really cool but a command should also be implemented for standaloners.

**Comment by IamLation** [comment]
> This would actually be really cool but a command should also be implemented for standaloners.

I agree a command also would be good!

**Comment by AvarianKnight** [comment]
Closing as this was already added.
