### ISSUE TITLE
Bug: i need help with this error: -> Error: Unhandled promise failure: TypeError: Cannot read properties of null (reading '2')

### ISSUE THREAD

**Issue by MrNipz** [project-error/npwd#938]
### Development Issue

Unsure

### Phone Version

1.7.1

### Issue Description

as soon as i setup everything to add the phone in i keep getting this error

[         script:npwd] Error: Unhandled promise failure: TypeError: Cannot read properties of null (reading '2')
[         script:npwd]     at parseUri (@npwd/resources/dist/server/server.js:34897:39)
[         script:npwd]     at _BootDb.<anonymous> (@npwd/resources/dist/server/server.js:34983:31)
[         script:npwd]     at Generator.next (<anonymous>)
[         script:npwd]     at @npwd/resources/dist/server/server.js:64:61
[         script:npwd]     at new Promise (<anonymous>)
[         script:npwd]     at __async (@npwd/resources/dist/server/server.js:48:10)
[         script:npwd]     at _BootDb.doesPlayerTableExist (@npwd/resources/dist/server/server.js:34982:16)
[         script:npwd]     at _BootService.<anonymous> (@npwd/resources/dist/server/server.js:35059:58)
[         script:npwd]     at Generator.next (<anonymous>)
[         script:npwd]     at @npwd/resources/dist/server/server.js:64:61

### Issue Reproduction

on first install

**Comment by AvarianKnight** [comment]
Do you have a syntax error in your `mysql_connection_string`?

**Comment by derletzteritter** [comment]
Hi! This should be fixed in the latest version.
