### ISSUE TITLE
Enhancement: export requested for compatobility with an official qb-core resource

### ISSUE THREAD

**Issue by r0adra93** [project-error/npwd#939]
### Application

Dialer

### Dependency

Yes

### Feature Description

A client side export created in NPWD that can do the following:
1) accept a table/array containing phoneNumber & callType
2) callType being Text or Call
3) then depending on what's sent either open the text app or the phone app on the phone with the number prepopulated.

All the player has to do is type in a message or place a call.

**Comment by Mojito-Fivem** [comment]
Is that the same QB-core which is warden blacklisted

**Comment by r0adra93** [comment]
That black list a pile of bull!
All the code that was claimed to be *stolen* has been verified to be open-source licensed code.

As long as the license is in-tact the code can be used.

The license is the permission, no permission is expected to be requested.

READ THE LICENSE OF ANY SOFTWARE APPLICATION BEFORE USING AND MAKING FALSE CLAIMS!

qb-core is open-source and respects the liceneses that all our reapurces utilize and we follow those terms!

How about a little more research on how open source licensing works and not keep claiming code was stolen!

**Comment by r0adra93** [comment]
To go further qb-core isn't blacklisted by warden kakarot is which is also bullshit.

**Comment by Mojito-Fivem** [comment]
This is not really the place to argue, a simple yes or no would be suffice. I don't really see much use for this, much less why we should do this explicitly for blacklisted scripters but feel free to Pull Request.

**Comment by thelindat** [comment]
> All the code that was claimed to be _stolen_ has been verified to be open-source licensed code.

How do you licence stolen code.

**Comment by r0adra93** [comment]
The code isn't stolen if the license is OPEN SOURCE!
much like how apl of your shit isnopen spurce and has the open source license to it.

I can just fork it over make chamges and sell it and keep the license for that code intact.

As per your license states!

Knock off your slanderous baseless attacks because you have it out against a project.
