### ISSUE TITLE
Yarn fail

### ISSUE THREAD

**Issue by Z3rkhol** [project-error/npwd#940]
### Development Issue

Unsure

### Phone Version

Latest

### Issue Description

When i tried to install it, during yarn installation it faild with this: [         script:yarn] Error: [yarn] C:\server\txData\QBCoreFramework_A5F823.base\resources\[cfx-default]\[system]\[builders]\yarn\yarn_cli.js:89153
[         script:yarn]     compromised = compromised || function (err) { throw err; };
[         script:yarn]                                                   ^
[         script:yarn] 
[         script:yarn] Error: Unable to update lock within the stale threshold
[         script:yarn]     at C:\server\txData\QBCoreFramework_A5F823.base\resources\[cfx-default]\[system]\[builders]\yarn\yarn_cli.js:89075:66
[         script:yarn]     at FSReqCallback.oncomplete (node:fs:188:23) {
[         script:yarn]   code: 'ECOMPROMISED'
[         script:yarn] }
[         script:yarn] 
[ citizen-server-impl] Building resource npwd failed.
[ citizen-server-impl] Error data: yarn failed!

### Issue Reproduction

1. Restart/Start server
2. Error in live console

**Comment by jellyton69** [comment]
I'm having the same issue with building the resource, but I'm not getting any error, it's just this

```
[ citizen-server-impl] Building resource npwd failed.
[ citizen-server-impl] Error data: yarn failed!
```

**Comment by makingmoney12345** [comment]
Same here

`Error: [yarn] error jest-worker@28.1.3: The engine "node" is incompatible with this module. Expected version "2.13.0 || 4.15.0 || 6.10.0 || >=17.0.0". Got "16.9.1"`
