### ISSUE TITLE
Bug: No database connection

### ISSUE THREAD

**Issue by korpens1** [project-error/npwd#941]
### Development Issue

Yes

### Phone Version

1.7.1

### Issue Description

When you enable a script, it does not connect to the database that was specified in the server.cfg 
My database: 146.59.52.138 
Database to which the script connects: 172.18.0.54 

And this is a bug
{"level":"error","message":"Error executing (SHOW TABLES WHERE `Tables_in_s2707_new`LIKE ? [\"users\"]) with error message Access denied for user 'u2707_rVl4oEu29U'@'172.18.0.54' (using password: YES)","module":"DBInterface","timestamp":"2022-12-29T19:06:43.556Z"}

### Issue Reproduction

Behind every attempt to turn on

### Evidence

https://cdn.discordapp.com/attachments/1033457673678626826/1058306355112443954/image.png
https://cdn.discordapp.com/attachments/1033457673678626826/1058302122397016064/image.png

**Comment by Local9** [comment]
Make sure you have no special characters in the password, I've just had the same issue and removed all special characters and it worked fine. This was also stated in #794

**Comment by JackosSVK** [comment]
I have database on pterodactyl

**Comment by AvarianKnight** [comment]
The @'172.18.0.54' is the ip that is connecting to the database.

This isn't something that we can reproduce, so I'm not really sure if we can help you.
