### ISSUE TITLE
Bug: No such export isPhoneVisible on release build of the script.

### ISSUE THREAD

**Issue by CrazedslawDev** [project-error/npwd#943]
### Development Issue

Unsure

### Phone Version

1.7.0

### Issue Description

Fresh install on a new server, Tested using both the release builds of 1.7.0 and 1.7.1 and i get the same result every single time. Have tried reinstalling to no avail.

**Log:**
_[    c-scripting-core] Creating script environments for esx-npwd
[ citizen-server-impl] Started resource esx-npwd
[    c-scripting-core] Creating script environments for npwd
[         script:npwd] **Error loading script resources/dist/server/server.js in resource npwd: SyntaxError: Unexpected string in JSON at position 1074**
[         script:npwd] stack:
[         script:npwd] SyntaxError: Unexpected string in JSON at position 1074
[         script:npwd]     at JSON.parse (<anonymous>)
[         script:npwd]     at getConfig (@npwd/resources/dist/server/server.js:47463:24)
[         script:npwd]     at @npwd/resources/dist/server/server.js:47469:19
[         script:npwd]     at @npwd/resources/dist/server/server.js:47485:3
[    c-scripting-core] Failed to load script resources/dist/server/server.js.
[ citizen-server-impl] Started resource npwd_

**in the F8 Console on the server:**
SCRIPT ERROR: @npwd/resources/client/cl_controls.lua:53: No such export isPhoneVisible in resource npwd
Uncaught (in promise) SyntaxError: Unexpected end of JSON input (@npwd/resources/html/index.html#/:1

### Issue Reproduction

1. Start server
2. See error.

### Evidence

![ECKSDEE](https://user-images.githubusercontent.com/65857370/210276445-2b18c812-b5cb-4016-8b13-f84014eb70f0.PNG)
[fxserver_1672691037.log](https://github.com/project-error/npwd/files/10333441/fxserver_1672691037.log)

**Comment by Mojito-Fivem** [comment]
It looks like your config file has a syntax error
