### ISSUE TITLE
Database No Connection

### ISSUE THREAD

**Issue by Advil165** [project-error/npwd#953]
### Development Issue

Yes

### Phone Version

1.71& 1.7.0

### Issue Description

Once you newly connect you will be assigned a phone number and in hopes you keep the same number. But instead when you leave and join back the same server it creates a new phone number because it sends an error code of “Failed to store phone number in database. And it will generate a new one every time. With the same person joining.

### Issue Reproduction

Whenever the same person joins 

### Evidence

https://media.discordapp.net/attachments/789608072125087766/1064364484317167647/image.png

**Comment by MauriceHandwerker** [comment]
Hey is this issue still active?

**Comment by derletzteritter** [comment]
This is like 100% fixed!
