### ISSUE TITLE
Bug: ESX Server cant find resource and start it

### ISSUE THREAD

**Issue by TmoGAMERcz** [project-error/npwd#954]
### Development Issue

Yes

### Phone Version

1.7.0

### Issue Description

I have esx server and i added script to resources and started in server.cfg But it cant find the script in game 

### Issue Reproduction

1. added script to resources
2. added to start.cfg
3. restarted server
4. joined server
5. there was NO PHONE
6. i tried to restart script but
7. Error Could not find dependency screenshot-basic for resource npwd
8. couldnt start resource npwd

### Evidence

https://streamable.com/145bbz
![image](https://user-images.githubusercontent.com/74590563/215345551-063492c4-c770-47f5-aa04-f969cdddf974.png)

https://user-images.githubusercontent.com/74590563/215345551-063492c4-c770-47f5-aa04-f969cdddf974.png

**Comment by silez** [comment]
Good day,
it's really no offense meant but sometimes very good resources come with documentation. In this, which you can find here [NPWD Documentation](https://projecterror.dev/docs/npwd/start/installation/) the very first paragraph already says that you need another resource: "screenshot-basic". This must also be started BEFORE npwd.
By the way, this answer is also in your error message which you included as a screenshot.
As I said, no offense meant, but sometimes reading can help :) :)
Warm greetings

**Comment by AvarianKnight** [comment]
Read the error message that you have.
