### ISSUE TITLE
Bug: Phone not upload photo discord webhook

### ISSUE THREAD

**Issue by Gregory-Hepicloud** [project-error/npwd#955]
### Development Issue

Yes

### Phone Version

1.7.0

### Issue Description

(node:901344) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `FXServer --trace-deprecation ...` to show where the warning was created)
[         script:npwd] [NPWD] [photo] [error]: Failed to upload photo

### Issue Reproduction
add set SCREENSHOT_BASIC_TOKEN WEBHOOK DISCORD HERE to server cfg
add to npwd config :

"images": {
    "useWebhook": true
  }
  
Take a photo with phone

error

**Comment by llamatude** [comment]
I am having the same issue.

**Comment by GoldenHouseRP** [comment]
+1

**Comment by alberttheprince** [comment]
You need to migrate over to Imgur, Discord blocking images from Fivem.
