### ISSUE TITLE
Bug: Hello Guys I Have A Lot Of Problems

### ISSUE THREAD

**Issue by GTnik3005** [project-error/npwd#971]
### Development Issue

Yes

### Phone Version

Latest

### Issue Description

i have this errors on my server console + they cant hear its other on the calls (i have pma-voice)
![εικόνα](https://user-images.githubusercontent.com/82971694/219686736-ed3e9a5f-fddb-47f7-bad5-1bc12bfdc094.png)

### Issue Reproduction

just open the twitter and create an account and in the matchmaker app i get this error 

![εικόνα](https://user-images.githubusercontent.com/82971694/219687026-432e410c-b945-420c-9a53-063412bddfcc.png)

**Comment by LiamDormon** [comment]
Not an issue
