### ISSUE TITLE
[V2] Roadmap

### ISSUE THREAD

**Issue by itschip** [project-error/npwd#987]
Here's some rough ideas on what should be done before we release v2.

[ ] - Redesign with RadixUI and Tailwind. Get rid of MUI and emotion.
[ ] - Use React Query for fetch. Might heavily reduce our use of states with Recoil.
[ ] - Update React Router to v6, if not a complete shitshow.
[ ] - Try to use Vite, atleast for external apps w/ vite-plugin-federation (#988)
[ ] - Better support for default contact
[ ] - Action apps
[ ] - Playing sound from entities 
[ ] - Dynamic phone number format

**Comment by LukeWasTakenn** [comment]
Something that would probably be nice which would tie into the redesign (I have mentioned this before) is client based theming, perhaps something similar to Google's Material 3 (You) dynamic color system?

https://m3.material.io/styles/color/dynamic-color/overview

**Comment by AvarianKnight** [comment]
Closing this as a v2 is not currently planned anymore.
