### ISSUE TITLE
Bug: MariaDB Issue with NWPD

### ISSUE THREAD

**Issue by GravityScriptsV2** [project-error/npwd#989]
### Development Issue

Unsure

### Phone Version

1.70

### Issue Description

Error: Unhandled promise failure: TypeError: Cannot read properties of null (reading '2')
[         script:npwd]     at parseUri (@npwd/resources/dist/server/server.js:47616:35)
[         script:npwd]     at _BootDb.doesPlayerTableExist (@npwd/resources/dist/server/server.js:47682:25)
[         script:npwd]     at _BootService.validateDatabaseSchema (@npwd/resources/dist/server/server.js:47736:52)
[         script:npwd]     at _BootService.handleResourceStarting (@npwd/resources/dist/server/server.js:47731:16)
[         script:npwd]     at @npwd/resources/dist/server/server.js:47788:32
[         script:npwd]     at citizen:/scripting/v8/main.js:477:30
[         script:npwd]     at Number.__cfx_wrap_1 (citizen:/scripting/v8/main.js:23:12)
[         script:npwd]     at citizen:/scripting/v8/main.js:29:16
[         script:npwd]     at citizen:/scripting/v8/main.js:450:3

### Issue Reproduction

 1. Go to Github
 2. Click on Download, put it inside ur server
 3. Go to tx admin and see error

**Comment by AvarianKnight** [comment]
Do you have a syntax error in your `mysql_connection_string`?

**Comment by GravityScriptsV2** [comment]
I do not

**Comment by GravityScriptsV2** [comment]
MySQL string looks fine and works with everything else.

**Comment by AvarianKnight** [comment]
Do you have any special characters in it, iirc it wont work properly if you do, otherwise I'm not really sure what the issue is

**Comment by GravityScriptsV2** [comment]
I believe I have 3 special characters

**Comment by derletzteritter** [comment]
Hey! Thanks for the issue! This should fixed the latest version.
