### ISSUE TITLE
No UI

### ISSUE THREAD

**Issue by WOW-sys-32** [project-error/npwd#992]
### Development Issue

Yes

### Phone Version

1.7.0
FIVEM:2189

### Issue Description

Each time i press F1 in my server the phone shows up on hand but the phone UI doesnt

### Issue Reproduction

sq

### Evidence

![image](https://user-images.githubusercontent.com/72619073/228377133-cb0b3085-86e5-4cb3-a5b1-caa700225d8d.png)

**Comment by NeyZzO** [comment]
Try this
https://projecterror.dev/docs/npwd/faq#my-phone-crashed-after-a-settings-update

**Comment by WOW-sys-32** [comment]
> Try this https://projecterror.dev/docs/npwd/faq#my-phone-crashed-after-a-settings-update

this didnt work sadly

**Comment by necaz1337** [comment]
same problem where with esx legacy
![image](https://user-images.githubusercontent.com/120249798/229354592-cdf8f38e-61f8-4db1-8803-f2100e377ef4.png)

**Comment by necaz1337** [comment]
![image](https://user-images.githubusercontent.com/120249798/229354694-96214e1c-7664-492b-8d7a-73d49e583e84.png)
after this https://projecterror.dev/docs/npwd/faq/#my-phone-crashed-after-a-settings-update 
i get this log in console but ui  not working

**Comment by necaz1337** [comment]
all last 3 versions not working.

**Comment by mahanmoulaei** [comment]
Yes this a bug as mentioned in https://github.com/project-error/npwd/issues/981 and a temporary workaround for this is to press ESC before opening the phone

**Comment by HypnoticCity** [comment]
I am having this issue as well. However, pressing esc first does nothing for me. Character pulls out the phone but no UI displays. 
I also get these errors in my console when I start the script:

Settings Schema was invalid, applying default settings (@npwd/resources/html/3054.js:1)
TypeError: Failed to execute 'fetch' on 'Window': The global scope is shutting down. (@npwd/resources/html/4502.js:1)
TypeError: Cannot read properties of null (reading 'cssRules') (@npwd/resources/html/3935.js:2)
Could not find a config file! TypeError: Failed to execute 'fetch' on 'Window': The global scope is shutting down. (@npwd/resources/html/3054.js:1)

**Comment by AvarianKnight** [comment]
This should've been fixed, if not please open a new issue.
