### ISSUE TITLE
Phone time outs & dont load in server

### ISSUE THREAD

**Issue by Daniiel35** [project-error/npwd#998]
![Screenshot 2023-04-28 201520](https://user-images.githubusercontent.com/95129567/235146575-3ecfad8d-2cc8-42d9-88c5-0439e22e541f.png)
I have been having this issue for a week now, I have been flying into the server that i play for 2 years with no issues and the NPWD script has been used for a while now no issues, all of a sudden a week ago, i flew in and found that the map didn't load & the npwd script was timing out at 15000ms & was crashing my game, i have completed a reinstall of fivem, gta & windows and i am still having this issue & the owner of the server can't fix this as its the client issue but this is a issue that is coming from the npwd script itself

**Comment by LiamDormon** [comment]
This is unrelated to npwd, those timeouts on the client are printed when something on the server side is going wrong. If there was a client issue there would be a client error, not a timeout.

**Comment by AvarianKnight** [comment]
Closing this issue as it makes no sense that this error would lead to a crash as Mojito said.
